-- Restore original text for all City-States
UPDATE Language_en_US
SET Text = 'Once a small fishing village known as Havn, Copenhagen is now the largest city and capital of the Kingdom of Denmark. While some archaeological finds date the town back to the late Viking age, the founding of Copenhagen is traditionally set in 1167, when the Danish Bishop Absalon fortified the harbor town. The well-protected harbor established Copenhagen''s importance as a center of trade and commerce for centuries to come, and it was made the capital of Denmark early in the 15th century. Unfortunately, other civilizations also noticed the natural riches of Copenhagen''s harbor, and the city was attacked numerous times, especially by the Hanseatic League (a trade organization running a monopoly along the coast of Northern Europe).[NEWLINE][NEWLINE]In 1658 the Swedes unsuccessfully tried to take the city, but in 1807 the British succeeded where they could not; a preemptive naval blockade, following by a sweeping firebombing bombardment on civilian buildings and its failing old defenses, caused massive damage to the city and left hundreds dead. After the end of the Napoleonic wars, the city began to rebuild and expand over the now useless defensive inland moats, improving sanitation and incorporating nearby towns in the process. Copenhagen was occupied by the Germans in World War II, but did not sustain any substantial damage and continued to expand greatly after the war''s end.[NEWLINE][NEWLINE]Copenhagen is now recognized as one of the up-and-coming cities in Europe and is ranked the "most livable city in the world" for its wonderful quality of life. The city is also renowned for its extensive public infrastructure and environmentally-friendly policies. Copenhagen is now one of the most visited cities in Europe and has become a veritable Mecca for the world''s new architects, chefs, and designers.'
WHERE Tag = 'TXT_KEY_CIV5_COPENHAGEN_TEXT';

UPDATE Language_zh_CN
SET Text = '哥本哈根曾经是一个名为 Havn 的小渔村，现在是丹麦王国最大的城市和首都。虽然一些考古发现表明该镇的历史可以追溯到维京时代晚期，但传统上哥本哈根的建城时间是 1167 年，当时丹麦主教阿布萨隆 (Absalon) 加固了这座海港小镇。受到良好保护的港口确立了哥本哈根作为未来几个世纪贸易和商业中心的重要性，并于 15 世纪初成为丹麦的首都。不幸的是，其他文明也注意到了哥本哈根港口的自然财富，这座城市多次遭到袭击，特别是汉萨同盟（一个沿北欧海岸垄断的贸易组织）。[NEWLINE][NEWLINE]1658 年，瑞典人试图占领这座城市，但没有成功，但 1807 年，英国人却成功了。先发制人的海上封锁，随后对民用建筑及其失效的旧防御设施进行全面的燃烧弹轰炸，对该市造成了巨大破坏，造成数百人死亡。拿破仑战争结束后，这座城市开始在现已无用的防御性内陆护城河上进行重建和扩建，改善卫生条件并将附近的城镇纳入其中。哥本哈根在第二次世界大战中被德国占领，但没有受到任何实质性破坏，并在战争结束后继续大幅扩张。[NEWLINE][NEWLINE]哥本哈根现已被公认为欧洲新兴城市之一，并以其美妙的生活质量被评为“世界上最宜居的城市”。该市还以其广泛的公共基础设施和环保政策而闻名。哥本哈根现在是欧洲访问量最大的城市之一，并已成为世界新建筑师、厨师和设计师名副其实的圣地。'
WHERE Tag = 'TXT_KEY_CIV5_COPENHAGEN_TEXT';

UPDATE Language_en_US
SET Text = 'The ancient city of Kathmandu, capital to the highly-elevated country of Nepal, traces its history back almost 2,000 years to the dawn of the first millennium AD. Steeped in both Hindu and Buddhist traditions, the city of Kathmandu was named after a great temple found at the site known as "Kasthamandap," said to have been constructed from the timber of a single tree in the 16th century.[NEWLINE][NEWLINE]Long before the city''s establishment, the Kathmandu Valley was inhabited by the Newar people, ancestors to the modern Newars who continue to live throughout Nepal. The Newars are responsible for many of the unique characteristics that have come to be recognized as symbolic of Nepal, including the pagoda style architecture that was adapted over the centuries from both Chinese and Indian designs.[NEWLINE][NEWLINE]During the reign of the Malla Dynasty, who ruled Kathmandu for over 500 years beginning in the 12th century, many of the city''s most notable temples and pagodas were constructed. Though the city was often fraught with conflict and turmoil, leading to the destruction of many of the earliest structures, dozens of magnificent examples remain today. In 2006, the collective of monuments within Kathmandu was designated as a UNESCO World Heritage site, acknowledging the cultural significance of the historic city.[NEWLINE][NEWLINE]In the present-day, Kathmandu is home to more than one million residents, with an economy supported by the production of local crafts as well as an increasingly large tourist population. As the city continues to grow and modernize, the local government faces a difficult task in dealing with urbanization and pollution issues.'
WHERE Tag = 'TXT_KEY_CIV5_KATHMANDU_TEXT';

UPDATE Language_zh_CN
SET Text = '古城加德满都是尼泊尔海拔较高的国家的首都，其历史可以追溯到公元第一个千年之初，已有近 2000 年的历史。加德满都这座城市深受印度教和佛教传统的影响，以在“Kasthamandap”遗址发现的一座宏伟寺庙命名，据说这座寺庙是 16 世纪用一棵树的木材建造的。[NEWLINE][NEWLINE]早在这座城市建立之前，加德满都谷地就居住着尼瓦尔人，他们是现代尼瓦尔人的祖先，他们继续居住在尼泊尔各地。尼瓦尔人创造了许多被认为是尼泊尔象征的独特特征，包括几个世纪以来根据中国和印度设计改编的宝塔式建筑。[NEWLINE][NEWLINE]从 12 世纪开始，马拉王朝统治加德满都 500 多年，在其统治期间，建造了这座城市许多最著名的寺庙和宝塔。尽管这座城市经常充满冲突和动乱，导致许多最早的建筑被毁，但至今仍保留着数十座宏伟的建筑。 2006 年，加德满都的古迹群被指定为联合国教科文组织世界遗产，承认了这座历史名城的文化意义。[NEWLINE][NEWLINE]如今，加德满都拥有超过一百万居民，经济由当地工艺品生产和日益庞大的游客人口支撑。随着城市的不断发展和现代化，当地政府在处理城市化和污染问题方面面临着艰巨的任务。'
WHERE Tag = 'TXT_KEY_CIV5_KATHMANDU_TEXT';

UPDATE Language_en_US
SET Text = 'According to legend, Oslo was founded by King Harald Hardrada (or Hardråde) of Norway in 1048, but archaeological excavations show that some urban settlement at the site preceded that date. The first King of Norway did not reside in the city until much later, sometime in the early 14th century AD, when it became officially regarded as the capital city of the country.[NEWLINE][NEWLINE]Unfortunately (as medieval cities were wont to do), Oslo was destroyed several times by fire in the coming centuries, and in 1624 King Christian IV ordered the city rebuilt at a new site across the bay; the city was also renamed Christiana in honor of its new founding. Christiana was a local center of commerce, but its importance declined while Norway was a part of Denmark, during which its growth slowed to a halt. After the two countries separated in 1814, Christiana grew into the largest city in Norway (overtaking Bergen), as the newly founded University of Oslo helped to fuel the population and economy. The city''s name was restored to "Oslo" in 1925.[NEWLINE][NEWLINE]Growth in the city has remained a source of contention, as the citizens fight both growing up (with skyscrapers) and out (destroying the local farming and fishing communities). The last century has seen a grand increase in the economy and industry of the city, and Oslo now is home to some of the world''s largest maritime shipping companies. Oslo has also recently gained the dubious honor of being the most expensive city in the world to live in, as space for apartments grows to an even higher premium.'
WHERE Tag = 'TXT_KEY_CIV5_OSLO_TEXT';

UPDATE Language_zh_CN
SET Text = '据传说，奥斯陆由挪威国王哈拉尔·哈德拉达 (Harald Hardrada)（或哈德拉德 (Hardrade)）于 1048 年建立，但考古发掘表明，该地点的一些城市定居点早于该日期。挪威的第一位国王直到很久以后，即公元 14 世纪初期才居住在这座城市，当时它被正式视为该国的首都。[NEWLINE][NEWLINE]不幸的是（正如中世纪城市惯常发生的那样），奥斯陆在接下来的几个世纪中多次被大火摧毁，1624 年，国王克里斯蒂安四世下令在海湾对面的新地点重建这座城市；为了纪念它的新成立，这座城市也更名为克里斯蒂安娜。克里斯蒂安娜是当地的商业中心，但随着挪威成为丹麦的一部分，其重要性下降，在此期间其增长放缓至停止。 1814 年两国分离后，克里斯蒂娜发展成为挪威最大的城市（超过卑尔根），新成立的奥斯陆大学帮助推动了人口和经济的发展。 1925年，该市的名称恢复为“奥斯陆”。[NEWLINE][NEWLINE]城市的发展仍然是争论的焦点，因为市民们既在成长（建设摩天大楼）又在奋斗（摧毁当地的农业和渔业社区）。上个世纪，这座城市的经济和工业取得了巨大的增长，奥斯陆现在是一些世界上最大的海运公司的所在地。奥斯陆最近还获得了世界上居住成本最昂贵的城市的可疑荣誉，因为公寓空间的溢价变得更高。'
WHERE Tag = 'TXT_KEY_CIV5_OSLO_TEXT';

UPDATE Language_en_US
SET Text = 'Quebec City, founded in 1608 by the French explorer Samuel de Champlain, was once the location of a small Iroquois village known as Stadaconé. Taking its name from the Algonquin word "Kebec," meaning "where the river becomes narrow," the settlement of Quebec City would grow to become the center of French colonial efforts in North America throughout the 17th century.[NEWLINE][NEWLINE]During its early development, Quebec City served not only as a valuable trade outpost, but also as a home to various Christian missionaries and an increasing number of permanent settlers. The fur and lumber industries provided the French with valuable resources that strengthened early efforts to expand their reach in North America. Briefly passing under British rule from 1629 until 1632, the city would otherwise be controlled by the French for over 150 years, despite several sieges. In 1663, Quebec City was officially named the capital of New France, having already served as the capital of French Canada since its founding.[NEWLINE][NEWLINE]The French would finally lose control of the colony in 1759 to the British during the Battle of the Plains of Abraham. Britain would remain in control of Quebec City until the formation of the Dominion of Canada in 1867. Following the Constitution Act of Canada, Quebec City would become the capital of the Canadian Province of Quebec.[NEWLINE][NEWLINE]Today, Quebec City is home to over 500,000 residents, and continues to thrive with a rich cultural heritage. Named a UNESCO World Heritage site in 1985, Quebec City still maintains much of the historic architecture from its colonial roots. Of particular interest are the famous Château Frontenac hotel, and the Roman Catholic churches of Notre-Dame de Québec and Notre-Dame-des-Victoires, both originally constructed in the 17th century.'
WHERE Tag = 'TXT_KEY_CIV5_QUEBEC_CITY_TEXT';

UPDATE Language_zh_CN
SET Text = '魁北克市由法国探险家塞缪尔·德·尚普兰 (Samuel de Champlain) 于 1608 年建立，曾经是一个名为斯塔达科内 (Stadaconé) 的易洛魁小村庄所在地。魁北克市的名字来源于阿尔冈昆语“Kebec”，意思是“河流变窄的地方”，魁北克市的定居点在整个 17 世纪逐渐发展成为法国在北美殖民活动的中心。[NEWLINE][NEWLINE]在其早期发展过程中，魁北克市不仅是一个有价值的贸易前哨，也是各种基督教传教士和越来越多的永久定居者的家园。毛皮和木材工业为法国人提供了宝贵的资源，加强了法国人早期扩大其在北美影响力的努力。从 1629 年到 1632 年，这座城市曾短暂受英国统治，尽管多次遭到围攻，但这座城市仍将被法国人控制 150 多年。 1663年，魁北克市被正式命名为新法兰西的首都，自建国以来一直是法属加拿大的首都。[NEWLINE][NEWLINE]1759 年，法国人最终在亚伯拉罕平原战役中将殖民地的控制权拱手让给了英国人。英国将继续控制魁北克市，直至 1867 年加拿大自治领成立。根据加拿大宪法法案，魁北克市将成为加拿大魁北克省的首府。[NEWLINE][NEWLINE]如今，魁北克市拥有超过 500,000 名居民，并凭借丰​​富的文化遗产继续繁荣发展。魁北克市于 1985 年被联合国教科文组织列为世界遗产，至今仍保留着许多殖民时期的历史建筑。特别令人感兴趣的是著名的芳提娜城堡酒店以及魁北克圣母院和胜利圣母院的罗马天主教堂，这两个教堂最初均建于 17 世纪。'
WHERE Tag = 'TXT_KEY_CIV5_QUEBEC_CITY_TEXT';

UPDATE Language_en_US
SET Text = 'Records show that while the area around Seoul has been settled from the Paleolithic Age, the city wasn''t officially founded until 18 BC when the kingdom of Baekje built its capital city Wiryeseong at the site. In time, Baekje developed from a small minor state into one of the major Three Kingdoms of Korea, a group of countries which dominated the peninsula for most of the first millennium. Over time, Seoul grew into a formidable city and held great political significance.[NEWLINE][NEWLINE]Eventually the Three Kingdoms were consolidated under one rule, and in 1394 AD the capital of this new country was moved to Seoul. Large walls were built around the city, as much to keep out thieves as well as tigers and other unwanted large, scary animals. Each day the gates were opened at dawn and closed at dusk, keeping the city isolated and protected. Eventually, Seoul opened its gates to the influx of westerners arriving in the east during the late 1800s, and the city began to modernize. In fact, Seoul was the first eastern city to have electricity, running water, and the telephone.[NEWLINE][NEWLINE]Things continued well for Seoul until World War I when the Japanese occupied Korea in 1910; the country remained under Japanese rule until 1945. After Korea''s liberation, the Republic of Korea was founded (modern day South Korea), and Seoul was named as its capital. During the Korean War, starting in 1950, Seoul changed hands between North and South Korea many times, it being less than 100 miles from the border. The city endured heavy damage during this time, with over two hundred thousand buildings in ruins.[NEWLINE][NEWLINE]After the war, the city was the focus of a huge reconstruction effort and an attempt to improve the standard of living for the population, which had swelled with millions of refugees. The city continued its population and economic boom into the 21st century, becoming the third largest metropolitan area in the world and housing a full quarter of South Korea''s population. Seoul has been voted the 2010 Design Capital of the World, boasts one of the world''s most technologically advanced infrastructures, and is home to some of the world''s largest electronic companies.'
WHERE Tag = 'TXT_KEY_CIV5_SEOUL_TEXT';

UPDATE Language_zh_CN
SET Text = '记录显示，虽然首尔周边地区从旧石器时代起就有人定居，但这座城市直到公元前 18 年百济王国在此地建立首都维礼城时才正式建立。随着时间的推移，百济从一个小国发展成为朝鲜三大王国之一，这三个国家在第一个千年的大部分时间里统治着半岛。随着时间的推移，首尔发展成为一座令人敬畏的城市，并具有重大的政治意义。[NEWLINE][NEWLINE]最终，三个王国统一在一个统治之下，并于公元 1394 年将这个新国家的首都迁至首尔。城市周围修建了高大的城墙，以防止小偷、老虎和其他令人讨厌的大型可怕动物。城门每天黎明时打开，黄昏时关闭，保持城市的孤立和保护。最终，首尔在 1800 年代末向东方涌入的西方人敞开了大门，这座城市开始现代化。事实上，首尔是第一个拥有电力、自来水和电话的东部城市。[NEWLINE][NEWLINE]首尔的生活一直很顺利，直到第一次世界大战期间，日本于 1910 年占领了朝鲜半岛。该国一直受日本统治，直到 1945 年。韩国解放后，大韩民国成立（现韩国），首都定为首尔。从1950年开始的朝鲜战争期间，首尔在朝鲜和韩国之间多次易手，距离边境不到100英里。在此期间，这座城市遭受了严重破坏，超过二十万座建筑物成为废墟。[NEWLINE][NEWLINE]战后，这座城市成为大规模重建工作的重点，并试图提高人口的生活水平，其中有数百万难民。进入 21 世纪，这座城市的人口和经济持续繁荣，成为世界第三大都市区，居住着韩国四分之一的人口。首尔被评为 2010 年世界设计之都，拥有世界上技术最先进的基础设施之一，并且是一些世界上最大的电子公司的所在地。'
WHERE Tag = 'TXT_KEY_CIV5_SEOUL_TEXT';

UPDATE Language_en_US
SET Text = 'Sydney, located on the southeastern coast of Australia, was not only the first British colony established on the continent, but also the first European settlement of any kind. Founded by Admiral Arthur Phillip in 1788 as a penal colony, Sydney''s early development would be led initially by convicts, and later continued by retired soldiers and settlers arriving from Britain. Over time, Sydney would grow to become the largest and perhaps most famous city in Australia, with a population of over 4 million people today.[NEWLINE][NEWLINE]Scouted by James Cook in 1770, the original landing site, known famously as "Botany Bay", was deemed unsuitable for the location of a permanent settlement. The nearby Sydney Cove named for "Lord Sydney" Thomas Townshend, would prove to be the ideal location. This area is thought to have been inhabited by Australian Aborigines for several thousand years prior to the arrival of British colonists, and numerous tribes were found in the region upon their arrival. Despite the efforts of Admiral Phillip to regulate the interaction between colonists and the local tribesmen, thousands of Aborigines would die from smallpox and measles spread by colonial expeditions.[NEWLINE][NEWLINE]During its later history, Sydney experienced a massive population boom throughout the 19th century as gold was discovered in neighboring areas, particularly Bathurst. Greatly expanding its industrial development during this period, by the 1920s, Sydney''s population would reach over 1 million and the city would continue expanding to meet its growing infrastructure needs.[NEWLINE][NEWLINE]In the present day, Sydney is known for its financial development, serving as the economic hub for all of Australia. Home to numerous major banks and financial institutions, the Australian Securities Exchange is also located in Sydney. Since the early 1800s, the date of Sydney''s founding, January 26th, has been celebrated as Australia''s national day, commemorating not only the city''s history, but also its importance to Australia in the present day.'
WHERE Tag = 'TXT_KEY_CIV5_SYDNEY_TEXT';

UPDATE Language_zh_CN
SET Text = '悉尼位于澳大利亚东南海岸，不仅是英国在澳大利亚大陆建立的第一个殖民地，也是欧洲第一个定居点。悉尼由阿瑟·菲利普 (Arthur Phillip) 海军上将于 1788 年建立，当时是一个流放地，悉尼的早期发展最初由罪犯领导，后来由来自英国的退役士兵和定居者继续发展。随着时间的推移，悉尼将发展成为澳大利亚最大、或许也是最著名的城市，如今人口超过 400 万。[NEWLINE][NEWLINE]1770 年，詹姆斯·库克 (James Cook) 勘察到最初的登陆地点，即著名的“植物湾”，被认为不适合永久定居。附近以“悉尼勋爵”托马斯·汤森德 (Thomas Townshend) 命名的悉尼湾 (Sydney Cove) 被证明是理想的地点。据认为，在英国殖民者到来之前，澳大利亚原住民已经在该地区居住了数千年，并且在英国殖民者抵达后，在该地区发现了许多部落。尽管菲利普海军上将努力规范殖民者与当地部落成员之间的互动，但仍有数千名原住民死于殖民探险传播的天花和麻疹。[NEWLINE][NEWLINE]在其后来的历史中，悉尼在整个 19 世纪经历了大规模的人口激增，因为邻近地区（尤其是巴瑟斯特）发现了金矿。在此期间，悉尼的工业发展得到了极大的扩展，到了 1920 年代，悉尼的人口将达到 100 万以上，并且城市将继续扩张以满足其不断增长的基础设施需求。[NEWLINE][NEWLINE]如今，悉尼以其金融发展而闻名，是整个澳大利亚的经济中心。澳大利亚证券交易所也位于悉尼，是众多主要银行和金融机构的所在地。自 1800 年代初以来，悉尼的建城日 1 月 26 日一直被视为澳大利亚的国庆日，不仅纪念这座城市的历史，也纪念其对当今澳大利亚的重要性。'
WHERE Tag = 'TXT_KEY_CIV5_SYDNEY_TEXT';

-- Tweak Rio de Janeiro's description
UPDATE Language_en_US
SET Text = 'Portuguese explorers first came across the Rio de Janeiro area in 1502 AD, which was at the time inhabited by four different groups of indigenous peoples. A small fortified settlement was erected at the site, both to deal with the natives and to fend off encroaching attacks from French pirates. On March 1, 1565, the city center was officially founded. The fertile land surrounding the settlement was planted with sugarcane and provided all of the city''s early income. The small city grew to about 8,000 people by 1700, but two thirds of these were probably slaves.[NEWLINE][NEWLINE]About this time scouts found gold and diamonds in the neighboring hills, generating a huge influx of both wealth and immigrants. The city tripled in size and the colonial capital was transferred here in 1763. Rio continued to wildly grow and the city spilled beyond its fortified walls. Many large Romanesque aqueducts were also built at this time, the ruins of which still stand in the city. However, towards the end of the century the mines began to dry up and Central America entered the world economy with a strong sugar market of its own, both of which put Rio in a precarious position. Exports had fallen by more than half of what they were by 1796.[NEWLINE][NEWLINE]Coffee saved the day for Rio. In 1808 the Portuguese royal family fled to the city to escape Napoleon''s invasion of Portugal, temporarily transforming Rio into the capital of the Portuguese Empire. They ordered the growing of the bean and resettled themselves in Brazil, bringing a new-found prosperity to the colony. Expansion of the coffee plantations gave birth to a new wave of improvements in the city, and large manor homes were built, streets were paved, and fine academic institutions were founded.[NEWLINE][NEWLINE]In 1822 Prince Pedro I proclaimed Brazil''s independence, and named Rio as the capital of the new empire. When the country replaced the monarchy with a republic in 1889, it kept Rio as the capital city. Rio was further transformed into a modern city through the early 1900''s as streets were widened, health conditions of its populace were improved, and the surrounding swamps were drained and reclaimed for future building sites. In 1960 the capital was moved to the newly constructed city of Brasilia, and the growth of Rio finally began to slow.[NEWLINE][NEWLINE]Rio de Janeiro is famous worldwide for its carnival celebrations, the invention of samba music, the Cristo Redentor (a modern Wonder of the World), and its landmark beaches. Despite challenges related to urbanization and crime, it remains one of Brazil''s most vibrant cities and a major cultural and economic hub in South America. Millions of tourists continue to visit each year to sample its charm, beauty, and relaxed spirit.'
WHERE Tag = 'TXT_KEY_CIV5_RIODEJANEIRO_TEXT';

UPDATE Language_zh_CN
SET Text = '葡萄牙探险家于公元 1502 年首次来到里约热内卢地区，当时该地区居住着四个不同的土著民族。在该地点建立了一个小型的防御工事定居点，既是为了对付当地人，也是为了抵御法国海盗的入侵。 1565年3月1日，市中心正式成立。定居点周围肥沃的土地种植了甘蔗，提供了城市早期的全部收入。到 1700 年，这座小城市的人口已增至约 8,000 人，但其中三分之二可能是奴隶。[NEWLINE][NEWLINE]大约在这个时候，侦察兵在附近的山上发现了黄金和钻石，带来了大量的财富和移民的涌入。这座城市的规模扩大了两倍，殖民首都于 1763 年迁至此地。里约热内卢继续疯狂发展，城市已超出其坚固的城墙。许多大型罗马式渡槽也在此时建成，其遗址至今仍矗立在城市中。然而，到本世纪末，矿山开始枯竭，中美洲凭借自己强大的食糖市场进入世界经济，这两者都使力拓陷入了岌岌可危的境地。到 1796 年，出口量下降了一半以上。[NEWLINE][NEWLINE]咖啡拯救了里约热内卢。 1808年，葡萄牙王室为躲避拿破仑入侵葡萄牙而逃往该市，暂时将里约改为葡萄牙帝国的首都。他们下令种植这种豆子，并在巴西定居，为殖民地带来了新的繁荣。咖啡种植园的扩张催生了城市的新一轮改善浪潮，修建了大型庄园、铺设了街道、建立了优秀的学术机构。[NEWLINE][NEWLINE]1822年，佩德罗一世亲王宣布巴西独立，并将里约定为新帝国的首都。 1889 年，该国以共和制取代君主制，并保留里约热内卢作为首都。到了 1900 年代初，里约进一步转变为一座现代化城市，街道拓宽，民众的健康状况得到改善，周围的沼泽被排干并开垦为未来的建筑工地。 1960年首都迁往新建的巴西利亚市，里约的增长终于开始放缓。[NEWLINE][NEWLINE]里约热内卢因其狂欢节庆祝活动、桑巴音乐的发明、救世基督像（现代世界奇迹）及其地标性海滩而闻名于世。尽管面临城市化和犯罪方面的挑战，它仍然是巴西最具活力的城市之一，也是南美洲的主要文化和经济中心。每年都有数以百万计的游客前来参观，体验它的魅力、美丽和轻松的精神。'
WHERE Tag = 'TXT_KEY_CIV5_RIODEJANEIRO_TEXT';

-- Endogenize Venice name so civilopedia can find the Civ Venice
UPDATE Language_en_US
SET Text = 'Venezia'
WHERE Tag = 'TXT_KEY_CITYSTATE_VENICE';

UPDATE Language_zh_CN
SET Text = '威尼斯'
WHERE Tag = 'TXT_KEY_CITYSTATE_VENICE';

-- The Scramble for Africa scenario City-States have existing Civilopedia entries in the BNW files, but they are much shorter and less detailed
-- For parity with their peers, we edit and expand on those as well
UPDATE Language_en_US
SET Text = 'The Bornu Empire flourished from 1380 to 1893 AD, dominating the lands of what is now northeastern Nigeria, Chad, and parts of Cameroon. It was the successor state to the Kanem Empire, ruled by the Sayfawa dynasty, whose origins stretched back centuries in the central Sahel. The empire''s capital shifted westward over time to better control trade routes and defend against nomadic incursions. Bornu became a hub of Saharan commerce, exporting horses, textiles, and salt, and importing luxury goods from North Africa and beyond.[NEWLINE][NEWLINE]Under the reign of Idris Alooma (1571-1603), Bornu reached its greatest power, territorial extent, and prosperity. Alooma was a skilled statesman and military strategist who reformed the army, improved administration, and introduced new agricultural practices. His reign brought unprecedented stability, allowing trade to flourish along the trans-Saharan routes. The empire''s influence extended deep into the Sahel, and its scholars and clerics maintained close ties with Islamic centers in Cairo and Mecca.[NEWLINE][NEWLINE]Though Bornu endured into the late 18th century, it was weakened by internal disputes and external threats. The Fulani Jihad of the early 1800s toppled the kingdom into decades of instability. Conquered by Sudanese forces in 1893, Bornu briefly fell under Islamic Sudanese rule before being absorbed into the British Empire, forming the nucleus of the colony of Nigeria.'
WHERE Tag = 'TXT_KEY_CIV5_BORNU_TEXT';

UPDATE Language_zh_CN
SET Text = '博尔努帝国从公元 1380 年到 1893 年繁荣，统治着现在尼日利亚东北部、乍得和喀麦隆部分地区的土地。它是卡内姆帝国的继承国，由赛法瓦王朝统治，其起源可以追溯到几个世纪前的萨赫勒中部地区。随着时间的推移，帝国的首都向西转移，以更好地控制贸易路线并防御游牧民族的入侵。博尔努成为撒哈拉商业的中心，出口马匹、纺织品和盐，并从北非及其他地区进口奢侈品。[NEWLINE][NEWLINE]在伊德里斯·阿卢马（Idris Alooma，1571-1603 年）的统治下，博尔努达到了最强大的实力、领土范围和繁荣。阿卢马是一位熟练的政治家和军事战略家，他改革了军队，改善了行政管理，并引入了新的农业实践。他的统治带来了前所未有的稳定，使跨撒哈拉航线沿线的贸易蓬勃发展。帝国的影响力深入萨赫勒地区，其学者和神职人员与开罗和麦加的伊斯兰中心保持着密切的联系。[NEWLINE][NEWLINE]尽管博尔努一直延续到 18 世纪末，但它因内部争端和外部威胁而被削弱。 1800 年代初的富拉尼圣战使该王国陷入数十年的不稳定。 1893 年，博尔努被苏丹军队征服，曾短暂受伊斯兰苏丹统治，随后被大英帝国吞并，成为尼日利亚殖民地的核心。'
WHERE Tag = 'TXT_KEY_CIV5_BORNU_TEXT';

UPDATE Language_en_US
SET Text = 'In the late 19th century, Msiri, the ambitious son of an East African trader, established the town of Bunkeya in present-day Katanga Province, Democratic Republic of Congo. From this base, he forged the Bayeke Kingdom, controlling a vast territory in the east Congo Basin. Bunkeya became a strategic center of commerce, trading ivory, copper, iron ore, salt, and slaves to Arab-Swahili merchants on the coast. In exchange, Msiri acquired firearms and ammunition, cementing his power and expanding his influence.[NEWLINE][NEWLINE]By the 1880s, Bunkeya had drawn the attention of European powers. The British explored potential alliances with Msiri, prompting King Leopold II of Belgium to act swiftly to secure the region for his Congo Free State. Leopold dispatched three expeditions to Bunkeya; the first two failed to secure Msiri''s submission.[NEWLINE][NEWLINE]In 1891, a third expedition, led from Zanzibar, forced Bayeke forces to retreat. Msiri was killed during a confrontation shortly thereafter, and Bunkeya was absorbed into the Congo Free State. Its incorporation marked the end of one of the last major indigenous Central African kingdoms to resist European colonial control.'
WHERE Tag = 'TXT_KEY_CIV5_BUNKEYA_TEXT';

UPDATE Language_zh_CN
SET Text = '19 世纪末，东非商人雄心勃勃的儿子姆西里 (Msiri) 在今刚果民主共和国加丹加省建立了邦克亚 (Bunkeya) 镇。以此为基地，他建立了巴耶克王国，控制了刚果盆地东部的大片领土。邦克亚成为战略商业中心，向沿海的阿拉伯斯瓦希里商人进行象牙、铜、铁矿石、盐和奴隶的贸易。作为交换，姆西里获得了枪支和弹药，巩固了他的权力并扩大了他的影响力。[NEWLINE][NEWLINE]到了 1880 年代，文雅已经引起了欧洲列强的注意。英国探索与姆西里结盟的可能性，促使比利时国王利奥波德二世迅速采取行动，为其刚果自由邦确保该地区的安全。利奥波德派遣了三支探险队前往邦克亚。前两次未能让姆西里屈服。[NEWLINE][NEWLINE]1891年，来自桑给巴尔的第三次远征迫使巴耶克军队撤退。不久之后，姆西里在一次冲突中被杀，邦克亚被并入刚果自由邦。它的合并标志着最后一个抵抗欧洲殖民控制的主要中非本土王国之一的终结。'
WHERE Tag = 'TXT_KEY_CIV5_BUNKEYA_TEXT';

UPDATE Language_en_US
SET Text = 'The Luba people emerged around the 5th century AD in the Upemba Depression, a resource-rich area of central Africa in modern-day Democratic Republic of Congo. From their early settlements, they cultivated a strong culture centered on fishing, agriculture, and metalworking. By the 16th century, the Luba Kingdom had consolidated under skilled rulers, extending its authority over copper mines, palm oil groves, and fertile lands.[NEWLINE][NEWLINE]From the 1580s, successive Luba chieftains expanded their realm rapidly, subduing neighboring peoples and integrating them into a sophisticated system of governance. The Luba became renowned for their artisanship, particularly in woodcarving and metalwork, and for their oral traditions, which preserved the deeds of rulers and the laws of the land. Trade networks brought goods from the Congo River Basin to distant markets.[NEWLINE][NEWLINE]The arrival of European colonial powers in the late 19th century spelled disaster for the kingdom. Pressured by encroaching Belgian forces, the Luba were formally incorporated into the Congo Free State in 1885. A major rebellion in 1895 sought to restore independence, but Belgian forces crushed the uprising, devastating the Luba population and marking the end of their sovereignty.'
WHERE Tag = 'TXT_KEY_CIV5_LUBA_TEXT';

UPDATE Language_zh_CN
SET Text = '卢巴人于公元 5 世纪左右出现在乌彭巴洼地，这是中非资源丰富的地区，位于现代刚果民主共和国。从他们早期的定居点开始，他们就培养了以渔业、农业和金属加工为中心的强大文化。到了 16 世纪，卢巴王国在熟练的统治者的统治下得到巩固，将其权力扩展到铜矿、棕榈油园和肥沃的土地。[NEWLINE][NEWLINE]从1580年代起，历代鲁巴土司迅速扩张疆域，征服周边民族，将他们纳入复杂的治理体系。卢巴人因其手工艺（尤其是木雕和金属制品）以及保存统治者行为和当地法律的口头传统而闻名。贸易网络将货物从刚果河流域运送到遥远的市场。[NEWLINE][NEWLINE]19世纪末欧洲殖民列强的到来给这个王国带来了灾难。在比利时军队入侵的压力下，卢巴人于 1885 年正式并入刚果自由邦。1895 年发生了一场大规模叛乱，试图恢复独立，但比利时军队镇压了起义，摧毁了卢巴人，标志着他们主权的终结。'
WHERE Tag = 'TXT_KEY_CIV5_LUBA_TEXT';

UPDATE Language_en_US
SET Text = 'The Ninsi tribes of the Upper Volta region had long been divided by rivalries and warfare until 1441 AD, when the semi-legendary warrior Wurbi united his people. This victory gave rise to the Mossi Empire, with Wogodogo-later known in French as Ouagadougou-as its capital. Situated at a crossroads of regional trade, Ouagadougou drew merchants from across West Africa, as well as caravans from both the Atlantic and the Sahel.[NEWLINE][NEWLINE]For centuries, the Mossi resisted incursions by powerful neighbors, including the Songhai and the Mali Empires, while maintaining trade in gold, salt, and textiles. Ouagadougou grew into a cosmopolitan center of governance, with the emperor presiding over a court that balanced traditional Mossi customs with Islamic influences brought by traders and scholars.[NEWLINE][NEWLINE]In 1896, French colonial forces under Paul Voulet and Julien Chanoine swept into the region, seeking to consolidate France''s West African holdings. The Mossi were defeated, and Ouagadougou became part of French West Africa. After independence in 1960, it was named the capital of the Republic of Upper Volta, later renamed Burkina Faso, retaining its role as the political and cultural heart of the nation.'
WHERE Tag = 'TXT_KEY_CIV5_OUGADOUGOU_TEXT';

UPDATE Language_zh_CN
SET Text = '上沃尔特地区的宁西部落长期以来因竞争和战争而分裂，直到公元 1441 年，半传奇战士乌尔比 (Wurbi) 团结了他的人民。这次胜利催生了莫西帝国，以沃戈多戈（后来的法语称为​​瓦加杜古）为首都。瓦加杜古位于区域贸易的十字路口，吸引了来自西非各地的商人以及来自大西洋和萨赫勒地区的商队。[NEWLINE][NEWLINE]几个世纪以来，莫西家族抵御了包括桑海帝国和马里帝国在内的强大邻国的入侵，同时维持着黄金、盐和纺织品的贸易。瓦加杜古逐渐发展成为一个国际化的治理中心，皇帝主持的法庭平衡了传统的莫西习俗与商人和学者带来的伊斯兰影响。[NEWLINE][NEWLINE]1896 年，Paul Voulet 和 Julien Chanoine 领导的法国殖民军队席卷该地区，寻求巩固法国在西非的领土。莫西人被击败，瓦加杜古成为法属西非的一部分。 1960年独立后，它被命名为上沃尔特共和国的首都，后更名为布基纳法索，保留了其作为国家政治和文化中心的地位。'
WHERE Tag = 'TXT_KEY_CIV5_OUGADOUGOU_TEXT';

UPDATE Language_en_US
SET Text = 'Founded by the Soninke people around the 11th century AD, Segou rose to prominence as a center of agriculture and trade along the Niger River. Its fertile lands supported farming and fishing, while its markets connected it to other great cities such as Djenne and Timbuktu. The city reached its first golden age under Biton Coulibaly (1712-1755), who transformed it into the capital of the Bambara Kingdom.[NEWLINE][NEWLINE]Biton''s disciplined army and administrative reforms strengthened Segou''s control over surrounding territories. Under Mamary Coulibaly, Segou joined forces with Djenne and Macina, creating a powerful alliance that dominated the middle Niger region. The city''s reputation for craftsmanship and scholarship grew, with artisans producing fine textiles and metalwork.[NEWLINE][NEWLINE]Around 1860, the city fell to El Hadj Umar Tall, a Toucouleur conqueror and Islamic reformer, who converted the populace to Islam. French colonial forces arrived in the 1890s, incorporating Segou into their growing West African empire. The French made Segou the administrative center for the Office du Niger irrigation project, cementing its role as a regional hub.'
WHERE Tag = 'TXT_KEY_CIV5_SEGOU_TEXT';

UPDATE Language_zh_CN
SET Text = '塞古由索宁克人于公元 11 世纪左右建立，作为尼日尔河沿岸的农业和贸易中心而声名鹊起。其肥沃的土地支持农业和渔业，而其市场则将其与杰内和廷巴克图等其他大城市连接起来。在比顿·库利巴利（Biton Coulibaly，1712-1755 年）的统治下，这座城市达到了第一个黄金时代，他将其转变为班巴拉王国的首都。[NEWLINE][NEWLINE]比顿纪律严明的军队和行政改革加强了塞古对周边领土的控制。在马玛丽·库利巴利的领导下，塞古与杰内和马西纳联手，建立了一个统治尼日尔中部地区的强大联盟。这座城市的工艺和学术声誉日益提高，工匠们生产精美的纺织品和金属制品。[NEWLINE][NEWLINE]1860 年左右，这座城市被图库勒尔征服者和伊斯兰改革家哈吉·奥马尔·塔尔 (El Hadj Umar Tall) 攻陷，他使民众皈依了伊斯兰教。法国殖民军队于 1890 年代抵达，将塞古并入其不断壮大的西非帝国。法国人将塞古作为尼日尔灌溉项目办公室的行政中心，巩固了其作为区域枢纽的作用。'
WHERE Tag = 'TXT_KEY_CIV5_SEGOU_TEXT';

UPDATE Language_en_US
SET Text = 'Perched on steep escarpments at the confluence of two rivers in present-day Nigeria, Sokoto was the fortress - capital of the Sokoto Caliphate, one of the largest Islamic states in 19th-century Africa. Before its rise, the site had been the center of several smaller Islamic kingdoms of pre-colonial Sudan, though their records have been largely lost to history.[NEWLINE][NEWLINE]The caliphate was established in the early 1800s by Usman dan Fodio following his Fulani-led jihad. Sokoto became the political and spiritual heart of the new state, reaching its peak of influence in the 1820s. It governed a vast network of emirates through a combination of religious authority and military strength, fostering Islamic scholarship and jurisprudence.[NEWLINE][NEWLINE]The first European to reach Sokoto was the Scottish explorer Hugh Clapperton in 1827. By the turn of the 20th century, British forces sought to control the region as part of their Nigerian colony. In 1903, the English captured Sokoto, dismantling the caliphate and absorbing much of its territory into British Nigeria, ending its two centuries of independence.'
WHERE Tag = 'TXT_KEY_CIV5_SOKOTO_TEXT';

UPDATE Language_zh_CN
SET Text = '索科托坐落在现今尼日利亚两条河流交汇处的陡峭悬崖上，是索科托哈里发国的要塞和首都，索科托哈里发国是 19 世纪非洲最大的伊斯兰国家之一。在其崛起之前，该遗址曾是前殖民苏丹的几个较小的伊斯兰王国的中心，尽管它们的记录大部分已消失在历史中。[NEWLINE][NEWLINE]1800 年代初，乌斯曼·丹·福迪奥 (Usman dan Fodio) 在富拉尼领导的圣战之后建立了哈里发国。索科托成为新国家的政治和精神中心，其影响力在 1820 年代达到顶峰。它通过宗教权威和军事力量的结合来管理庞大的酋长国网络，促进伊斯兰学术和法学的发展。[NEWLINE][NEWLINE]第一个到达索科托的欧洲人是 1827 年苏格兰探险家休·克拉珀顿 (Hugh Clapperton)。到了 20 世纪之交，英国军队试图控制该地区，将其作为尼日利亚殖民地的一部分。 1903 年，英国占领索科托，瓦解了哈里发国，并将其大部分领土并入英属尼日利亚，结束了其两个世纪的独立。'
WHERE Tag = 'TXT_KEY_CIV5_SOKOTO_TEXT';
