-- Shock
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+5% [COLOR_POSITIVE_TEXT]Flanking bonus[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_1_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+5% [COLOR_POSITIVE_TEXT]侧翼奖金[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_1_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+5% [COLOR_POSITIVE_TEXT]Flanking bonus[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_2_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+5% [COLOR_POSITIVE_TEXT]侧翼奖金[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_2_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+5% [COLOR_POSITIVE_TEXT]Flanking bonus[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_3_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+5% [COLOR_POSITIVE_TEXT]侧翼奖金[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_3_HELP';

-- Drill
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]-15% Damage from Cities.'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_1_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]-15% 来自城市的伤害。'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_1_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]-15% Damage from Cities.'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_2_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]-15% 来自城市的伤害。'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_2_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]-15% Damage from Cities.'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_3_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]-15% 来自城市的伤害。'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_3_HELP';

-- Barrage
UPDATE Language_en_US
SET Text = '+10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Units above 50% HP[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_1_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。[NEWLINE]+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]生命值超过 50% 的单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_1_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Units above 50% HP[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_2_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。[NEWLINE]+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]生命值超过 50% 的单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_2_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Units above 50% HP[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_3_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。[NEWLINE]+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]生命值超过 50% 的单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_3_HELP';

-- Accuracy
UPDATE Language_en_US
SET Text = '+10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Units at or below 50% HP[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_1_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。[NEWLINE]+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]HP 等于或低于 50% 的单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_1_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Units at or below 50% HP[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_2_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。[NEWLINE]+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]HP 等于或低于 50% 的单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_2_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Units at or below 50% HP[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_3_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。[NEWLINE]+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]HP 等于或低于 50% 的单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_3_HELP';

-- Targeting
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR].[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Units at or below 50% HP[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_1_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]海军[ENDCOLOR]和[COLOR_POSITIVE_TEXT]土地单位[ENDCOLOR].[NEWLINE]+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]HP 等于或低于 50% 的单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_1_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR].[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Units at or below 50% HP[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_2_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]海军[ENDCOLOR]和[COLOR_POSITIVE_TEXT]土地单位[ENDCOLOR].[NEWLINE]+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]HP 等于或低于 50% 的单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_2_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR].[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Units at or below 50% HP[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_3_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]海军[ENDCOLOR]和[COLOR_POSITIVE_TEXT]土地单位[ENDCOLOR].[NEWLINE]+10% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]HP 等于或低于 50% 的单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_3_HELP';

-- Sentry
UPDATE Language_en_US
SET Text = '+1 [ICON_VISION] Sight.'
WHERE Tag = 'TXT_KEY_PROMOTION_SENTRY_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_VISION]视线。'
WHERE Tag = 'TXT_KEY_PROMOTION_SENTRY_HELP';

UPDATE Language_en_US
SET Text = 'Forlorn Hope'
WHERE Tag = 'TXT_KEY_PROMOTION_SIEGE';

UPDATE Language_zh_CN
SET Text = '绝望的希望'
WHERE Tag = 'TXT_KEY_PROMOTION_SIEGE';

UPDATE Language_en_US
SET Text = '-10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+100% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SIEGE_HELP';

UPDATE Language_zh_CN
SET Text = '-10% [ICON_STRENGTH]战斗力。[NEWLINE]+100% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SIEGE_HELP';

-- Volley
UPDATE Language_en_US
SET Text = '+50% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Fortified Units[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_VOLLEY_HELP';

UPDATE Language_zh_CN
SET Text = '+50% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]强化单位[ENDCOLOR]和[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_VOLLEY_HELP';

-- Medic
UPDATE Language_en_US
SET Text = 'Medic I'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC';

UPDATE Language_zh_CN
SET Text = '军医一号'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC';

UPDATE Language_en_US
SET Text = '+5 HP when [COLOR_POSITIVE_TEXT]Healing[ENDCOLOR] for Units [COLOR_POSITIVE_TEXT]on or adjacent to this tile[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_HELP';

UPDATE Language_zh_CN
SET Text = '+5 HP 当[COLOR_POSITIVE_TEXT]康复[ENDCOLOR]对于单位[COLOR_POSITIVE_TEXT]在此图块上或附近[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_HELP';

UPDATE Language_en_US
SET Text = '+5 HP when [COLOR_POSITIVE_TEXT]Healing[ENDCOLOR] for Units [COLOR_POSITIVE_TEXT]on or adjacent to this tile[ENDCOLOR].[NEWLINE]+5 HP when Healing [COLOR_POSITIVE_TEXT]Outside of Friendly Territory[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_II_HELP';

UPDATE Language_zh_CN
SET Text = '+5 HP 当[COLOR_POSITIVE_TEXT]康复[ENDCOLOR]对于单位[COLOR_POSITIVE_TEXT]在此图块上或附近[ENDCOLOR].[NEWLINE]治疗时 HP +5[COLOR_POSITIVE_TEXT]友好领土之外[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_II_HELP';

-- Amphibious
UPDATE Language_en_US
SET Text = 'Eliminate combat penalties for attacking from the sea or over a river.[NEWLINE]Crossing a river costs only 1 [ICON_MOVES] Movement.[NEWLINE]Ignore Terrain Cost in [COLOR_POSITIVE_TEXT]Marsh[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AMPHIBIOUS_HELP';

UPDATE Language_zh_CN
SET Text = '消除从海上或跨河攻击的战斗惩罚。[NEWLINE]过河仅需1[ICON_MOVES]移动。[NEWLINE]忽略地形成本[COLOR_POSITIVE_TEXT]沼泽[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AMPHIBIOUS_HELP';

-- Cover
UPDATE Language_en_US
SET Text = '+25% [ICON_STRENGTH] Combat Strength when defending against [COLOR_POSITIVE_TEXT]Ranged Attacks[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_COVER_1_HELP';

UPDATE Language_zh_CN
SET Text = '+25% [ICON_STRENGTH]防御时的战斗力[COLOR_POSITIVE_TEXT]远程攻击[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_COVER_1_HELP';

UPDATE Language_en_US
SET Text = '+25% [ICON_STRENGTH] Combat Strength when defending against [COLOR_POSITIVE_TEXT]Ranged Attacks[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_COVER_2_HELP';

UPDATE Language_zh_CN
SET Text = '+25% [ICON_STRENGTH]防御时的战斗力[COLOR_POSITIVE_TEXT]远程攻击[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_COVER_2_HELP';

UPDATE Language_en_US
SET Text = 'Charge I'
WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE';

UPDATE Language_zh_CN
SET Text = '电荷一'
WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength when attacking Units in [COLOR_POSITIVE_TEXT]Open Terrain[ENDCOLOR].[NEWLINE]+20% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Wounded Units[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]攻击单位时的战斗力[COLOR_POSITIVE_TEXT]开放地形[ENDCOLOR].[NEWLINE]+20% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]受伤单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE_HELP';

-- Formation
UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH] Combat Strength VS [COLOR_POSITIVE_TEXT]Mounted Units[ENDCOLOR].[NEWLINE]+15% [ICON_STRENGTH] Combat Strength when defending in [COLOR_POSITIVE_TEXT]Open Terrain[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_1_HELP';

UPDATE Language_zh_CN
SET Text = '+33% [ICON_STRENGTH]战斗力VS[COLOR_POSITIVE_TEXT]安装单位[ENDCOLOR].[NEWLINE]+15% [ICON_STRENGTH]防守时的战斗力[COLOR_POSITIVE_TEXT]开放地形[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_1_HELP';

UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH] Combat Strength VS [COLOR_POSITIVE_TEXT]Mounted Units[ENDCOLOR].[NEWLINE]+15% [ICON_STRENGTH] Combat Strength when defending in [COLOR_POSITIVE_TEXT]Open Terrain[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_2_HELP';

UPDATE Language_zh_CN
SET Text = '+33% [ICON_STRENGTH]战斗力VS[COLOR_POSITIVE_TEXT]安装单位[ENDCOLOR].[NEWLINE]+15% [ICON_STRENGTH]防守时的战斗力[COLOR_POSITIVE_TEXT]开放地形[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_2_HELP';

-- Ambush
UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH] Combat Strength VS [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR].[NEWLINE]+15% [ICON_STRENGTH] Combat Strength when attacking Units in [COLOR_POSITIVE_TEXT]Rough Terrain[ENDCOLOR].[NEWLINE][NEWLINE]Available once you have researched [COLOR_CYAN]{TXT_KEY_TECH_COMBUSTION_TITLE}[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_1_HELP';

UPDATE Language_zh_CN
SET Text = '+33% [ICON_STRENGTH]战斗力VS[COLOR_POSITIVE_TEXT]装甲部队[ENDCOLOR].[NEWLINE]+15% [ICON_STRENGTH]攻击单位时的战斗力[COLOR_POSITIVE_TEXT]崎岖地形[ENDCOLOR].[NEWLINE][NEWLINE]研究完成后即可使用[COLOR_CYAN]{TXT_KEY_TECH_COMBUSTION_TITLE}[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_1_HELP';

UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH] Combat Strength VS [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR].[NEWLINE]+15% [ICON_STRENGTH] Combat Strength when attacking Units in [COLOR_POSITIVE_TEXT]Rough Terrain[ENDCOLOR].[NEWLINE][NEWLINE]Available once you have researched [COLOR_CYAN]{TXT_KEY_TECH_COMBUSTION_TITLE}[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_2_HELP';

UPDATE Language_zh_CN
SET Text = '+33% [ICON_STRENGTH]战斗力VS[COLOR_POSITIVE_TEXT]装甲部队[ENDCOLOR].[NEWLINE]+15% [ICON_STRENGTH]攻击单位时的战斗力[COLOR_POSITIVE_TEXT]崎岖地形[ENDCOLOR].[NEWLINE][NEWLINE]研究完成后即可使用[COLOR_CYAN]{TXT_KEY_TECH_COMBUSTION_TITLE}[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_2_HELP';

-- Supply
UPDATE Language_en_US
SET Text = 'Can Heal [COLOR_POSITIVE_TEXT]Outside of Friendly Territory[ENDCOLOR].[NEWLINE]+5 HP when [COLOR_POSITIVE_TEXT]Healing[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SUPPLY_HELP';

UPDATE Language_zh_CN
SET Text = '可以治愈[COLOR_POSITIVE_TEXT]友好领土之外[ENDCOLOR].[NEWLINE]+5 HP 当[COLOR_POSITIVE_TEXT]康复[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SUPPLY_HELP';

-- March
UPDATE Language_en_US
SET Text = 'Unit will [COLOR_POSITIVE_TEXT]Heal Every Turn[ENDCOLOR], even if it performs an action.'
WHERE Tag = 'TXT_KEY_PROMOTION_MARCH_HELP';

UPDATE Language_zh_CN
SET Text = '单位将[COLOR_POSITIVE_TEXT]每回合治愈[ENDCOLOR]，即使它执行了一个动作。'
WHERE Tag = 'TXT_KEY_PROMOTION_MARCH_HELP';

-- Blitz
UPDATE Language_en_US
SET Text = '+1 [ICON_WAR] Attack.[NEWLINE]Can move after attacking.'
WHERE Tag = 'TXT_KEY_PROMOTION_BLITZ_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_WAR]攻击。[NEWLINE]攻击后可以移动。'
WHERE Tag = 'TXT_KEY_PROMOTION_BLITZ_HELP';

-- Woodsman
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength in [COLOR_POSITIVE_TEXT]Rough Terrain[ENDCOLOR].[NEWLINE]Ignore Terrain Cost in [COLOR_POSITIVE_TEXT]Forest[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Jungle[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_WOODSMAN_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力在[COLOR_POSITIVE_TEXT]崎岖地形[ENDCOLOR].[NEWLINE]忽略地形成本[COLOR_POSITIVE_TEXT]森林[ENDCOLOR]和[COLOR_POSITIVE_TEXT]丛林[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_WOODSMAN_HELP';

-- Logistics
UPDATE Language_en_US
SET Text = '+1 [ICON_WAR] Attack.[NEWLINE]-30% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.'
WHERE Tag = 'TXT_KEY_PROMOTION_LOGISTICS_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_WAR]攻击。[NEWLINE]-30% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_LOGISTICS_HELP';

-- Range
UPDATE Language_en_US
SET Text = '+1 [ICON_RANGE_STRENGTH] Range.[NEWLINE]-20% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.'
WHERE Tag = 'TXT_KEY_PROMOTION_RANGE_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_RANGE_STRENGTH]范围。[NEWLINE]-20% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_RANGE_HELP';

-- Mobility, Mobility I, Mobility II
UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES] Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_MOBILITY_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_MOVES]移动。'
WHERE Tag = 'TXT_KEY_PROMOTION_MOBILITY_HELP';

UPDATE Language_en_US
SET Text = 'Ace Pilot I'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_1';

UPDATE Language_zh_CN
SET Text = '王牌飞行员 I'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_1';

UPDATE Language_en_US
SET Text = '+33% Chance to [COLOR_POSITIVE_TEXT]Intercept[ENDCOLOR] Enemy Air Units.'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_1_HELP';

UPDATE Language_zh_CN
SET Text = '+33% 几率[COLOR_POSITIVE_TEXT]截距[ENDCOLOR]敌方空军单位。'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_1_HELP';

UPDATE Language_en_US
SET Text = 'Ace Pilot II'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_2';

UPDATE Language_zh_CN
SET Text = '王牌飞行员 II'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_2';

UPDATE Language_en_US
SET Text = '+33% Chance to [COLOR_POSITIVE_TEXT]Intercept[ENDCOLOR] Enemy Air Units.[NEWLINE]+33% [ICON_STRENGTH] Combat Strength when [COLOR_POSITIVE_TEXT]Intercepting[ENDCOLOR] Enemy Air Units.'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_2_HELP';

UPDATE Language_zh_CN
SET Text = '+33% 几率[COLOR_POSITIVE_TEXT]截距[ENDCOLOR]敌方空军单位。[NEWLINE]+33% [ICON_STRENGTH]战斗力时[COLOR_POSITIVE_TEXT]拦截[ENDCOLOR]敌方空军单位。'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_2_HELP';

UPDATE Language_en_US
SET Text = 'Ace Pilot III'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_3';

UPDATE Language_zh_CN
SET Text = '王牌飞行员 III'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_3';

UPDATE Language_en_US
SET Text = '+34% Chance to [COLOR_POSITIVE_TEXT]Intercept[ENDCOLOR] Enemy Air Units.[NEWLINE]+33% [ICON_STRENGTH] Combat Strength when [COLOR_POSITIVE_TEXT]Intercepting[ENDCOLOR] Enemy Air Units.[NEWLINE]+1 operational range.'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_3_HELP';

UPDATE Language_zh_CN
SET Text = '+34% 几率[COLOR_POSITIVE_TEXT]截距[ENDCOLOR]敌方空军单位。[NEWLINE]+33% [ICON_STRENGTH]战斗力时[COLOR_POSITIVE_TEXT]拦截[ENDCOLOR]敌方空军单位。[NEWLINE]+1 作战范围。'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_3_HELP';

UPDATE Language_en_US
SET Text = 'Ace Pilot IV'
WHERE Tag = 'TXT_KEY_PROMOTION_SORTIE';

UPDATE Language_zh_CN
SET Text = '王牌飞行员 IV'
WHERE Tag = 'TXT_KEY_PROMOTION_SORTIE';

UPDATE Language_en_US
SET Text = '+34% [ICON_STRENGTH] Combat Strength when [COLOR_POSITIVE_TEXT]Intercepting[ENDCOLOR] Enemy Air Units.[NEWLINE]+1 operational range.[NEWLINE]+1 [COLOR_POSITIVE_TEXT]Interception[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SORTIE_HELP';

UPDATE Language_zh_CN
SET Text = '+34% [ICON_STRENGTH]战斗力时[COLOR_POSITIVE_TEXT]拦截[ENDCOLOR]敌方空军单位。[NEWLINE]+1 作战范围。[NEWLINE]+1 [COLOR_POSITIVE_TEXT]拦截[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SORTIE_HELP';

-- Dogfighting
UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH] Combat Strength when performing an [COLOR_POSITIVE_TEXT]Air Sweep[ENDCOLOR]. Deal 5 Damage to all [COLOR_POSITIVE_TEXT]Air Units[ENDCOLOR] on or adjacent to the target tile if this Air Sweep is [COLOR_POSITIVE_TEXT]not Intercepted[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP';

UPDATE Language_zh_CN
SET Text = '+33% [ICON_STRENGTH]执行某项任务时的战斗力[COLOR_POSITIVE_TEXT]风扫[ENDCOLOR]。对所有人造成 5 点伤害[COLOR_POSITIVE_TEXT]空气单位[ENDCOLOR]如果此空气清扫是在目标图块上或附近[COLOR_POSITIVE_TEXT]未被拦截[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP';

UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH] Combat Strength when performing an [COLOR_POSITIVE_TEXT]Air Sweep[ENDCOLOR]. Deal 10 Damage to all [COLOR_POSITIVE_TEXT]Air Units[ENDCOLOR] on or adjacent to the target tile if this Air Sweep is [COLOR_POSITIVE_TEXT]not Intercepted[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP';

UPDATE Language_zh_CN
SET Text = '+33% [ICON_STRENGTH]执行某项任务时的战斗力[COLOR_POSITIVE_TEXT]风扫[ENDCOLOR]。对所有人造成 10 点伤害[COLOR_POSITIVE_TEXT]空气单位[ENDCOLOR]如果此空气清扫是在目标图块上或附近[COLOR_POSITIVE_TEXT]未被拦截[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP';

UPDATE Language_en_US
SET Text = '+34% [ICON_STRENGTH] Combat Strength when performing an [COLOR_POSITIVE_TEXT]Air Sweep[ENDCOLOR]. Deal 15 Damage to all [COLOR_POSITIVE_TEXT]Air Units[ENDCOLOR] on or adjacent to the target tile if this Air Sweep is [COLOR_POSITIVE_TEXT]not Intercepted[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP';

UPDATE Language_zh_CN
SET Text = '+34% [ICON_STRENGTH]执行某项任务时的战斗力[COLOR_POSITIVE_TEXT]风扫[ENDCOLOR]。对所有人造成 15 点伤害[COLOR_POSITIVE_TEXT]空气单位[ENDCOLOR]如果此空气清扫是在目标图块上或附近[COLOR_POSITIVE_TEXT]未被拦截[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP';

-- Siege (Air)
UPDATE Language_en_US
SET Text = '+50% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP';

UPDATE Language_zh_CN
SET Text = '+50% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP';

UPDATE Language_en_US
SET Text = '+50% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP';

UPDATE Language_zh_CN
SET Text = '+50% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP';

UPDATE Language_en_US
SET Text = '+50% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP';

UPDATE Language_zh_CN
SET Text = '+50% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP';

-- Bombardment
UPDATE Language_en_US
SET Text = '+10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.[NEWLINE]+30% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。[NEWLINE]+30% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.[NEWLINE]+30% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。[NEWLINE]+30% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.[NEWLINE]+30% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。[NEWLINE]+30% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP';

UPDATE Language_en_US
SET Text = 'Air Targeting I'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_1';

UPDATE Language_zh_CN
SET Text = '空中瞄准 I'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_1';

UPDATE Language_en_US
SET Text = 'Air Targeting II'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_2';

UPDATE Language_zh_CN
SET Text = '空中瞄准 II'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_2';

UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP';

UPDATE Language_zh_CN
SET Text = '+15% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]海军[ENDCOLOR]和[COLOR_POSITIVE_TEXT]土地单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP';

-- Air Ambush I, Air Ambush II
UPDATE Language_en_US
SET Text = '+50% [ICON_STRENGTH] Combat Strength VS [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP';

UPDATE Language_zh_CN
SET Text = '+50% [ICON_STRENGTH]战斗力VS[COLOR_POSITIVE_TEXT]装甲部队[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP';

UPDATE Language_en_US
SET Text = 'Evasion'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION';

UPDATE Language_zh_CN
SET Text = '闪避'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION';

UPDATE Language_en_US
SET Text = '-50% Damage received when performing an [COLOR_POSITIVE_TEXT]Air Strike[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_HELP';

UPDATE Language_zh_CN
SET Text = '-50% 执行某项任务时受到的伤害[COLOR_POSITIVE_TEXT]空袭[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_HELP';

-- Scouting
UPDATE Language_en_US
SET Text = '+1 [ICON_VISION] Sight and Embarked Sight.'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_1_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_VISION]视线和登船视线。'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_1_HELP';

UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES] Movement and Embarked Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_2_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_MOVES]运动和开始运动。'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_2_HELP';

-- Survivalism
UPDATE Language_en_US
SET Text = '+25% [ICON_STRENGTH] Combat Strength when defending.[NEWLINE]+5 HP when Healing [COLOR_POSITIVE_TEXT]Outside of Friendly Territory[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_1_HELP';

UPDATE Language_zh_CN
SET Text = '+25% [ICON_STRENGTH]防御时的战斗力。[NEWLINE]治疗时 HP +5[COLOR_POSITIVE_TEXT]友好领土之外[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_1_HELP';

UPDATE Language_en_US
SET Text = '+25% [ICON_STRENGTH] Combat Strength when defending.[NEWLINE]+5 HP when Healing [COLOR_POSITIVE_TEXT]Outside of Friendly Territory[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_2_HELP';

UPDATE Language_zh_CN
SET Text = '+25% [ICON_STRENGTH]防御时的战斗力。[NEWLINE]治疗时 HP +5[COLOR_POSITIVE_TEXT]友好领土之外[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_2_HELP';

UPDATE Language_en_US
SET Text = 'Unit will [COLOR_POSITIVE_TEXT]Heal Every Turn[ENDCOLOR], even if it performs an action.[NEWLINE][ICON_RAZING] Pillaging costs no [ICON_MOVES] Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_3_HELP';

UPDATE Language_zh_CN
SET Text = '单位将[COLOR_POSITIVE_TEXT]每回合治愈[ENDCOLOR]，即使它执行了一个动作。[NEWLINE][ICON_RAZING]掠夺成本 无[ICON_MOVES]移动。'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_3_HELP';

UPDATE Language_en_US
SET Text = 'Tank Hunter I'
WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_1';

UPDATE Language_zh_CN
SET Text = '坦克猎人 I'
WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_1';

UPDATE Language_en_US
SET Text = 'Tank Hunter II'
WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_2';

UPDATE Language_zh_CN
SET Text = '坦克猎人II'
WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_2';

UPDATE Language_en_US
SET Text = 'Hull I'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_1';

UPDATE Language_zh_CN
SET Text = '船体一号'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_1';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+10 Hit Points.'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+10 生命值。'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP';

UPDATE Language_en_US
SET Text = 'Hull II'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_2';

UPDATE Language_zh_CN
SET Text = '船体二号'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_2';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+15 Hit Points.'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+15 生命值。'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP';

UPDATE Language_en_US
SET Text = 'Hull III'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_3';

UPDATE Language_zh_CN
SET Text = '船体三号'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_3';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+15 Hit Points.'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+15 生命值。'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP';

-- Boarding Party
UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH] Combat Strength.[NEWLINE]Inflict the [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_BOARDED_1}[ENDCOLOR] status on Enemy Naval Units when attacking or melee defending, reducing their [ICON_MOVES] Movement by 2 for 1 Turn.'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP';

UPDATE Language_zh_CN
SET Text = '+15% [ICON_STRENGTH]战斗力。[NEWLINE]造成[COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_BOARDED_1}[ENDCOLOR]敌方海军部队在攻击或近战防御时的状态，降低其[ICON_MOVES]1 回合移动 2 点。'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP';

UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH] Combat Strength.[NEWLINE]Immune to the [COLOR_POSITIVE_TEXT]Boarded[ENDCOLOR] status.'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP';

UPDATE Language_zh_CN
SET Text = '+15% [ICON_STRENGTH]战斗力。[NEWLINE]免疫[COLOR_POSITIVE_TEXT]登机[ENDCOLOR]地位。'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP';

UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH] Combat Strength.[NEWLINE]Inflict the [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_BOARDED_2}[ENDCOLOR] status on Enemy Naval Units when attacking or melee defending, reducing their [ICON_MOVES] Movement by 4 for 1 Turn.'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP';

UPDATE Language_zh_CN
SET Text = '+15% [ICON_STRENGTH]战斗力。[NEWLINE]造成[COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_BOARDED_2}[ENDCOLOR]敌方海军部队在攻击或近战防御时的状态，降低其[ICON_MOVES]1 回合移动 4 点。'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP';

UPDATE Language_en_US
SET Text = 'Torpedo I'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_1';

UPDATE Language_zh_CN
SET Text = '鱼雷一号'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_1';

UPDATE Language_en_US
SET Text = '+30% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_1_HELP';

UPDATE Language_zh_CN
SET Text = '+30% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]海军[ENDCOLOR]和[COLOR_POSITIVE_TEXT]土地单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_1_HELP';

UPDATE Language_en_US
SET Text = 'Torpedo II'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_2';

UPDATE Language_zh_CN
SET Text = '鱼雷II'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_2';

UPDATE Language_en_US
SET Text = '+30% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_2_HELP';

UPDATE Language_zh_CN
SET Text = '+30% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]海军[ENDCOLOR]和[COLOR_POSITIVE_TEXT]土地单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_2_HELP';

UPDATE Language_en_US
SET Text = 'Torpedo III'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_3';

UPDATE Language_zh_CN
SET Text = '鱼雷III'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_3';

UPDATE Language_en_US
SET Text = '+30% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_3_HELP';

UPDATE Language_zh_CN
SET Text = '+30% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]海军[ENDCOLOR]和[COLOR_POSITIVE_TEXT]土地单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_3_HELP';

-- Flight Deck
UPDATE Language_en_US
SET Text = '+1 Cargo Slot.'
WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_1_HELP';

UPDATE Language_zh_CN
SET Text = '+1 货位。'
WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_1_HELP';

UPDATE Language_en_US
SET Text = '+1 Cargo Slot.'
WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_2_HELP';

UPDATE Language_zh_CN
SET Text = '+1 货位。'
WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_2_HELP';

UPDATE Language_en_US
SET Text = '+1 Cargo Slot.'
WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_3_HELP';

UPDATE Language_zh_CN
SET Text = '+1 货位。'
WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_3_HELP';

-- Armor Plating
UPDATE Language_en_US
SET Text = '+25% [ICON_STRENGTH] Combat Strength when defending.'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_1_HELP';

UPDATE Language_zh_CN
SET Text = '+25% [ICON_STRENGTH]防御时的战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_1_HELP';

UPDATE Language_en_US
SET Text = '+25% [ICON_STRENGTH] Combat Strength when defending.'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_2_HELP';

UPDATE Language_zh_CN
SET Text = '+25% [ICON_STRENGTH]防御时的战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_2_HELP';

UPDATE Language_en_US
SET Text = '+25% [ICON_STRENGTH] Combat Strength when defending.'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_3_HELP';

UPDATE Language_zh_CN
SET Text = '+25% [ICON_STRENGTH]防御时的战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_3_HELP';

UPDATE Language_en_US
SET Text = 'Air Penetration I'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_I';

UPDATE Language_zh_CN
SET Text = '空气渗透Ⅰ'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_I';

UPDATE Language_en_US
SET Text = 'Air Penetration II'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_II';

UPDATE Language_zh_CN
SET Text = '空气渗透 II'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_II';

UPDATE Language_en_US
SET Text = 'Interceptor I'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_I';

UPDATE Language_zh_CN
SET Text = '拦截机一号'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_I';

UPDATE Language_en_US
SET Text = 'Interceptor II'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_II';

UPDATE Language_zh_CN
SET Text = '拦截机II'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_II';

UPDATE Language_en_US
SET Text = 'Interceptor III'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_III';

UPDATE Language_zh_CN
SET Text = '拦截机III'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_III';

UPDATE Language_en_US
SET Text = 'Interceptor IV'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_IV';

UPDATE Language_zh_CN
SET Text = '拦截机IV'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_IV';

UPDATE Language_en_US
SET Text = 'Air Supremacy I'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR';

UPDATE Language_zh_CN
SET Text = '制空权 I'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR';

UPDATE Language_en_US
SET Text = 'Air Supremacy II'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR_II';

UPDATE Language_zh_CN
SET Text = '制空权II'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR_II';

UPDATE Language_en_US
SET Text = 'Eagle Hunter'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_FIGHTER';

UPDATE Language_zh_CN
SET Text = '猎鹰者'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_FIGHTER';

-- Buffalo Chest
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+25 Hit Points.'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_CHEST_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+25 生命值。'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_CHEST_HELP';

-- Buffalo Horns
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+25% [COLOR_POSITIVE_TEXT]Flanking bonus[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_HORNS_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+25% [COLOR_POSITIVE_TEXT]侧翼奖金[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_HORNS_HELP';

-- Buffalo Loins
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+1 [ICON_MOVES] Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_LOINS_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+1 [ICON_MOVES]移动。'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_LOINS_HELP';

-- Embarkation with Ocean Movement
UPDATE Language_en_US
SET Text = 'Can embark onto [COLOR_POSITIVE_TEXT]Water Tiles[ENDCOLOR] and enter [COLOR_POSITIVE_TEXT]Ocean[ENDCOLOR].[NEWLINE]+2 [ICON_VISION] Embarked Sight.'
WHERE Tag = 'TXT_KEY_PROMOTION_ALLWATER_EMBARKATION_HELP';

UPDATE Language_zh_CN
SET Text = '可以踏上[COLOR_POSITIVE_TEXT]水砖[ENDCOLOR]并输入[COLOR_POSITIVE_TEXT]海洋[ENDCOLOR].[NEWLINE]+2 [ICON_VISION]登船视线。'
WHERE Tag = 'TXT_KEY_PROMOTION_ALLWATER_EMBARKATION_HELP';

UPDATE Language_en_US
SET Text = 'Colonization'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_MOVEMENT';

UPDATE Language_zh_CN
SET Text = '殖民化'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_MOVEMENT';

UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES] Embarked Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_MOVEMENT_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_MOVES]开始运动。'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_MOVEMENT_HELP';

-- Exploration
UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES] Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_MOVES]移动。'
WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP';

-- Patriotic War
UPDATE Language_en_US
SET Text = '+20% [ICON_STRENGTH] Combat Strength in or adjacent to a [COLOR_POSITIVE_TEXT]City[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_NATIONALISM_HELP';

UPDATE Language_zh_CN
SET Text = '+20% [ICON_STRENGTH]位于或邻近的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_NATIONALISM_HELP';

-- Altitude Training
UPDATE Language_en_US
SET Text = 'Double [ICON_MOVES] Movement in [COLOR_POSITIVE_TEXT]Hill[ENDCOLOR].[NEWLINE]+10% [ICON_STRENGTH] Combat Strength when fighting in [COLOR_POSITIVE_TEXT]Hill[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_ALTITUDE_TRAINING_HELP';

UPDATE Language_zh_CN
SET Text = '双倍的[ICON_MOVES]运动于[COLOR_POSITIVE_TEXT]爬坡道[ENDCOLOR].[NEWLINE]+10% [ICON_STRENGTH]战斗时的战斗力[COLOR_POSITIVE_TEXT]爬坡道[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_ALTITUDE_TRAINING_HELP';

-- Morale 
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.'
WHERE Tag = 'TXT_KEY_PROMOTION_MORALE_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_MORALE_HELP';

-- Statue Of Zeus
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Military Units:[ENDCOLOR] +25% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].[NEWLINE][COLOR_POSITIVE_TEXT]Workers:[ENDCOLOR] Immune to the [COLOR_NEGATIVE_TEXT]{TXT_KEY_PROMOTION_PRISONERS_OF_WAR}[ENDCOLOR] status.'
WHERE Tag = 'TXT_KEY_PROMOTION_STATUE_ZEUS_HELP';

UPDATE Language_zh_CN
SET Text = '[COLOR_POSITIVE_TEXT]军事单位：[ENDCOLOR] +25% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].[NEWLINE][COLOR_POSITIVE_TEXT]工人：[ENDCOLOR]免疫[COLOR_NEGATIVE_TEXT]{TXT_KEY_PROMOTION_PRISONERS_OF_WAR}[ENDCOLOR]地位。'
WHERE Tag = 'TXT_KEY_PROMOTION_STATUE_ZEUS_HELP';

-- Himeji Castle
UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]Inside Friendly Territory[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP';

UPDATE Language_zh_CN
SET Text = '+15% [ICON_STRENGTH]战斗力[COLOR_POSITIVE_TEXT]友好领土内[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP';

UPDATE Language_en_US
SET Text = 'Anti-Tank Rounds'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_TANK';

UPDATE Language_zh_CN
SET Text = '反坦克弹'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_TANK';

UPDATE Language_en_US
SET Text = 'City Attack Penalty'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_PENALTY';

UPDATE Language_zh_CN
SET Text = '攻城惩罚'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_PENALTY';

UPDATE Language_en_US
SET Text = '-33% [ICON_STRENGTH] Combat Strength when attacking [COLOR_NEGATIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_PENALTY_HELP';

UPDATE Language_zh_CN
SET Text = '-33% [ICON_STRENGTH]攻击时的战斗力[COLOR_NEGATIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_PENALTY_HELP';

-- Hovering Unit
UPDATE Language_en_US
SET Text = 'Can enter [COLOR_POSITIVE_TEXT]Impassable[ENDCOLOR] tiles, and can enter Water tiles without embarking.[NEWLINE]Cannot attack in [COLOR_NEGATIVE_TEXT]Ocean[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_HOVERING_UNIT_HELP';

UPDATE Language_zh_CN
SET Text = '可以进入[COLOR_POSITIVE_TEXT]不可逾越[ENDCOLOR]瓷砖，并且无需登船即可进入水瓷砖。[NEWLINE]无法攻击[COLOR_NEGATIVE_TEXT]海洋[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_HOVERING_UNIT_HELP';

UPDATE Language_en_US
SET Text = 'All tiles cost 1 [ICON_MOVES] Movement.[NEWLINE][COLOR_NEGATIVE_TEXT]Cannot use Roads and Railroads.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST';

UPDATE Language_zh_CN
SET Text = '所有瓷砖成本 1[ICON_MOVES]移动。[NEWLINE][COLOR_NEGATIVE_TEXT]不能使用公路和铁路。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST';

UPDATE Language_en_US
SET Text = 'Siege Engine'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE';

UPDATE Language_zh_CN
SET Text = '攻城车'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE';

UPDATE Language_en_US
SET Text = '+100% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE_HELP';

UPDATE Language_zh_CN
SET Text = '+100% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE_HELP';

-- Indirect Fire
UPDATE Language_en_US
SET Text = 'Can perform Ranged Attacks over obstacles.[NEWLINE]-10% [ICON_RANGE_STRENGTH] Ranged Combat Strength when attacking.'
WHERE Tag = 'TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP';

UPDATE Language_zh_CN
SET Text = '可以越过障碍物进行远程攻击。[NEWLINE]-10% [ICON_RANGE_STRENGTH]攻击时的远程战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP';

-- Extra Sight While Embarked
UPDATE Language_en_US
SET Text = '+1 [ICON_VISION] Embarked Sight.'
WHERE Tag = 'TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_VISION]登船视线。'
WHERE Tag = 'TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP';

-- Embarkation with Defense
UPDATE Language_en_US
SET Text = '+100% [ICON_STRENGTH] Combat Strength when defending while Embarked.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]Lost on Upgrade.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP';

UPDATE Language_zh_CN
SET Text = '+100% [ICON_STRENGTH]出发时防御时的战斗力。[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升级时丢失。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP';

-- Skyranger
UPDATE Language_en_US
SET Text = 'Can [COLOR_POSITIVE_TEXT]Paradrop[ENDCOLOR] up to 40 tiles away while [COLOR_POSITIVE_TEXT]Inside Friendly Territory[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_EXTENDED_PARADROP_HELP';

UPDATE Language_zh_CN
SET Text = '能[COLOR_POSITIVE_TEXT]帕拉德罗普[ENDCOLOR]最多 40 格之外[COLOR_POSITIVE_TEXT]友好领土内[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_EXTENDED_PARADROP_HELP';

UPDATE Language_en_US
SET Text = 'Oceanic Peril'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE';

UPDATE Language_zh_CN
SET Text = '海洋危机'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE';

UPDATE Language_en_US
SET Text = 'Depth Charges I'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_I';

UPDATE Language_zh_CN
SET Text = '深水炸弹 I'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_I';

UPDATE Language_en_US
SET Text = 'Depth Charges II'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_II';

UPDATE Language_zh_CN
SET Text = '深水炸弹 II'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_II';

UPDATE Language_en_US
SET Text = 'Silent Hunter'
WHERE Tag = 'TXT_KEY_PROMOTION_SILENT_HUNTER';

UPDATE Language_zh_CN
SET Text = '沉默的猎手'
WHERE Tag = 'TXT_KEY_PROMOTION_SILENT_HUNTER';

-- Air Sweep
UPDATE Language_en_US
SET Text = 'Can perform [COLOR_POSITIVE_TEXT]Air Sweep[ENDCOLOR] to clear Interception near the target tile.'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SWEEP_HELP';

UPDATE Language_zh_CN
SET Text = '可以执行[COLOR_POSITIVE_TEXT]风扫[ENDCOLOR]清除目标方块附近的拦截。'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SWEEP_HELP';

UPDATE Language_en_US
SET Text = 'Bonus vs Helicopters (150)'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER';

UPDATE Language_zh_CN
SET Text = '奖金 vs 直升机 (150)'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER';

UPDATE Language_en_US
SET Text = 'Domestic Focus'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO';

UPDATE Language_zh_CN
SET Text = '国内聚焦'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO';

UPDATE Language_en_US
SET Text = 'Cannot end turn in [COLOR_NEGATIVE_TEXT]Ocean[ENDCOLOR] until you have researched [COLOR_CYAN]{TXT_KEY_TECH_COMPASS_TITLE}[ENDCOLOR].[NEWLINE]Can move through visible Ocean if destination is visible Coast.'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP';

UPDATE Language_zh_CN
SET Text = '无法结束上交[COLOR_NEGATIVE_TEXT]海洋[ENDCOLOR]直到你研究完毕[COLOR_CYAN]{TXT_KEY_TECH_COMPASS_TITLE}[ENDCOLOR].[NEWLINE]如果目的地是可见海岸，则可以穿过可见海洋。'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP';

-- Unwelcome Evangelist
UPDATE Language_en_US
SET Text = 'Can enter rival territory without Open Borders but lose 25% of original Religious Strength if ending a turn in it. Unit is [COLOR_NEGATIVE_TEXT]eliminated[ENDCOLOR] when Religious Strength reaches 0.'
WHERE Tag = 'TXT_KEY_PROMOTION_UNWELCOME_EVANGELIST_HELP';

UPDATE Language_zh_CN
SET Text = '可以在没有开放边界的情况下进入敌方领地，但如果结束一个回合，就会失去 25% 的原始宗教力量。单位是[COLOR_NEGATIVE_TEXT]消除了[ENDCOLOR]当宗教强度达到0时。'
WHERE Tag = 'TXT_KEY_PROMOTION_UNWELCOME_EVANGELIST_HELP';

-- Leadership
UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH] Combat Strength for Land Units within 2 tiles of this Unit.'
WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_GENERAL_HELP';

UPDATE Language_zh_CN
SET Text = '+15% [ICON_STRENGTH]该单位 2 格内陆地单位的战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_GENERAL_HELP';

-- Naval Leadership
UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH] Combat Strength for [COLOR_POSITIVE_TEXT]Naval Units[ENDCOLOR] within 2 tiles of this Unit.[NEWLINE]May use the [COLOR_POSITIVE_TEXT]{TXT_KEY_MISSION_REPAIR_FLEET}[ENDCOLOR] Ability, expending this Unit and fully healing all [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Embarked Units[ENDCOLOR] on or adjacent to this tile.'
WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP';

UPDATE Language_zh_CN
SET Text = '+15% [ICON_STRENGTH]战斗力为[COLOR_POSITIVE_TEXT]海军单位[ENDCOLOR]该单元的 2 格内。[NEWLINE]可以使用[COLOR_POSITIVE_TEXT]{TXT_KEY_MISSION_REPAIR_FLEET}[ENDCOLOR]能力，消耗该单位并完全治愈所有人[COLOR_POSITIVE_TEXT]海军[ENDCOLOR]和[COLOR_POSITIVE_TEXT]上船单位[ENDCOLOR]在该图块上或附近。'
WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP';

-- Withdraw Before Melee
UPDATE Language_en_US
SET Text = 'Withdraw from Melee Attack if there is an open tile behind this Unit, once per turn.'
WHERE Tag = 'TXT_KEY_PROMOTION_WITHDRAW_BEFORE_MELEE_HELP';

UPDATE Language_zh_CN
SET Text = '如果该单位后面有空位，则退出近战攻击，每回合一次。'
WHERE Tag = 'TXT_KEY_PROMOTION_WITHDRAW_BEFORE_MELEE_HELP';

UPDATE Language_en_US
SET Text = 'Unity'
WHERE Tag = 'TXT_KEY_PROMOTION_DISCIPLINE';

UPDATE Language_zh_CN
SET Text = '统一'
WHERE Tag = 'TXT_KEY_PROMOTION_DISCIPLINE';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH] Combat Strength.[NEWLINE]+15% [ICON_STRENGTH] Combat Strength per [COLOR_POSITIVE_TEXT]Adjacent Owned Land Unit[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DISCIPLINE_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [ICON_STRENGTH]战斗力。[NEWLINE]+15% [ICON_STRENGTH]战斗力每[COLOR_POSITIVE_TEXT]相邻自有土地单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DISCIPLINE_HELP';

-- Bonus vs Mounted (50)
UPDATE Language_en_US
SET Text = '+50% [ICON_STRENGTH] Combat Strength VS [COLOR_POSITIVE_TEXT]Mounted Units[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]Lost on Upgrade.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP';

UPDATE Language_zh_CN
SET Text = '+50% [ICON_STRENGTH]战斗力VS[COLOR_POSITIVE_TEXT]安装单位[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升级时丢失。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP';

UPDATE Language_en_US
SET Text = 'Skeleton Key'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT';

UPDATE Language_zh_CN
SET Text = '万能钥匙'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT';

UPDATE Language_en_US
SET Text = '+150% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]Lost on Upgrade.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT_HELP';

UPDATE Language_zh_CN
SET Text = '+150% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]城市[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升级时丢失。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT_HELP';

UPDATE Language_en_US
SET Text = 'Minor City Attack Penalty'
WHERE Tag = 'TXT_KEY_SMALL_PROMOTION_CITY_PENALTY';

UPDATE Language_zh_CN
SET Text = '小型城市攻击惩罚'
WHERE Tag = 'TXT_KEY_SMALL_PROMOTION_CITY_PENALTY';

UPDATE Language_en_US
SET Text = '-25% [ICON_STRENGTH] Combat Strength when attacking [COLOR_NEGATIVE_TEXT]Cities[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]Lost on Upgrade.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_SMALL_PROMOTION_CITY_PENALTY_HELP';

UPDATE Language_zh_CN
SET Text = '-25% [ICON_STRENGTH]攻击时的战斗力[COLOR_NEGATIVE_TEXT]城市[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升级时丢失。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_SMALL_PROMOTION_CITY_PENALTY_HELP';

UPDATE Language_en_US
SET Text = 'Open Terrain Bonus (30)'
WHERE Tag = 'TXT_KEY_PROMOTION_OPEN_TERRAIN';

UPDATE Language_zh_CN
SET Text = '开放地形奖励 (30)'
WHERE Tag = 'TXT_KEY_PROMOTION_OPEN_TERRAIN';

-- Ranged Support Fire
UPDATE Language_en_US
SET Text = 'Perform a [COLOR_POSITIVE_TEXT]Ranged Attack[ENDCOLOR] at 50% [ICON_STRENGTH] Combat Strength before attacking [COLOR_POSITIVE_TEXT]Units[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]Lost on Upgrade.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_RANGED_SUPPORT_FIRE_HELP';

UPDATE Language_zh_CN
SET Text = '执行一个[COLOR_POSITIVE_TEXT]远程攻击[ENDCOLOR]50%[ICON_STRENGTH]攻击前的战斗力[COLOR_POSITIVE_TEXT]单位[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升级时丢失。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_RANGED_SUPPORT_FIRE_HELP';

UPDATE Language_en_US
SET Text = 'Tenacity'
WHERE Tag = 'TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';

UPDATE Language_zh_CN
SET Text = '韧性'
WHERE Tag = 'TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';

-- Combat Bonus in Forest/Jungle (33)
UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH] Combat Strength when defending in or attacking a Unit in [COLOR_POSITIVE_TEXT]Forest[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Jungle[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_MOHAWK_HELP';

UPDATE Language_zh_CN
SET Text = '+33% [ICON_STRENGTH]防御或攻击单位时的战斗力[COLOR_POSITIVE_TEXT]森林[ENDCOLOR]和[COLOR_POSITIVE_TEXT]丛林[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_MOHAWK_HELP';

-- War Canoes
UPDATE Language_en_US
SET Text = 'Double [ICON_MOVES] Movement when moving along Rivers.'
WHERE Tag = 'TXT_KEY_PROMOTION_WAR_CANOES_HELP';

UPDATE Language_zh_CN
SET Text = '双倍的[ICON_MOVES]沿着河流移动时的移动。'
WHERE Tag = 'TXT_KEY_PROMOTION_WAR_CANOES_HELP';

UPDATE Language_en_US
SET Text = 'Expeditionary Warfare'
WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS';

UPDATE Language_zh_CN
SET Text = '远征战'
WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS';

UPDATE Language_en_US
SET Text = '+20% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]Outside of Friendly Territory[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS_HELP';

UPDATE Language_zh_CN
SET Text = '+20% [ICON_STRENGTH]战斗力[COLOR_POSITIVE_TEXT]友好领土之外[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS_HELP';

UPDATE Language_en_US
SET Text = 'Faster Healing'
WHERE Tag = 'TXT_KEY_PROMOTION_FASTER_HEAL';

UPDATE Language_zh_CN
SET Text = '愈合更快'
WHERE Tag = 'TXT_KEY_PROMOTION_FASTER_HEAL';

UPDATE Language_en_US
SET Text = 'Marksmanship'
WHERE Tag = 'TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED';

UPDATE Language_zh_CN
SET Text = '枪法'
WHERE Tag = 'TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED';

UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH] Combat Strength when attacking [COLOR_POSITIVE_TEXT]Wounded Units[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP';

UPDATE Language_zh_CN
SET Text = '+33% [ICON_STRENGTH]攻击时的战斗力[COLOR_POSITIVE_TEXT]受伤单位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP';

UPDATE Language_en_US
SET Text = 'Highlander'
WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY';

UPDATE Language_zh_CN
SET Text = '汉兰达'
WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY';

UPDATE Language_en_US
SET Text = 'Double [ICON_MOVES] Movement in [COLOR_POSITIVE_TEXT]Snow[ENDCOLOR], [COLOR_POSITIVE_TEXT]Tundra[ENDCOLOR], and [COLOR_POSITIVE_TEXT]Hill[ENDCOLOR].[NEWLINE]+25% [ICON_STRENGTH] Combat Strength when fighting in [COLOR_POSITIVE_TEXT]Snow[ENDCOLOR], [COLOR_POSITIVE_TEXT]Tundra[ENDCOLOR], and [COLOR_POSITIVE_TEXT]Hill[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY_HELP';

UPDATE Language_zh_CN
SET Text = '双倍的[ICON_MOVES]运动于[COLOR_POSITIVE_TEXT]雪[ENDCOLOR], [COLOR_POSITIVE_TEXT]苔原[ENDCOLOR]， 和[COLOR_POSITIVE_TEXT]爬坡道[ENDCOLOR].[NEWLINE]+25% [ICON_STRENGTH]战斗时的战斗力[COLOR_POSITIVE_TEXT]雪[ENDCOLOR], [COLOR_POSITIVE_TEXT]苔原[ENDCOLOR]， 和[COLOR_POSITIVE_TEXT]爬坡道[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY_HELP';

-- Haka War Dance
UPDATE Language_en_US
SET Text = '-20% [ICON_STRENGTH] Combat Strength for [COLOR_POSITIVE_TEXT]Adjacent Enemy Units[ENDCOLOR].[NEWLINE]Embarking and Disembarking cost only 1 [ICON_MOVES] Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_HAKA_WAR_DANCE_HELP';

UPDATE Language_zh_CN
SET Text = '-20% [ICON_STRENGTH]战斗力为[COLOR_POSITIVE_TEXT]相邻敌方单位[ENDCOLOR].[NEWLINE]上船和下船仅需 1[ICON_MOVES]移动。'
WHERE Tag = 'TXT_KEY_PROMOTION_HAKA_WAR_DANCE_HELP';

UPDATE Language_en_US
SET Text = 'Khaaaan!'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_GENERAL';

UPDATE Language_zh_CN
SET Text = '哈安！'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_GENERAL';

UPDATE Language_en_US
SET Text = 'Deal 10 Damage to Enemy Units ending their turn adjacent to this Unit.[NEWLINE]This Damage ignores damage reduction.'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP';

UPDATE Language_zh_CN
SET Text = '对在该单位附近结束回合的敌方单位造成 10 点伤害。[NEWLINE]该伤害忽略伤害减免。'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP';

-- Quick Study
UPDATE Language_en_US
SET Text = '+50% Experience gained from combat.'
WHERE Tag = 'TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP';

UPDATE Language_zh_CN
SET Text = '+50% 从战斗中获得的经验。'
WHERE Tag = 'TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP';

-- Trade Mission Bonus
UPDATE Language_en_US
SET Text = '+100% [ICON_GOLD] Gold from performing a [COLOR_POSITIVE_TEXT]Trade Mission[ENDCOLOR].[NEWLINE]+2 [ICON_MOVES] Embarked Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_TRADE_MISSION_BONUS_HELP';

UPDATE Language_zh_CN
SET Text = '+100% [ICON_GOLD]黄金来自表演[COLOR_POSITIVE_TEXT]贸易代表团[ENDCOLOR].[NEWLINE]+2 [ICON_MOVES]开始运动。'
WHERE Tag = 'TXT_KEY_PROMOTION_TRADE_MISSION_BONUS_HELP';

-- Heavy Charge
UPDATE Language_en_US
SET Text = '+50% [ICON_STRENGTH] Combat Strength when attacking if the target cannot retreat. The target is forced to retreat (if possible) if it has lower [ICON_STRENGTH] Combat Strength than this Unit after all modifiers.'
WHERE Tag = 'TXT_KEY_PROMOTION_HEAVY_CHARGE_HELP';

UPDATE Language_zh_CN
SET Text = '+50% [ICON_STRENGTH]如果目标无法撤退，则攻击时的战斗力。如果目标的防御力较低，则目标被迫撤退（如果可能）[ICON_STRENGTH]经过所有修正后，战斗力高于该单位。'
WHERE Tag = 'TXT_KEY_PROMOTION_HEAVY_CHARGE_HELP';

-- Sapper
UPDATE Language_en_US
SET Text = 'When adjacent to an Enemy City, Owned Units within 2 tiles gain +40% [ICON_STRENGTH] Combat Strength when attacking the City.[NEWLINE]If 2 tiles from an Enemy City, Owned Units within 2 tiles gain +20% [ICON_STRENGTH] Combat Strength when attacking the City.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]These bonuses do not stack.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SAPPER_HELP';

UPDATE Language_zh_CN
SET Text = '当邻近敌方城市时，2 格内的己方单位增益 +40%[ICON_STRENGTH]攻城时的战斗力。[NEWLINE]如果敌方城市有 2 格，则 2 格内的己方单位增益 +20%[ICON_STRENGTH]攻城时的战斗力。[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]这些奖金不能叠加。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SAPPER_HELP';

-- Golden Age from Victories
UPDATE Language_en_US
SET Text = 'Gain 100% of the [ICON_STRENGTH] Combat Strength of defeated Enemy Units as [ICON_GOLDEN_AGE] Golden Age Points.'
WHERE Tag = 'TXT_KEY_PROMOTION_GOLDEN_AGE_POINTS_HELP';

UPDATE Language_zh_CN
SET Text = '获得 100% 的[ICON_STRENGTH]被击败的敌方单位的战斗力为[ICON_GOLDEN_AGE]黄金时代积分。'
WHERE Tag = 'TXT_KEY_PROMOTION_GOLDEN_AGE_POINTS_HELP';

-- Homeland Guardian
UPDATE Language_en_US
SET Text = '+25% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]Inside Friendly Territory[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_HOMELAND_GUARDIAN_HELP';

UPDATE Language_zh_CN
SET Text = '+25% [ICON_STRENGTH]战斗力[COLOR_POSITIVE_TEXT]友好领土内[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_HOMELAND_GUARDIAN_HELP';

-- Full Moon Striker
UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES] Movement.[NEWLINE]Gain 200 [ICON_RESEARCH] Science when [ICON_RAZING] Pillaging Improvements.'
WHERE Tag = 'TXT_KEY_PROMOTION_MOON_STRIKER_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_MOVES]移动。[NEWLINE]增益200[ICON_RESEARCH]科学当[ICON_RAZING]掠夺改进。'
WHERE Tag = 'TXT_KEY_PROMOTION_MOON_STRIKER_HELP';

-- Mystic Blade
UPDATE Language_en_US
SET Text = 'Randomly gain one of the below promotions after first combat:[NEWLINE][COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_INVULNERABIILITY}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_SNEAK_ATTACK}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_ENEMY_BLADE}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_AMBITION}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_EVIL_SPIRITS}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_RESTLESSNESS}[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_MYSTIC_BLADE_HELP';

UPDATE Language_zh_CN
SET Text = '第一次战斗后随机获得以下促销之一：[NEWLINE][COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_INVULNERABIILITY}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_SNEAK_ATTACK}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_ENEMY_BLADE}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_AMBITION}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_EVIL_SPIRITS}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_RESTLESSNESS}[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_MYSTIC_BLADE_HELP';

-- Lightning Warfare
UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH] Combat Strength when attacking.[NEWLINE]+1 [ICON_MOVES] Movement.[NEWLINE]Ignore [COLOR_POSITIVE_TEXT]Zone of Control[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_LIGHTNING_WARFARE_HELP';

UPDATE Language_zh_CN
SET Text = '+15% [ICON_STRENGTH]攻击时的战斗力。[NEWLINE]+1 [ICON_MOVES]移动。[NEWLINE]忽略[COLOR_POSITIVE_TEXT]控制区[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_LIGHTNING_WARFARE_HELP';

-- Exotic Cargo
UPDATE Language_en_US
SET Text = 'Can {TXT_KEY_MISSION_SELL_EXOTIC_GOODS} when adjacent to foreign territory to gain [ICON_GOLD] Gold and XP based on the distance from your [ICON_CAPITAL] Capital up to two times.[NEWLINE]If sold to a City-State as the Portuguese, a Feitoria is [COLOR_POSITIVE_TEXT]automatically created[ENDCOLOR] in its territory.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]Lost on Upgrade.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SELL_EXOTIC_GOODS_HELP';

UPDATE Language_zh_CN
SET Text = '能{TXT_KEY_MISSION_SELL_EXOTIC_GOODS}当邻近外国领土时获得[ICON_GOLD]黄金和经验值取决于距您的距离[ICON_CAPITAL]资本最多两倍。[NEWLINE]如果像葡萄牙人一样卖给城邦，费托利亚是[COLOR_POSITIVE_TEXT]自动创建[ENDCOLOR]在其领土内。[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升级时丢失。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SELL_EXOTIC_GOODS_HELP';

-- City Plunder
UPDATE Language_en_US
SET Text = 'Steal [ICON_GOLD] Gold equal to 100% of Damage inflicted when attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR], capped at 10x [ICON_STRENGTH] City Strength.'
WHERE Tag = 'TXT_KEY_PROMOTION_DOUBLE_PLUNDER_HELP';

UPDATE Language_zh_CN
SET Text = '偷[ICON_GOLD]金币等于攻击时造成伤害的 100%[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]，上限为 10 倍[ICON_STRENGTH]城市实力。'
WHERE Tag = 'TXT_KEY_PROMOTION_DOUBLE_PLUNDER_HELP';

-- Feared Elephant
UPDATE Language_en_US
SET Text = '-10% [ICON_STRENGTH] Combat Strength on [COLOR_POSITIVE_TEXT]Adjacent Enemy Units[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]Lost on Upgrade.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP';

UPDATE Language_zh_CN
SET Text = '-10% [ICON_STRENGTH]战斗力开启[COLOR_POSITIVE_TEXT]相邻敌方单位[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升级时丢失。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP';

-- Enhanced Flank Attack
UPDATE Language_en_US
SET Text = '+10% [COLOR_POSITIVE_TEXT]Flanking bonus[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP';

UPDATE Language_zh_CN
SET Text = '+10% [COLOR_POSITIVE_TEXT]侧翼奖金[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP';

-- Near Capital Bonus
UPDATE Language_en_US
SET Text = '+30% [ICON_STRENGTH] Combat Strength in your [ICON_CAPITAL] Capital; bonus falls off by 1% per tile away from your [ICON_CAPITAL] Capital, up to 29 tiles away.'
WHERE Tag = 'TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP';

UPDATE Language_zh_CN
SET Text = '+30% [ICON_STRENGTH]你的战斗力[ICON_CAPITAL]首都;距离你的每格奖励下降 1%[ICON_CAPITAL]首都，距离最远 29 格。'
WHERE Tag = 'TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP';

-- Great General Combat Bonus
UPDATE Language_en_US
SET Text = '+25% [ICON_STRENGTH] Combat Strength when a Great General is on this tile.'
WHERE Tag = 'TXT_KEY_PROMOTION_GENERAL_STACKING_HELP';

UPDATE Language_zh_CN
SET Text = '+25% [ICON_STRENGTH]当大将军位于此板块时的战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_GENERAL_STACKING_HELP';

-- City Attack Only
UPDATE Language_en_US
SET Text = 'Cannot attack [COLOR_NEGATIVE_TEXT]Units[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Lost on Upgrade.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ONLY_ATTACKS_CITIES_HELP';

UPDATE Language_zh_CN
SET Text = '无法攻击[COLOR_NEGATIVE_TEXT]单位[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]升级时丢失。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ONLY_ATTACKS_CITIES_HELP';

-- Prize Ships
UPDATE Language_en_US
SET Text = 'Enlist defeated Enemy Units surrounded in half or more of adjacent traversable tiles.[NEWLINE]Captured Units start with 25% of their max HP, 0 XP, and can immediately move (but not attack).'
WHERE Tag = 'TXT_KEY_PROMOTION_PRIZE_SHIPS_HELP';

UPDATE Language_zh_CN
SET Text = '征召被击败的敌方单位被一半或更多相邻可穿越瓷砖包围。[NEWLINE]被捕获的单位一开始的生命值为最大生命值的 25%，经验值为 0，并且可以立即移动（但不能攻击）。'
WHERE Tag = 'TXT_KEY_PROMOTION_PRIZE_SHIPS_HELP';

-- Invulnerability
UPDATE Language_en_US
SET Text = '-2 Damage from all sources.[NEWLINE]+20 HP when [COLOR_POSITIVE_TEXT]Healing[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_INVULNERABIILITY_HELP';

UPDATE Language_zh_CN
SET Text = '-2 所有来源的伤害。[NEWLINE]+20 HP 当[COLOR_POSITIVE_TEXT]康复[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_INVULNERABIILITY_HELP';

-- Sneak Attack
UPDATE Language_en_US
SET Text = '+20% [COLOR_POSITIVE_TEXT]Flanking bonus[ENDCOLOR].[NEWLINE]Ignore [COLOR_POSITIVE_TEXT]Terrain Costs[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Zone of Control[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SNEAK_ATTACK_HELP';

UPDATE Language_zh_CN
SET Text = '+20% [COLOR_POSITIVE_TEXT]侧翼奖金[ENDCOLOR].[NEWLINE]忽略[COLOR_POSITIVE_TEXT]地形成本[ENDCOLOR]和[COLOR_POSITIVE_TEXT]控制区[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SNEAK_ATTACK_HELP';

UPDATE Language_en_US
SET Text = 'Determination'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBITION';

UPDATE Language_zh_CN
SET Text = '决心'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBITION';

UPDATE Language_en_US
SET Text = '+30% [ICON_STRENGTH] Combat Strength when attacking.[NEWLINE]+5% [ICON_STRENGTH] Combat Strength when defending.'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBITION_HELP';

UPDATE Language_zh_CN
SET Text = '+30% [ICON_STRENGTH]攻击时的战斗力。[NEWLINE]+5% [ICON_STRENGTH]防御时的战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBITION_HELP';

UPDATE Language_en_US
SET Text = 'Ceaselessness'
WHERE Tag = 'TXT_KEY_PROMOTION_RESTLESSNESS';

UPDATE Language_zh_CN
SET Text = '不间断'
WHERE Tag = 'TXT_KEY_PROMOTION_RESTLESSNESS';

UPDATE Language_en_US
SET Text = '+1 [ICON_WAR] Attack.[NEWLINE]+1 [ICON_MOVES] Movement.'
WHERE Tag = 'TXT_KEY_PROMOTION_RESTLESSNESS_HELP';

UPDATE Language_zh_CN
SET Text = '+1 [ICON_WAR]攻击。[NEWLINE]+1 [ICON_MOVES]移动。'
WHERE Tag = 'TXT_KEY_PROMOTION_RESTLESSNESS_HELP';

-- Enemy Blade
UPDATE Language_en_US
SET Text = 'Heal 10 HP when starting turn [COLOR_POSITIVE_TEXT]Inside Enemy Territory[ENDCOLOR].[NEWLINE]Deal 10 Damage to Enemy Units ending their turn adjacent to this Unit.[NEWLINE]This Damage ignores damage reduction.'
WHERE Tag = 'TXT_KEY_PROMOTION_ENEMY_BLADE_HELP';

UPDATE Language_zh_CN
SET Text = '回合开始时恢复 10 HP[COLOR_POSITIVE_TEXT]进入敌方领土[ENDCOLOR].[NEWLINE]对在该单位附近结束回合的敌方单位造成 10 点伤害。[NEWLINE]该伤害忽略伤害减免。'
WHERE Tag = 'TXT_KEY_PROMOTION_ENEMY_BLADE_HELP';

UPDATE Language_en_US
SET Text = 'Ancestral Protection'
WHERE Tag = 'TXT_KEY_PROMOTION_EVIL_SPIRITS';

UPDATE Language_zh_CN
SET Text = '祖先保护'
WHERE Tag = 'TXT_KEY_PROMOTION_EVIL_SPIRITS';

UPDATE Language_en_US
SET Text = '+5% [ICON_STRENGTH] Combat Strength when attacking.[NEWLINE]+30% [ICON_STRENGTH] Combat Strength when defending.'
WHERE Tag = 'TXT_KEY_PROMOTION_EVIL_SPIRITS_HELP';

UPDATE Language_zh_CN
SET Text = '+5% [ICON_STRENGTH]攻击时的战斗力。[NEWLINE]+30% [ICON_STRENGTH]防御时的战斗力。'
WHERE Tag = 'TXT_KEY_PROMOTION_EVIL_SPIRITS_HELP';
