------------------------------------------------
-- Ranking popup
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Ranks players by the average [ICON_PRODUCTION] Production generated by all of their cities.'
WHERE Tag = 'TXT_KEY_PROGRESS_SCREEN_PRODUCTION_TT';

UPDATE Language_zh_CN
SET Text = '按平均水平对玩家进行排名[ICON_PRODUCTION]所有城市产生的产量。'
WHERE Tag = 'TXT_KEY_PROGRESS_SCREEN_PRODUCTION_TT';

------------------------------------------------
-- Advisors
------------------------------------------------
UPDATE Language_en_US
SET Text = 'I''m not sure if the {1_LongCivName:textkey} has an army at all. Any hostilities with them would be laughably one-sided.'
WHERE Tag = 'TXT_KEY_DIPLOSTRATEGY_MILITARY_STRENGTH_COMPARED_TO_US_PATHETIC';

UPDATE Language_zh_CN
SET Text = '我不确定是否{1_LongCivName:textkey}根本有一支军队。与他们的任何敌对行动都是可笑的片面的。'
WHERE Tag = 'TXT_KEY_DIPLOSTRATEGY_MILITARY_STRENGTH_COMPARED_TO_US_PATHETIC';

------------------------------------------------
-- Tech tree
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Allows land units to embark and cross water Tiles.'
WHERE Tag = 'TXT_KEY_ALLOWS_EMBARKING';

UPDATE Language_zh_CN
SET Text = '允许陆地单位登船并穿越水域。'
WHERE Tag = 'TXT_KEY_ALLOWS_EMBARKING';

UPDATE Language_en_US
SET Text = 'Eligible units receive [COLOR_POSITIVE_TEXT]{1_Promotion:textkey}[ENDCOLOR] Promotion: {2_PromotionHelp:textkey}'
WHERE Tag = 'TXT_KEY_FREE_PROMOTION_FROM_TECH';

UPDATE Language_zh_CN
SET Text = '符合条件的单位可领取[COLOR_POSITIVE_TEXT]{1_Promotion:textkey}[ENDCOLOR]晋升：{2_PromotionHelp:textkey}'
WHERE Tag = 'TXT_KEY_FREE_PROMOTION_FROM_TECH';

UPDATE Language_en_US
SET Text = '{@1_ImprovementDescription}: +{3_Yield} {4_Icon} {@2_YieldDescription}'
WHERE Tag = 'TXT_KEY_CIVILOPEDIA_SPECIALABILITIES_YIELDCHANGES';

UPDATE Language_zh_CN
SET Text = '{@1_ImprovementDescription}: +{3_Yield} {4_Icon} {@2_YieldDescription}'
WHERE Tag = 'TXT_KEY_CIVILOPEDIA_SPECIALABILITIES_YIELDCHANGES';

UPDATE Language_en_US
SET Text = '{@1_ImprovementDescription}: +{3_Yield} {4_Icon} {@2_YieldDescription} {TXT_KEY_ABLTY_FRESH_WATER_STRING}'
WHERE Tag = 'TXT_KEY_CIVILOPEDIA_SPECIALABILITIES_FRESHWATERYIELDCHANGES';

UPDATE Language_zh_CN
SET Text = '{@1_ImprovementDescription}: +{3_Yield} {4_Icon} {@2_YieldDescription} {TXT_KEY_ABLTY_FRESH_WATER_STRING}'
WHERE Tag = 'TXT_KEY_CIVILOPEDIA_SPECIALABILITIES_FRESHWATERYIELDCHANGES';

UPDATE Language_en_US
SET Text = '{@1_ImprovementDescription}: +{3_Yield} {4_Icon} {@2_YieldDescription} {TXT_KEY_ABLTY_NO_FRESH_WATER_STRING}'
WHERE Tag = 'TXT_KEY_CIVILOPEDIA_SPECIALABILITIES_NOFRESHWATERYIELDCHANGES';

UPDATE Language_zh_CN
SET Text = '{@1_ImprovementDescription}: +{3_Yield} {4_Icon} {@2_YieldDescription} {TXT_KEY_ABLTY_NO_FRESH_WATER_STRING}'
WHERE Tag = 'TXT_KEY_CIVILOPEDIA_SPECIALABILITIES_NOFRESHWATERYIELDCHANGES';

UPDATE Language_en_US
SET Text = '{TXT_KEY_ABLTY_FASTER_MOVEMENT_STRING} {@1_RouteDescription}'
WHERE Tag = 'TXT_KEY_CIVILOPEDIA_SPECIALABILITIES_MOVEMENT';

UPDATE Language_zh_CN
SET Text = '{TXT_KEY_ABLTY_FASTER_MOVEMENT_STRING} {@1_RouteDescription}'
WHERE Tag = 'TXT_KEY_CIVILOPEDIA_SPECIALABILITIES_MOVEMENT';

UPDATE Language_en_US
SET Text = '{1_ImprovementName:textkey}: +{3_Num} {2_YieldType:textkey} (Fresh Water).'
WHERE Tag = 'TXT_KEY_FRESH_WATER';

UPDATE Language_zh_CN
SET Text = '{1_ImprovementName:textkey}: +{3_Num} {2_YieldType:textkey}（淡水）。'
WHERE Tag = 'TXT_KEY_FRESH_WATER';

UPDATE Language_en_US
SET Text = '{1_ImprovementName:textkey}: +{3_Num} {2_YieldType:textkey} (Not Fresh Water).'
WHERE Tag = 'TXT_KEY_NO_FRESH_WATER';

UPDATE Language_zh_CN
SET Text = '{1_ImprovementName:textkey}: +{3_Num} {2_YieldType:textkey}（不是淡水）。'
WHERE Tag = 'TXT_KEY_NO_FRESH_WATER';

UPDATE Language_en_US
SET Text = '(Fresh Water)'
WHERE Tag = 'TXT_KEY_ABLTY_FRESH_WATER_STRING';

UPDATE Language_zh_CN
SET Text = '（淡水）'
WHERE Tag = 'TXT_KEY_ABLTY_FRESH_WATER_STRING';

UPDATE Language_en_US
SET Text = '(Not Fresh Water)'
WHERE Tag = 'TXT_KEY_ABLTY_NO_FRESH_WATER_STRING';

UPDATE Language_zh_CN
SET Text = '（不是淡水）'
WHERE Tag = 'TXT_KEY_ABLTY_NO_FRESH_WATER_STRING';

UPDATE Language_en_US
SET Text = 'Leads To:'
WHERE Tag = 'TXT_KEY_TECH_HELP_LEADS_TO';

UPDATE Language_zh_CN
SET Text = '导致：'
WHERE Tag = 'TXT_KEY_TECH_HELP_LEADS_TO';

------------------------------------------------
-- Civilopedia
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Welcome to the Civilopedia! Here you will find detailed descriptions of all aspects of the game. Use the "Search" field to search for articles on any specific subject. Clicking on the tabs on the top edge of the screen will take you to the various major sections of the Civilopedia. The Navigation Bar on the left side of the screen will display the various entries within a section. Click on an entry to go directly there.[NEWLINE][NEWLINE]In the upper left-hand portion of the screen you will find the forward and back buttons which will help you navigate between pages. Click on the "X" on the upper right portion of the screen to return to the game.[NEWLINE][NEWLINE]Welcome to the Community Patch, a mod containing several bugfixes and AI improvements. [COLOR_YELLOW]Game Concepts that have been changed in the Community Patch are highlighted in yellow in the Civilopedia.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PEDIA_HOME_PAGE_HELP_TEXT';

UPDATE Language_zh_CN
SET Text = '欢迎来到文明百科！在这里您可以找到游戏各个方面的详细描述。使用“搜索”字段搜索有关任何特定主题的文章。单击屏幕顶部边缘的选项卡将带您进入文明百科的各个主要部分。屏幕左侧的导航栏将显示一个部分中的各个条目。单击某个条目可直接转到该条目。[NEWLINE][NEWLINE]在屏幕的左上角，您将找到前进和后退按钮，它们将帮助您在页面之间导航。单击屏幕右上方的“X”返回游戏。[NEWLINE][NEWLINE]欢迎来到社区补丁，这是一个包含多个错误修复和人工智能改进的模组。[COLOR_YELLOW]社区补丁中已更改的游戏概念在文明百科中以黄色突出显示。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PEDIA_HOME_PAGE_HELP_TEXT';

UPDATE Language_en_US
SET Text = 'Civilization V examines all of human history - from the deep past to the day after tomorrow. The "Game Concepts" portion of the Civilopedia explains some of the more important parts of the game - how to build and manage cities, how to fight wars, how to research technology, and so forth. The left Navigation Bar displays the major concepts; click on an entry to see the subsections within the concepts.[NEWLINE][NEWLINE][COLOR_YELLOW]Game Concepts that have been changed in the Community Patch are highlighted in yellow.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PEDIA_GAME_CONCEPT_HELP_TEXT';

UPDATE Language_zh_CN
SET Text = '《文明 V》审视了人类的全部历史——从遥远的过去到后天。文明百科的“游戏概念”部分解释了游戏中一些更重要的部分——如何建造和管理城市、如何打仗、如何研究技术等等。左侧导航栏显示主要概念；单击条目可查看概念中的小节。[NEWLINE][NEWLINE][COLOR_YELLOW]社区补丁中已更改的游戏概念以黄色突出显示。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PEDIA_GAME_CONCEPT_HELP_TEXT';

UPDATE Language_en_US
SET Text = 'Base Yield:'
WHERE Tag = 'TXT_KEY_PEDIA_YIELD_LABEL';

UPDATE Language_zh_CN
SET Text = '基础产量：'
WHERE Tag = 'TXT_KEY_PEDIA_YIELD_LABEL';

UPDATE Language_en_US
SET Text = 'Connected By:'
WHERE Tag = 'TXT_KEY_PEDIA_IMPROVEMENTS_LABEL';

UPDATE Language_zh_CN
SET Text = '连接者：'
WHERE Tag = 'TXT_KEY_PEDIA_IMPROVEMENTS_LABEL';

UPDATE Language_en_US
SET Text = 'The three nations that once comprised historical India have taken very different paths in the late 20th and early 21st centuries. Bangladesh is a parliamentary democracy, a highly-dense country much subject to floods, cyclones and famine, though life for its population has steadily improved since its independence in the ''70s.[NEWLINE][NEWLINE]Pakistan is the sixth most populous country in the world and the second most populous Muslim country. While its economy has done well in the past 25 years, it remains locationally-challenged. To the east is India, its old enemy, with whom it has an ongoing border dispute, and both sides have recently acquired nuclear weapons. To the west is Afghanistan, now under Taliban control, where open conflict has diminished but harsh rule and repression - particularly of women - have returned. Pakistan''s future will depend on managing its own political stability, curbing extremism, and redefining its relationships with both neighbors.[NEWLINE][NEWLINE]India is the world''s second most populous country and a thriving democracy. It is loud, boisterous, and has a growing and vibrant economy. It has a technological base second to none, and an education system that rivals that of the United States. It also has a large army and an arsenal of nuclear weapons, primarily aimed at deterring Pakistan, though China has become an increasing strategic concern. If it can reduce tensions with its neighbors and maintain its current economic and technological trajectory, India is well on its way to becoming one of the defining powers of the 21st century.'
WHERE Tag = 'TXT_KEY_CIV5_INDIA_TEXT_16';

UPDATE Language_zh_CN
SET Text = '历史上曾经组成印度的三个国家在 20 世纪末和 21 世纪初走了截然不同的道路。孟加拉国是一个议会民主国家，是一个人口稠密的国家，经常遭受洪水、飓风和饥荒，尽管自 70 年代独立以来，其人民的生活稳步改善。[NEWLINE][NEWLINE]巴基斯坦是世界第六大人口国家和第二大穆斯林国家。尽管其经济在过去 25 年中表现良好，但其地理位置仍然面临挑战。东边是它的宿敌印度，两国之间一直存在边界争端，而且双方最近都获得了核武器。西边是阿富汗，现在由塔利班控制，那里的公开冲突已经减少，但严厉的统治和镇压——尤其是对妇女的镇压——又回来了。巴基斯坦的未来将取决于管理自身的政治稳定、遏制极端主义以及重新定义与两个邻国的关系。[NEWLINE][NEWLINE]印度是世界第二人口大国，也是一个欣欣向荣的民主国家。它喧闹、热闹，经济不断增长且充满活力。它拥有首屈一指的技术基础和可与美国相媲美的教育体系。它还拥有一支庞大的军队和核武器库，主要目的是威慑巴基斯坦，尽管中国已成为日益重要的战略关注点。如果印度能够缓解与邻国的紧张关系并维持其当前的经济和技术发展轨迹，那么印度将有望成为 21 世纪的决定性强国之一。'
WHERE Tag = 'TXT_KEY_CIV5_INDIA_TEXT_16';

UPDATE Language_en_US
SET Text = 'Kyivan'
WHERE Tag = 'TXT_KEY_CIV5_RUSSIA_HEADING_4';

UPDATE Language_zh_CN
SET Text = '基辅'
WHERE Tag = 'TXT_KEY_CIV5_RUSSIA_HEADING_4';

UPDATE Language_en_US
SET Text = 'The eighth century saw the first written record of "Kyivan Rus." The Rus are believed to have been Scandinavian Vikings who migrated south from the Baltic coast (although this is disputed by some Russian scholars, who believe that the original founders of Kyivan Rus were Slavs). By 860 the Rus were sending raiding parties as far south as Constantinople, and by 1000 AD Kyivan Rus controlled a trade route from the Baltic to the Black Sea; this would form the economic backbone of the growing regional power.[NEWLINE][NEWLINE]By the 12th century, the Kyiv Empire covered much of what would become eastern Russia, extending from Poland in the west to the Volga in the east, and from Finland in the north to the Ukraine in the south. It was a vast territory to manage from one centralized location, especially as component parts of the Empire began developing individual identities and national aspirations. Economically, the Empire also became divided, with northern provinces aligning themselves with the Baltic powers while the western areas were drawn to Poland and Hungary, and the southern regions to Asia Minor and the Mediterranean. By the closing of the 12th century Rus Kyiv was dissolved in all but name, replaced by a number of smaller quasi-feudal states.'
WHERE Tag = 'TXT_KEY_CIV5_RUSSIA_TEXT_4';

UPDATE Language_zh_CN
SET Text = '八世纪出现了“基辅罗斯”的第一个书面记录。罗斯人被认为是从波罗的海沿岸向南迁移的斯堪的纳维亚维京人（尽管一些俄罗斯学者对此有争议，他们认为基辅罗斯的最初创始人是斯拉夫人）。到公元 860 年，罗斯向南派出袭击队伍，远至君士坦丁堡；到公元 1000 年，基辅罗斯控制了从波罗的海到黑海的贸易路线；这将成为不断增长的区域力量的经济支柱。[NEWLINE][NEWLINE]到12世纪，基辅帝国覆盖了俄罗斯东部的大部分地区，从西部的波兰到东部的伏尔加河，从北部的芬兰到南部的乌克兰。这是一个可以从一个集中地点管理的广阔领土，特别是当帝国的组成部分开始发展个人身份和国家愿望时。在经济上，帝国也陷入分裂，北部省份与波罗的海列强结盟，而西部地区则被吸引到波兰和匈牙利，南部地区则被吸引到小亚细亚和地中海。到 12 世纪末，罗斯基辅已经解体，只剩下名字，取而代之的是一些较小的准封建国家。'
WHERE Tag = 'TXT_KEY_CIV5_RUSSIA_TEXT_4';

UPDATE Language_en_US
SET Text = 'The first Mongol incursion into Kyivan territory occurred in 1223, when a Mongol reconnaissance unit met the combined warriors of several Rus states under the command of the wonderfully-named "Mstislav the Bold" and "Mstislav Romanovich the Old" at the Battle of the Kalka River. The Rus forces enjoyed early success, but they became disorganized in the pursuit of the retreating foe. The Mongol horsemen rallied and defeated the pursuers in detail before they could reorganize. A large portion of the Rus forces surrendered to the Mongols on the condition that they would be spared; the Mongols accepted the conditions then slaughtered them anyway. The Mongols then left Rus for several years before returning in much greater force.[NEWLINE][NEWLINE]In 1237 a vast Mongol army of some 30,000 or more horse archers once again crossed the Volga River. In a few short years the Mongols captured, looted and destroyed dozens of Russian cities and towns, including Ryazan, Kolomna, Moscow, Rostov, Kashin, Dmitrov, Kozelsk, Halych and Kyiv. They soundly thrashed every force raised to oppose them. By 1240 most of Rus was a smoking ruin, firmly under the control of the Mongols, who then turned their sight further west, towards Hungary and Poland.[NEWLINE]'
WHERE Tag = 'TXT_KEY_CIV5_RUSSIA_TEXT_5';

UPDATE Language_zh_CN
SET Text = '蒙古人第一次入侵基辅领土发生在1223年，当时一支蒙古侦察部队在卡尔卡河战役中遇到了由“勇敢的姆斯蒂斯拉夫”和“老姆斯蒂斯拉夫·罗曼诺维奇”指挥的几个罗斯国家的联合战士。罗斯军队取得了早期的胜利，但在追击撤退的敌人时，他们变得混乱不堪。蒙古骑兵重整旗鼓，在追击者重新集结之前将其击溃。大部分罗斯军队向蒙古人投降，条件是他们能幸免于难。蒙古人接受了这些条件，然后还是屠杀了他们。蒙古人随后离开罗斯数年，然后以更强大的力量返回。[NEWLINE][NEWLINE]1237年，一支由约3万名弓骑兵组成的庞大蒙古军队再次渡过伏尔加河。在短短几年内，蒙古人占领、抢劫和摧毁了数十个俄罗斯城镇，包括梁赞、科洛姆纳、莫斯科、罗斯托夫、卡申、德米特洛夫、科泽尔斯克、哈利奇和基辅。他们狠狠地打击了所有反对他们的势力。到了 1240 年，罗斯的大部分地区已成为冒烟的废墟，牢牢地处于蒙古人的控制之下，随后蒙古人将目光转向更西的匈牙利和波兰。[NEWLINE]'
WHERE Tag = 'TXT_KEY_CIV5_RUSSIA_TEXT_5';

------------------------------------------------
-- Info tooltip
------------------------------------------------

-- Common
UPDATE Language_en_US
SET Text = 'Resources Required: {1_NumResource} {2_ResIcon} {3_Res:textkey}'
WHERE Tag = 'TXT_KEY_PRODUCTION_RESOURCES_REQUIRED';

UPDATE Language_zh_CN
SET Text = '所需资源：{1_NumResource} {2_ResIcon} {3_Res:textkey}'
WHERE Tag = 'TXT_KEY_PRODUCTION_RESOURCES_REQUIRED';

-- Building
UPDATE Language_en_US
SET Text = '{1: number "''[ICON_HAPPINESS_1] Happiness: ''#;''[ICON_HAPPINESS_3] Unhappiness '':#"}'
WHERE Tag = 'TXT_KEY_PRODUCTION_BUILDING_HAPPINESS';

UPDATE Language_zh_CN
SET Text = '{1: number "''[ICON_HAPPINESS_1] 快乐：''#;''[ICON_HAPPINESS_3] 不满：'':#"}'
WHERE Tag = 'TXT_KEY_PRODUCTION_BUILDING_HAPPINESS';

UPDATE Language_en_US
SET Text = '[ICON_STRENGTH] City Strength: {2_Sign}{1_Num}'
WHERE Tag = 'TXT_KEY_PRODUCTION_BUILDING_DEFENSE';

UPDATE Language_zh_CN
SET Text = '[ICON_STRENGTH]城市实力：{2_Sign}{1_Num}'
WHERE Tag = 'TXT_KEY_PRODUCTION_BUILDING_DEFENSE';

UPDATE Language_en_US
SET Text = '[ICON_STRENGTH] Hit Points: {2_Sign}{1_Num}'
WHERE Tag = 'TXT_KEY_PRODUCTION_BUILDING_HITPOINTS';

UPDATE Language_zh_CN
SET Text = '[ICON_STRENGTH]生命值：{2_Sign}{1_Num}'
WHERE Tag = 'TXT_KEY_PRODUCTION_BUILDING_HITPOINTS';

-- Yield
UPDATE Language_en_US
SET Text = '[ICON_FOOD] Food is what determines how fast your City grows to acquire new [ICON_CITIZEN] Citizens, who work the land and collect yields for the City. Bigger Cities are nearly always better, but beware of the increased [ICON_HAPPINESS_3] Unhappiness!'
WHERE Tag = 'TXT_KEY_FOOD_HELP_INFO';

UPDATE Language_zh_CN
SET Text = '[ICON_FOOD]食物决定了你的城市以多快的速度获得新的[ICON_CITIZEN]公民，他们耕种土地并为城市收集收益。大城市几乎总是更好，但要注意日益增加的城市[ICON_HAPPINESS_3]不幸！'
WHERE Tag = 'TXT_KEY_FOOD_HELP_INFO';

UPDATE Language_en_US
SET Text = '[ICON_PEACE] Faith is spent on founding and improving [ICON_RELIGION] Religions at the empire-level. Faith can also be expended to purchase Missionaries, Inquisitors, Religious Buildings, and Great People.'
WHERE Tag = 'TXT_KEY_FAITH_HELP_INFO';

UPDATE Language_zh_CN
SET Text = '[ICON_PEACE]信仰花在建立和完善上[ICON_RELIGION]帝国层面的宗教。信仰也可以用来购买传教士、审判官、宗教建筑和伟人。'
WHERE Tag = 'TXT_KEY_FAITH_HELP_INFO';

UPDATE Language_en_US
SET Text = '{1: number "''[COLOR_POSITIVE_TEXT]''#,##0.00;''[COLOR_NEGATIVE_TEXT]-''#,##0.00"} {2_IconString} Base[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_YIELD_BASE';

UPDATE Language_zh_CN
SET Text = '{1: number "''[COLOR_POSITIVE_TEXT]''#,##0.00;''[COLOR_NEGATIVE_TEXT]-''#,##0.00"} {2_IconString}根据[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_YIELD_BASE';

UPDATE Language_en_US
SET Text = '{1: number "''[COLOR_POSITIVE_TEXT]''#,##0.00;''[COLOR_NEGATIVE_TEXT]-''#,##0.00"} {2_IconString} Total[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_YIELD_TOTAL';

UPDATE Language_zh_CN
SET Text = '{1: number "''[COLOR_POSITIVE_TEXT]''#,##0.00;''[COLOR_NEGATIVE_TEXT]-''#,##0.00"} {2_IconString}全部的[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_YIELD_TOTAL';

UPDATE Language_en_US
SET Text = '[ICON_BULLET]{1_Num} {2_IconString} from [ICON_CULTURE] Culture'
WHERE Tag = 'TXT_KEY_YIELD_FROM_CULTURE';

UPDATE Language_zh_CN
SET Text = '[ICON_BULLET]{1_Num} {2_IconString}从[ICON_CULTURE]文化'
WHERE Tag = 'TXT_KEY_YIELD_FROM_CULTURE';

UPDATE Language_en_US
SET Text = '[ICON_BULLET]{1_Num} {2_IconString} from Terrain'
WHERE Tag = 'TXT_KEY_YIELD_FROM_TERRAIN';

UPDATE Language_zh_CN
SET Text = '[ICON_BULLET]{1_Num} {2_IconString}从地形'
WHERE Tag = 'TXT_KEY_YIELD_FROM_TERRAIN';

UPDATE Language_en_US
SET Text = '[ICON_BULLET]{1_Num} {2_IconString} from Buildings'
WHERE Tag = 'TXT_KEY_YIELD_FROM_BUILDINGS';

UPDATE Language_zh_CN
SET Text = '[ICON_BULLET]{1_Num} {2_IconString}从建筑物'
WHERE Tag = 'TXT_KEY_YIELD_FROM_BUILDINGS';

UPDATE Language_en_US
SET Text = '[ICON_BULLET]{1_Num} {2_IconString} from Specialists'
WHERE Tag = 'TXT_KEY_YIELD_FROM_SPECIALISTS';

UPDATE Language_zh_CN
SET Text = '[ICON_BULLET]{1_Num} {2_IconString}来自专家'
WHERE Tag = 'TXT_KEY_YIELD_FROM_SPECIALISTS';

UPDATE Language_en_US
SET Text = '[ICON_BULLET]{1_Num} {2_IconString} from Religion'
WHERE Tag = 'TXT_KEY_YIELD_FROM_RELIGION';

UPDATE Language_zh_CN
SET Text = '[ICON_BULLET]{1_Num} {2_IconString}来自宗教'
WHERE Tag = 'TXT_KEY_YIELD_FROM_RELIGION';

UPDATE Language_en_US
SET Text = '[ICON_BULLET]{1_Num} {2_IconString} from [ICON_CITIZEN] Population'
WHERE Tag = 'TXT_KEY_YIELD_FROM_POP';

UPDATE Language_zh_CN
SET Text = '[ICON_BULLET]{1_Num} {2_IconString}从[ICON_CITIZEN]人口'
WHERE Tag = 'TXT_KEY_YIELD_FROM_POP';

UPDATE Language_en_US
SET Text = '[ICON_BULLET]{1_Num} {2_IconString} from other sources'
WHERE Tag = 'TXT_KEY_YIELD_FROM_MISC';

UPDATE Language_zh_CN
SET Text = '[ICON_BULLET]{1_Num} {2_IconString}从其他来源'
WHERE Tag = 'TXT_KEY_YIELD_FROM_MISC';

------------------------------------------------
-- City screen/banner
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Do you want to annex the puppet of {@1_CityName} into your empire? It will allow you to manage the City, but will increase your [ICON_HAPPINESS_4] Unhappiness and the cost of new [ICON_CULTURE] Policies, [ICON_RESEARCH] Technologies, and [ICON_GOLDEN_AGE] Golden Ages. You will not be able to reverse this.'
WHERE Tag = 'TXT_KEY_POPUP_ANNEX_PUPPET';

UPDATE Language_zh_CN
SET Text = '你想吞并傀儡吗？{@1_CityName}进入你的帝国？它将允许你管理城市，但会增加你的[ICON_HAPPINESS_4]不快乐和新的成本[ICON_CULTURE]政策、[ICON_RESEARCH]技术，以及[ICON_GOLDEN_AGE]黄金时代。您将无法逆转这一情况。'
WHERE Tag = 'TXT_KEY_POPUP_ANNEX_PUPPET';

UPDATE Language_en_US
SET Text = '[NEWLINE]Requires {TXT_KEY_GRAMMAR_A_AN << {1_BuildingName:textkey}} in this City.'
WHERE Tag = 'TXT_KEY_NO_ACTION_UNIT_REQUIRES_BUILDING';

UPDATE Language_zh_CN
SET Text = '[NEWLINE]需要{TXT_KEY_GRAMMAR_A_AN << {1_BuildingName:textkey}在这个城市。'
WHERE Tag = 'TXT_KEY_NO_ACTION_UNIT_REQUIRES_BUILDING';

UPDATE Language_en_US
SET Text = 'City Combat Strength'
WHERE Tag = 'TXT_KEY_CITYVIEW_CITY_COMB_STRENGTH_TT';

UPDATE Language_zh_CN
SET Text = '城市战斗力'
WHERE Tag = 'TXT_KEY_CITYVIEW_CITY_COMB_STRENGTH_TT';

UPDATE Language_en_US
SET Text = 'LEFT CLICK adds an additional item to the end of the production queue.[NEWLINE]CTRL + LEFT CLICK adds an additional item in front of the production queue.[NEWLINE]ALT + LEFT CLICK adds the chosen item to the end of the production queue on repeat.[NEWLINE]SHIFT + LEFT CLICK replaces everything in the production queue with the chosen item.[NEWLINE]H hides the chosen building from this city''s production options.'
WHERE Tag = 'TXT_KEY_CITYVIEW_QUEUE_PROD_TT';

UPDATE Language_zh_CN
SET Text = '左键单击将附加项目添加到生产队列的末尾。[NEWLINE]CTRL + 左键单击在生产队列前面添加一个附加项目。[NEWLINE]ALT + 左键单击将所选项目重复添加到生产队列的末尾。[NEWLINE]SHIFT + 左键单击将生产队列中的所有内容替换为所选项目。[NEWLINE]H 将所选建筑从该城市的生产选项中隐藏起来。'
WHERE Tag = 'TXT_KEY_CITYVIEW_QUEUE_PROD_TT';

UPDATE Language_en_US
SET Text = 'Click here to stop this city from growing in [ICON_CITIZEN] Population.'
WHERE Tag = 'TXT_KEY_CITYVIEW_FOCUS_AVOID_GROWTH_TT';

UPDATE Language_zh_CN
SET Text = '单击此处阻止这座城市的发展[ICON_CITIZEN]人口。'
WHERE Tag = 'TXT_KEY_CITYVIEW_FOCUS_AVOID_GROWTH_TT';

UPDATE Language_en_US
SET Text = '{1_Num} [ICON_CULTURE] from Great Works and Themes'
WHERE Tag = 'TXT_KEY_CULTURE_FROM_GREAT_WORKS';

UPDATE Language_zh_CN
SET Text = '{1_Num} [ICON_CULTURE]来自伟大的作品和主题'
WHERE Tag = 'TXT_KEY_CULTURE_FROM_GREAT_WORKS';

UPDATE Language_en_US
SET Text = '{1_Num} [ICON_TOURISM] Tourism from {2_Num} [ICON_GREAT_WORK] {2_Num: plural 1?Great Work; other?Great Works;}'
WHERE Tag = 'TXT_KEY_CO_CITY_TOURISM_GREAT_WORKS';

UPDATE Language_zh_CN
SET Text = '{1_Num} [ICON_TOURISM]旅游来自{2_Num} [ICON_GREAT_WORK] {2_Num: plural 1?杰作; other?杰作;}'
WHERE Tag = 'TXT_KEY_CO_CITY_TOURISM_GREAT_WORKS';

UPDATE Language_en_US
SET Text = '{1_Num} [ICON_TOURISM] Tourism from buildings purchased with [ICON_PEACE] Faith'
WHERE Tag = 'TXT_KEY_CO_CITY_TOURISM_FAITH_BUILDINGS';

UPDATE Language_zh_CN
SET Text = '{1_Num} [ICON_TOURISM]购买建筑物的旅游[ICON_PEACE]信仰'
WHERE Tag = 'TXT_KEY_CO_CITY_TOURISM_FAITH_BUILDINGS';

UPDATE Language_en_US
SET Text = '{1_ReligionIcon} {2_NumFollowers} {2_NumFollowers: plural 1?Follower; other?Followers;} {3_PressureString}'
WHERE Tag = 'TXT_KEY_RELIGION_TOOLTIP_LINE';

UPDATE Language_zh_CN
SET Text = '{1_ReligionIcon} {2_NumFollowers} {2_NumFollowers: plural 1?信徒; other?信徒;} {3_PressureString}'
WHERE Tag = 'TXT_KEY_RELIGION_TOOLTIP_LINE';

UPDATE Language_en_US
SET Text = '{1_ReligionIcon} {2_NumFollowers} {2_NumFollowers: plural 1?Follower; other?Followers;} {3_PressureString} ({4_Num} trade routes)'
WHERE Tag = 'TXT_KEY_RELIGION_TOOLTIP_LINE_WITH_TRADE';

UPDATE Language_zh_CN
SET Text = '{1_ReligionIcon} {2_NumFollowers} {2_NumFollowers: plural 1?信徒; other?信徒;} {3_PressureString} ({4_Num} 条商路)'
WHERE Tag = 'TXT_KEY_RELIGION_TOOLTIP_LINE_WITH_TRADE';

------------------------------------------------
-- Conquest picker
------------------------------------------------
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Razing[ENDCOLOR] The City will burn [ICON_RAZING] down each turn until it reaches 0 population, and is removed from the game. This produces a lot of [ICON_HAPPINESS_4] Unhappiness, but also increases your [COLOR_POSITIVE_TEXT]War Score[ENDCOLOR] versus this player.'
WHERE Tag = 'TXT_KEY_POPUP_CITY_CAPTURE_INFO_RAZE';

UPDATE Language_zh_CN
SET Text = '[COLOR_POSITIVE_TEXT]夷为平地[ENDCOLOR]城市将被烧毁[ICON_RAZING]每回合都会下降，直到达到 0 人口，然后从游戏中移除。这会产生很多[ICON_HAPPINESS_4]不快乐，也会增加你的[COLOR_POSITIVE_TEXT]战争分数[ENDCOLOR]与这位玩家进行对抗。'
WHERE Tag = 'TXT_KEY_POPUP_CITY_CAPTURE_INFO_RAZE';

------------------------------------------------
-- Great Person panel
------------------------------------------------
UPDATE Language_en_US
SET Text = '{1_Progress}/{2_Threshold}, {3_Turns} {3_Turns: plural 1?Turn; other?Turns;} Remaining'
WHERE Tag = 'TXT_KEY_GPLIST_PROGRESS';

UPDATE Language_zh_CN
SET Text = '{1_Progress}/{2_Threshold}，剩余 {3_Turns} {3_Turns: plural 1?回合; other?回合;}'
WHERE Tag = 'TXT_KEY_GPLIST_PROGRESS';

------------------------------------------------
-- Unit panel
------------------------------------------------
UPDATE Language_en_US
SET Text = '{1_Num} {1_Num: plural 1?Turn; other?Turns;}'
WHERE Tag = 'TXT_KEY_BUILD_NUM_TURNS';

UPDATE Language_zh_CN
SET Text = '{1_Num} {1_Num: plural 1?回合; other?回合;}'
WHERE Tag = 'TXT_KEY_BUILD_NUM_TURNS';

UPDATE Language_en_US
SET Text = 'After this action is performed, [COLOR_POSITIVE_TEXT]{2_NumFollowers}[ENDCOLOR] {2_NumFollowers: plural 1?Citizens; other?Citizens;} will be following [COLOR_POSITIVE_TEXT]{1_ReligionName}[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_MISSION_SPREAD_RELIGION_RESULT';

UPDATE Language_zh_CN
SET Text = '执行此操作后，[COLOR_POSITIVE_TEXT]{2_NumFollowers}[ENDCOLOR] {2_NumFollowers: plural 1?公民; other?公民;}将信奉[COLOR_POSITIVE_TEXT]{1_ReligionName}[ENDCOLOR]。'
WHERE Tag = 'TXT_KEY_MISSION_SPREAD_RELIGION_RESULT';

UPDATE Language_en_US
SET Text = 'Your Unit may move {1_Num} more {1_Num: plural 1?tile; other?tiles;} this turn.'
WHERE Tag = 'TXT_KEY_UPANEL_UNIT_MAY_MOVE';

UPDATE Language_zh_CN
SET Text = '你的单位本回合还可以额外移动 {1_Num} {1_Num: plural 1?地块; other?地块;}。'
WHERE Tag = 'TXT_KEY_UPANEL_UNIT_MAY_MOVE';

UPDATE Language_en_US
SET Text = 'Your Unit may strike within {1_Num} {1_Num: plural 1?tile; other?tiles;} or rebase within {2_Num} tiles.'
WHERE Tag = 'TXT_KEY_UPANEL_UNIT_MAY_STRIKE_REBASE';

UPDATE Language_zh_CN
SET Text = '你的单位可以在 {1_Num} {1_Num: plural 1?地块; other?地块;} 范围内打击，或在 {2_Num} 地块范围内重新部署。'
WHERE Tag = 'TXT_KEY_UPANEL_UNIT_MAY_STRIKE_REBASE';

------------------------------------------------
-- Combat simulator
------------------------------------------------
UPDATE Language_en_US
SET Text = '[COLOR_CYAN]Capture chance if defeated[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_EUPANEL_CAPTURE_CHANCE';

UPDATE Language_zh_CN
SET Text = '[COLOR_CYAN]击败后抓住机会[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_EUPANEL_CAPTURE_CHANCE';

UPDATE Language_en_US
SET Text = '[COLOR_WARNING_TEXT]{1_Number} known {1_Number: plural 1?Interceptor; other?Interceptors;}![ENDCOLOR]'
WHERE Tag = 'TXT_KEY_EUPANEL_VISIBLE_AA_UNITS';

UPDATE Language_zh_CN
SET Text = '[COLOR_WARNING_TEXT]{1_Number}已知的{1_Number: plural 1?Interceptor; other?Interceptors;}![ENDCOLOR]'
WHERE Tag = 'TXT_KEY_EUPANEL_VISIBLE_AA_UNITS';

UPDATE Language_en_US
SET Text = 'Distance from Capital'
WHERE Tag = 'TXT_KEY_EUPANEL_CAPITAL_DEFENSE_BONUS';

UPDATE Language_zh_CN
SET Text = '距首都的距离'
WHERE Tag = 'TXT_KEY_EUPANEL_CAPITAL_DEFENSE_BONUS';

------------------------------------------------
-- Diplomacy overview / player icon tooltip
------------------------------------------------

-- Neutral Indicators
UPDATE Language_en_US
SET Text = 'ELIMINATED'
WHERE Tag = 'TXT_KEY_EMOTIONLESS';

UPDATE Language_zh_CN
SET Text = '被淘汰'
WHERE Tag = 'TXT_KEY_EMOTIONLESS';

------------------------------------------------
-- Opinion modifiers
------------------------------------------------

-- Dispute Modifiers
UPDATE Language_en_US
SET Text = 'Territorial disputes strain your relationship.'
WHERE Tag = 'TXT_KEY_DIPLO_LAND_DISPUTE';

UPDATE Language_zh_CN
SET Text = '领土争端使你们的关系紧张。'
WHERE Tag = 'TXT_KEY_DIPLO_LAND_DISPUTE';

UPDATE Language_en_US
SET Text = 'You are competing for World Wonders.'
WHERE Tag = 'TXT_KEY_DIPLO_WONDER_DISPUTE';

UPDATE Language_zh_CN
SET Text = '你正在争夺世界奇迹。'
WHERE Tag = 'TXT_KEY_DIPLO_WONDER_DISPUTE';

UPDATE Language_en_US
SET Text = 'You are competing for the favor of the same City-States!'
WHERE Tag = 'TXT_KEY_DIPLO_MINOR_CIV_DISPUTE';

UPDATE Language_zh_CN
SET Text = '你们正在争夺同一个城邦的青睐！'
WHERE Tag = 'TXT_KEY_DIPLO_MINOR_CIV_DISPUTE';

-- War Stuff
UPDATE Language_en_US
SET Text = 'They have some early concerns about your warmongering.'
WHERE Tag = 'TXT_KEY_DIPLO_WARMONGER_THREAT_MINOR';

UPDATE Language_zh_CN
SET Text = '他们对你的好战行为有一些早期的担忧。'
WHERE Tag = 'TXT_KEY_DIPLO_WARMONGER_THREAT_MINOR';

UPDATE Language_en_US
SET Text = 'They are wary of the potential threat posed by your warmongering.'
WHERE Tag = 'TXT_KEY_DIPLO_WARMONGER_THREAT_MAJOR';

UPDATE Language_zh_CN
SET Text = '他们对你的好战行为构成的潜在威胁保持警惕。'
WHERE Tag = 'TXT_KEY_DIPLO_WARMONGER_THREAT_MAJOR';

UPDATE Language_en_US
SET Text = 'They believe your warmongering has become an existential threat.'
WHERE Tag = 'TXT_KEY_DIPLO_WARMONGER_THREAT_SEVERE';

UPDATE Language_zh_CN
SET Text = '他们相信你的好战行为已经成为一种生存威胁。'
WHERE Tag = 'TXT_KEY_DIPLO_WARMONGER_THREAT_SEVERE';

UPDATE Language_en_US
SET Text = 'They fear your warmongering will end this world in fire!'
WHERE Tag = 'TXT_KEY_DIPLO_WARMONGER_THREAT_CRITICAL';

UPDATE Language_zh_CN
SET Text = '他们担心你的好战行为会让这个世界陷入火海！'
WHERE Tag = 'TXT_KEY_DIPLO_WARMONGER_THREAT_CRITICAL';

UPDATE Language_en_US
SET Text = '[SPACE](They strongly dislike warmongers.)'
WHERE Tag = 'TXT_KEY_WARMONGER_HATE_HIGH';

UPDATE Language_zh_CN
SET Text = '[空格]（他们非常不喜欢战争贩子。）'
WHERE Tag = 'TXT_KEY_WARMONGER_HATE_HIGH';

UPDATE Language_en_US
SET Text = '[SPACE](They dislike warmongers.)'
WHERE Tag = 'TXT_KEY_WARMONGER_HATE_MID';

UPDATE Language_zh_CN
SET Text = '[空格]（他们不喜欢战争贩子。）'
WHERE Tag = 'TXT_KEY_WARMONGER_HATE_MID';

UPDATE Language_en_US
SET Text = '[SPACE](They overlook modest warmongering.)'
WHERE Tag = 'TXT_KEY_WARMONGER_HATE_LOW';

UPDATE Language_zh_CN
SET Text = '[空格]（他们忽视了适度的好战行为。）'
WHERE Tag = 'TXT_KEY_WARMONGER_HATE_LOW';

UPDATE Language_en_US
SET Text = 'You plundered their trade routes!'
WHERE Tag = 'TXT_KEY_DIPLO_PLUNDERING_OUR_TRADE_ROUTES';

UPDATE Language_zh_CN
SET Text = '你掠夺了他们的贸易路线！'
WHERE Tag = 'TXT_KEY_DIPLO_PLUNDERING_OUR_TRADE_ROUTES';

UPDATE Language_en_US
SET Text = 'You nuked them!'
WHERE Tag = 'TXT_KEY_DIPLO_NUKED';

UPDATE Language_zh_CN
SET Text = '你用核武器袭击了他们！'
WHERE Tag = 'TXT_KEY_DIPLO_NUKED';

UPDATE Language_en_US
SET Text = 'You have gone to war in the past.'
WHERE Tag = 'TXT_KEY_DIPLO_PAST_WAR_BAD';

UPDATE Language_zh_CN
SET Text = '你过去曾参加过战争。'
WHERE Tag = 'TXT_KEY_DIPLO_PAST_WAR_BAD';

UPDATE Language_en_US
SET Text = 'You captured their original capital.'
WHERE Tag = 'TXT_KEY_DIPLO_CAPTURED_CAPITAL';

UPDATE Language_zh_CN
SET Text = '你夺走了他们的原始资本。'
WHERE Tag = 'TXT_KEY_DIPLO_CAPTURED_CAPITAL';

-- Recent diplomatic actions
UPDATE Language_en_US
SET Text = 'Your recent diplomatic actions please them.'
WHERE Tag = 'TXT_KEY_DIPLO_ASSISTANCE_TO_THEM';

UPDATE Language_zh_CN
SET Text = '你最近的外交行动令他们高兴。'
WHERE Tag = 'TXT_KEY_DIPLO_ASSISTANCE_TO_THEM';

UPDATE Language_en_US
SET Text = 'Your recent diplomatic actions disappoint them.'
WHERE Tag = 'TXT_KEY_DIPLO_REFUSED_REQUESTS';

UPDATE Language_zh_CN
SET Text = '你最近的外交行动令他们失望。'
WHERE Tag = 'TXT_KEY_DIPLO_REFUSED_REQUESTS';

-- Player has done nice stuff
UPDATE Language_en_US
SET Text = 'We are trade partners.'
WHERE Tag = 'TXT_KEY_DIPLO_TRADE_PARTNER';

UPDATE Language_zh_CN
SET Text = '我们是贸易伙伴。'
WHERE Tag = 'TXT_KEY_DIPLO_TRADE_PARTNER';

UPDATE Language_en_US
SET Text = 'We fought together against a common foe.'
WHERE Tag = 'TXT_KEY_DIPLO_COMMON_FOE';

UPDATE Language_zh_CN
SET Text = '我们一起对抗共同的敌人。'
WHERE Tag = 'TXT_KEY_DIPLO_COMMON_FOE';

UPDATE Language_en_US
SET Text = 'You freed their captured citizens!'
WHERE Tag = 'TXT_KEY_DIPLO_CIVILIANS_RETURNED';

UPDATE Language_zh_CN
SET Text = '你释放了他们被俘的公民！'
WHERE Tag = 'TXT_KEY_DIPLO_CIVILIANS_RETURNED';

UPDATE Language_en_US
SET Text = 'You built a Landmark in their territory.'
WHERE Tag = 'TXT_KEY_DIPLO_LANDMARKS_BUILT';

UPDATE Language_zh_CN
SET Text = '你在他们的领土上建立了一个地标。'
WHERE Tag = 'TXT_KEY_DIPLO_LANDMARKS_BUILT';

UPDATE Language_en_US
SET Text = 'You restored their civilization after they were annihilated!'
WHERE Tag = 'TXT_KEY_DIPLO_RESURRECTED';

UPDATE Language_zh_CN
SET Text = '他们被消灭后，你又恢复了他们的文明！'
WHERE Tag = 'TXT_KEY_DIPLO_RESURRECTED';

UPDATE Language_en_US
SET Text = 'You liberated their original capital.'
WHERE Tag = 'TXT_KEY_DIPLO_LIBERATED_CAPITAL';

UPDATE Language_zh_CN
SET Text = '你解放了他们的原始资本。'
WHERE Tag = 'TXT_KEY_DIPLO_LIBERATED_CAPITAL';

UPDATE Language_en_US
SET Text = 'You have liberated some of their people!'
WHERE Tag = 'TXT_KEY_DIPLO_CITIES_LIBERATED';

UPDATE Language_zh_CN
SET Text = '你解放了他们的一些人民！'
WHERE Tag = 'TXT_KEY_DIPLO_CITIES_LIBERATED';

UPDATE Language_en_US
SET Text = 'They have an embassy in your capital.'
WHERE Tag = 'TXT_KEY_DIPLO_HAS_EMBASSY';

UPDATE Language_zh_CN
SET Text = '他们在你们的首都设有大使馆。'
WHERE Tag = 'TXT_KEY_DIPLO_HAS_EMBASSY';

UPDATE Language_en_US
SET Text = 'You forgave them for spying.'
WHERE Tag = 'TXT_KEY_DIPLO_FORGAVE_FOR_SPYING';

UPDATE Language_zh_CN
SET Text = '你原谅了他们的间谍活动。'
WHERE Tag = 'TXT_KEY_DIPLO_FORGAVE_FOR_SPYING';

UPDATE Language_en_US
SET Text = 'You have shared intrigue with them.'
WHERE Tag = 'TXT_KEY_DIPLO_SHARED_INTRIGUE';

UPDATE Language_zh_CN
SET Text = '你与他们分享了阴谋。'
WHERE Tag = 'TXT_KEY_DIPLO_SHARED_INTRIGUE';

-- Player has done mean stuff
UPDATE Language_en_US
SET Text = 'You stole their territory while at peace!'
WHERE Tag = 'TXT_KEY_DIPLO_CULTURE_BOMB';

UPDATE Language_zh_CN
SET Text = '你在和平时期偷走了他们的领土！'
WHERE Tag = 'TXT_KEY_DIPLO_CULTURE_BOMB';

UPDATE Language_en_US
SET Text = 'Your spies were caught stealing from them.'
WHERE Tag = 'TXT_KEY_DIPLO_CAUGHT_STEALING';

UPDATE Language_zh_CN
SET Text = '你的间谍在偷窃他们的东西时被发现了。'
WHERE Tag = 'TXT_KEY_DIPLO_CAUGHT_STEALING';

-- Player has asked us to do things we don't like
UPDATE Language_en_US
SET Text = 'You demanded they not settle near your lands!'
WHERE Tag = 'TXT_KEY_DIPLO_NO_SETTLE_ASKED';

UPDATE Language_zh_CN
SET Text = '你要求他们不要在你的土地附近定居！'
WHERE Tag = 'TXT_KEY_DIPLO_NO_SETTLE_ASKED';

UPDATE Language_en_US
SET Text = 'You asked them not to spy on you.'
WHERE Tag = 'TXT_KEY_DIPLO_STOP_SPYING_ASKED';

UPDATE Language_zh_CN
SET Text = '你要求他们不要监视你。'
WHERE Tag = 'TXT_KEY_DIPLO_STOP_SPYING_ASKED';

UPDATE Language_en_US
SET Text = 'You made a trade demand of them!'
WHERE Tag = 'TXT_KEY_DIPLO_TRADE_DEMAND';

UPDATE Language_zh_CN
SET Text = '您向他们提出了贸易需求！'
WHERE Tag = 'TXT_KEY_DIPLO_TRADE_DEMAND';

UPDATE Language_en_US
SET Text = 'You forced them to pay tribute.'
WHERE Tag = 'TXT_KEY_DIPLO_PAID_TRIBUTE';

UPDATE Language_zh_CN
SET Text = '你强迫他们致敬。'
WHERE Tag = 'TXT_KEY_DIPLO_PAID_TRIBUTE';

-- Denouncing
UPDATE Language_en_US
SET Text = 'We have denounced them!'
WHERE Tag = 'TXT_KEY_DIPLO_DENOUNCED_BY_US';

UPDATE Language_zh_CN
SET Text = '我们已经谴责他们了！'
WHERE Tag = 'TXT_KEY_DIPLO_DENOUNCED_BY_US';

UPDATE Language_en_US
SET Text = 'They have denounced us!'
WHERE Tag = 'TXT_KEY_DIPLO_DENOUNCED_BY_THEM';

UPDATE Language_zh_CN
SET Text = '他们已经谴责我们了！'
WHERE Tag = 'TXT_KEY_DIPLO_DENOUNCED_BY_THEM';

UPDATE Language_en_US
SET Text = 'You have denounced a leader they made a Declaration of Friendship with!'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DENOUNCED_FRIEND';

UPDATE Language_zh_CN
SET Text = '你谴责了一位与他们发表了友好宣言的领导人！'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DENOUNCED_FRIEND';

UPDATE Language_en_US
SET Text = 'You have denounced one of their declared enemies!'
WHERE Tag = 'TXT_KEY_DIPLO_MUTUAL_ENEMY';

UPDATE Language_zh_CN
SET Text = '你已经谴责了他们公开的敌人之一！'
WHERE Tag = 'TXT_KEY_DIPLO_MUTUAL_ENEMY';

UPDATE Language_en_US
SET Text = 'Their friends or allies have denounced you!'
WHERE Tag = 'TXT_KEY_DIPLO_DENOUNCED_BY_PEOPLE_WE_TRUST_MORE';

UPDATE Language_zh_CN
SET Text = '他们的朋友或盟友谴责了你！'
WHERE Tag = 'TXT_KEY_DIPLO_DENOUNCED_BY_PEOPLE_WE_TRUST_MORE';

-- Promises
UPDATE Language_en_US
SET Text = 'You made a promise not to declare war on them, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_MILITARY_PROMISE';

UPDATE Language_zh_CN
SET Text = '你曾许诺不向他们宣战，但后来又违背了！'
WHERE Tag = 'TXT_KEY_DIPLO_MILITARY_PROMISE';

UPDATE Language_en_US
SET Text = 'You made a promise not to declare war on another civilization, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_MILITARY_PROMISE_BROKEN_WITH_OTHERS';

UPDATE Language_zh_CN
SET Text = '你曾许诺不向另一个文明宣战，但却违背了它！'
WHERE Tag = 'TXT_KEY_DIPLO_MILITARY_PROMISE_BROKEN_WITH_OTHERS';

UPDATE Language_en_US
SET Text = 'You refused to move your troops away from their borders when they asked!'
WHERE Tag = 'TXT_KEY_DIPLO_MILITARY_PROMISE_IGNORED';

UPDATE Language_zh_CN
SET Text = '当他们提出要求时，你却拒绝将你的军队撤出边境！'
WHERE Tag = 'TXT_KEY_DIPLO_MILITARY_PROMISE_IGNORED';

UPDATE Language_en_US
SET Text = 'You made a promise to stop settling near them, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_EXPANSION_PROMISE';

UPDATE Language_zh_CN
SET Text = '你曾许诺不再在他们附近定居，但后来又违背了！'
WHERE Tag = 'TXT_KEY_DIPLO_EXPANSION_PROMISE';

UPDATE Language_en_US
SET Text = 'They asked you to stop settling near them, and you ignored them!'
WHERE Tag = 'TXT_KEY_DIPLO_EXPANSION_PROMISE_IGNORED';

UPDATE Language_zh_CN
SET Text = '他们要求你停止在他们附近定居，但你却无视他们！'
WHERE Tag = 'TXT_KEY_DIPLO_EXPANSION_PROMISE_IGNORED';

UPDATE Language_en_US
SET Text = 'You made a promise to stop buying land near them, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_BORDER_PROMISE';

UPDATE Language_zh_CN
SET Text = '你曾承诺不再购买他们附近的土地，但后来又违背了！'
WHERE Tag = 'TXT_KEY_DIPLO_BORDER_PROMISE';

UPDATE Language_en_US
SET Text = 'They asked you to stop buying land near them, and you ignored them!'
WHERE Tag = 'TXT_KEY_DIPLO_BORDER_PROMISE_IGNORED';

UPDATE Language_zh_CN
SET Text = '他们要求你停止购买他们附近的土地，你却无视他们！'
WHERE Tag = 'TXT_KEY_DIPLO_BORDER_PROMISE_IGNORED';

UPDATE Language_en_US
SET Text = 'You made a promise not to conquer a City-State protected by them, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_CITY_STATE_PROMISE';

UPDATE Language_zh_CN
SET Text = '你曾许诺不征服受他们保护的城邦，然后又违背了！'
WHERE Tag = 'TXT_KEY_DIPLO_CITY_STATE_PROMISE';

UPDATE Language_en_US
SET Text = 'You made a promise not to conquer another civilization''s protected City-State, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_CITY_STATE_PROMISE_BROKEN_WITH_OTHERS';

UPDATE Language_zh_CN
SET Text = '你曾许诺不征服另一个文明受保护的城邦，然后又违背了它！'
WHERE Tag = 'TXT_KEY_DIPLO_CITY_STATE_PROMISE_BROKEN_WITH_OTHERS';

UPDATE Language_en_US
SET Text = 'They asked you to stop attacking a City-State protected by them, and you ignored them!'
WHERE Tag = 'TXT_KEY_DIPLO_CITY_STATE_PROMISE_IGNORED';

UPDATE Language_zh_CN
SET Text = '他们要求你停止攻击受他们保护的城邦，你却无视他们！'
WHERE Tag = 'TXT_KEY_DIPLO_CITY_STATE_PROMISE_IGNORED';

UPDATE Language_en_US
SET Text = 'You made a promise to stop demanding tribute from a City-State protected by them, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_BULLY_CITY_STATE_PROMISE_BROKEN';

UPDATE Language_zh_CN
SET Text = '你曾许诺不再向受他们保护的城邦索取贡品，但后来又违背了！'
WHERE Tag = 'TXT_KEY_DIPLO_BULLY_CITY_STATE_PROMISE_BROKEN';

UPDATE Language_en_US
SET Text = 'They asked you to stop demanding tribute from a City-State protected by them, and you ignored them!'
WHERE Tag = 'TXT_KEY_DIPLO_BULLY_CITY_STATE_PROMISE_IGNORED';

UPDATE Language_zh_CN
SET Text = '他们要求你停止向受他们保护的城邦索取贡品，但你却无视他们！'
WHERE Tag = 'TXT_KEY_DIPLO_BULLY_CITY_STATE_PROMISE_IGNORED';

UPDATE Language_en_US
SET Text = 'You made a promise to stop converting their cities, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_NO_CONVERT_PROMISE_BROKEN';

UPDATE Language_zh_CN
SET Text = '你曾许诺停止改造他们的城市，然后又违背了！'
WHERE Tag = 'TXT_KEY_DIPLO_NO_CONVERT_PROMISE_BROKEN';

UPDATE Language_en_US
SET Text = 'They asked you to stop converting their cities, and you ignored them!'
WHERE Tag = 'TXT_KEY_DIPLO_NO_CONVERT_PROMISE_IGNORED';

UPDATE Language_zh_CN
SET Text = '他们要求你停止改造他们的城市，但你无视他们！'
WHERE Tag = 'TXT_KEY_DIPLO_NO_CONVERT_PROMISE_IGNORED';

UPDATE Language_en_US
SET Text = 'You made a promise to stop excavating their artifacts, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_NO_DIG_PROMISE_BROKEN';

UPDATE Language_zh_CN
SET Text = '你曾承诺停止挖掘他们的文物，但后来又违背了！'
WHERE Tag = 'TXT_KEY_DIPLO_NO_DIG_PROMISE_BROKEN';

UPDATE Language_en_US
SET Text = 'They asked you to stop excavating their artifacts, and you ignored them!'
WHERE Tag = 'TXT_KEY_DIPLO_NO_DIG_PROMISE_IGNORED';

UPDATE Language_zh_CN
SET Text = '他们要求你停止挖掘他们的文物，但你却无视他们！'
WHERE Tag = 'TXT_KEY_DIPLO_NO_DIG_PROMISE_IGNORED';

UPDATE Language_en_US
SET Text = 'You made a promise to stop spying on them, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_SPY_PROMISE_BROKEN';

UPDATE Language_zh_CN
SET Text = '你曾承诺不再监视他们，但后来又违背了！'
WHERE Tag = 'TXT_KEY_DIPLO_SPY_PROMISE_BROKEN';

UPDATE Language_en_US
SET Text = 'They asked you to stop spying on them, and you ignored them!'
WHERE Tag = 'TXT_KEY_DIPLO_SPY_PROMISE_IGNORED';

UPDATE Language_zh_CN
SET Text = '他们要求你停止监视他们，你却无视他们！'
WHERE Tag = 'TXT_KEY_DIPLO_SPY_PROMISE_IGNORED';

UPDATE Language_en_US
SET Text = 'You made a promise to start a cooperative war against another empire, and then broke it!'
WHERE Tag = 'TXT_KEY_DIPLO_COOP_WAR_PROMISE';

UPDATE Language_zh_CN
SET Text = '你曾许诺要对另一个帝国发动合作战争，但后来又违背了！'
WHERE Tag = 'TXT_KEY_DIPLO_COOP_WAR_PROMISE';

-- Religion / Ideology
UPDATE Language_en_US
SET Text = 'They have happily adopted your religion in the majority of their cities.' -- note for translators: swapped HIS and MY text keys from vanilla
WHERE Tag = 'TXT_KEY_DIPLO_ADOPTING_HIS_RELIGION';

UPDATE Language_en_US
SET Text = 'You have adopted their religion in the majority of your cities.'  -- note for translators: swapped HIS and MY text keys from vanilla
WHERE Tag = 'TXT_KEY_DIPLO_ADOPTING_MY_RELIGION';

UPDATE Language_en_US
SET Text = 'They are spreading their own religion, but you converted some of their cities to your religion.'
WHERE Tag = 'TXT_KEY_DIPLO_RELIGIOUS_CONVERSIONS';

UPDATE Language_zh_CN
SET Text = '他们正在传播自己的宗教，但你却将他们的一些城市转变为你的宗教。'
WHERE Tag = 'TXT_KEY_DIPLO_RELIGIOUS_CONVERSIONS';

UPDATE Language_en_US
SET Text = 'You have both chosen to adopt the {1_PolicyTree} Ideology.'
WHERE Tag = 'TXT_KEY_DIPLO_SAME_LATE_POLICY_TREES';

UPDATE Language_zh_CN
SET Text = '你们都选择采用{1_PolicyTree}思想。'
WHERE Tag = 'TXT_KEY_DIPLO_SAME_LATE_POLICY_TREES';

UPDATE Language_en_US
SET Text = 'You have chosen to adopt the {1_YourPolicyTree} Ideology, but they believe in {2_TheirPolicyTree}.'
WHERE Tag = 'TXT_KEY_DIPLO_DIFFERENT_LATE_POLICY_TREES';

UPDATE Language_zh_CN
SET Text = '您已选择采用{1_YourPolicyTree}意识形态，但他们相信{2_TheirPolicyTree}.'
WHERE Tag = 'TXT_KEY_DIPLO_DIFFERENT_LATE_POLICY_TREES';

-- Protected Minors
UPDATE Language_en_US
SET Text = 'You have conquered City-States under their protection!'
WHERE Tag = 'TXT_KEY_DIPLO_PROTECTED_MINORS_KILLED';

UPDATE Language_zh_CN
SET Text = '你已经在他们的保护下征服了城邦！'
WHERE Tag = 'TXT_KEY_DIPLO_PROTECTED_MINORS_KILLED';

UPDATE Language_en_US
SET Text = 'You have attacked City-States under their protection!'
WHERE Tag = 'TXT_KEY_DIPLO_PROTECTED_MINORS_ATTACKED';

UPDATE Language_zh_CN
SET Text = '你们袭击了他们保护下的城邦！'
WHERE Tag = 'TXT_KEY_DIPLO_PROTECTED_MINORS_ATTACKED';

UPDATE Language_en_US
SET Text = 'You have demanded tribute from City-States under their protection!'
WHERE Tag = 'TXT_KEY_DIPLO_PROTECTED_MINORS_BULLIED';

UPDATE Language_zh_CN
SET Text = '你们要求受到保护的城邦的贡品！'
WHERE Tag = 'TXT_KEY_DIPLO_PROTECTED_MINORS_BULLIED';

UPDATE Language_en_US
SET Text = 'They mistreated your protected City-States, and you didn''t look the other way!'
WHERE Tag = 'TXT_KEY_DIPLO_SIDED_WITH_MINOR';

UPDATE Language_zh_CN
SET Text = '他们虐待你们受保护的城邦，而你们却没有视而不见！'
WHERE Tag = 'TXT_KEY_DIPLO_SIDED_WITH_MINOR';

-- Declaration of Friendship
UPDATE Language_en_US
SET Text = 'We have made a public Declaration of Friendship!'
WHERE Tag = 'TXT_KEY_DIPLO_DOF';

UPDATE Language_zh_CN
SET Text = '我们公开发表了友好宣言！'
WHERE Tag = 'TXT_KEY_DIPLO_DOF';

UPDATE Language_en_US
SET Text = 'We have made Declarations of Friendship with the same leaders!'
WHERE Tag = 'TXT_KEY_DIPLO_MUTUAL_DOF';

UPDATE Language_zh_CN
SET Text = '我们与同样的领导人发表了友好宣言！'
WHERE Tag = 'TXT_KEY_DIPLO_MUTUAL_DOF';

UPDATE Language_en_US
SET Text = 'You have made a Declaration of Friendship with one of their enemies!'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DOF_WITH_ENEMY';

UPDATE Language_zh_CN
SET Text = '您已与他们的敌人之一发表了一份友谊宣言！'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DOF_WITH_ENEMY';

-- Traitor Opinion
UPDATE Language_en_US
SET Text = 'Your friends found reason to denounce you!'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DENOUNCED_BY_FRIENDS';

UPDATE Language_zh_CN
SET Text = '你的朋友找到了谴责你的理由！'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DENOUNCED_BY_FRIENDS';

UPDATE Language_en_US
SET Text = 'You have denounced leaders you''ve made Declarations of Friendship with!'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DENOUNCED_FRIENDS';

UPDATE Language_zh_CN
SET Text = '你们谴责了与你们发表友好宣言的领导人！'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DENOUNCED_FRIENDS';

UPDATE Language_en_US
SET Text = 'We made a Declaration of Friendship and then denounced them!'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_FRIEND_DENOUNCED';

UPDATE Language_zh_CN
SET Text = '我们发表了友好宣言，然后谴责了他们！'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_FRIEND_DENOUNCED';

UPDATE Language_en_US
SET Text = 'You have declared war on leaders you''ve made Declarations of Friendship with!'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DECLARED_WAR_ON_FRIENDS';

UPDATE Language_zh_CN
SET Text = '你已经向与你发表友好宣言的领导人宣战了！'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_DECLARED_WAR_ON_FRIENDS';

UPDATE Language_en_US
SET Text = 'We made a Declaration of Friendship and then declared war on them!'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_FRIEND_DECLARED_WAR';

UPDATE Language_zh_CN
SET Text = '我们发表了友好宣言，然后向他们宣战！'
WHERE Tag = 'TXT_KEY_DIPLO_HUMAN_FRIEND_DECLARED_WAR';

-- Reckless Expander
UPDATE Language_en_US
SET Text = 'They believe we are expanding our empire too aggressively!'
WHERE Tag = 'TXT_KEY_DIPLO_RECKLESS_EXPANDER';

UPDATE Language_zh_CN
SET Text = '他们认为我们过于激进地扩张我们的帝国！'
WHERE Tag = 'TXT_KEY_DIPLO_RECKLESS_EXPANDER';

-- World Congress
UPDATE Language_en_US
SET Text = 'They liked our proposal to the World Congress.'
WHERE Tag = 'TXT_KEY_DIPLO_LIKED_OUR_PROPOSAL';

UPDATE Language_zh_CN
SET Text = '他们喜欢我们向世界大会提出的提案。'
WHERE Tag = 'TXT_KEY_DIPLO_LIKED_OUR_PROPOSAL';

UPDATE Language_en_US
SET Text = 'They disliked our proposal to the World Congress.'
WHERE Tag = 'TXT_KEY_DIPLO_DISLIKED_OUR_PROPOSAL';

UPDATE Language_zh_CN
SET Text = '他们不喜欢我们向世界大会提出的提案。'
WHERE Tag = 'TXT_KEY_DIPLO_DISLIKED_OUR_PROPOSAL';

UPDATE Language_en_US
SET Text = 'We passed their proposal in the World Congress.'
WHERE Tag = 'TXT_KEY_DIPLO_SUPPORTED_THEIR_PROPOSAL';

UPDATE Language_zh_CN
SET Text = '我们在世界大会上通过了他们的提案。'
WHERE Tag = 'TXT_KEY_DIPLO_SUPPORTED_THEIR_PROPOSAL';

UPDATE Language_en_US
SET Text = 'We defeated their proposal in the World Congress.'
WHERE Tag = 'TXT_KEY_DIPLO_FOILED_THEIR_PROPOSAL';

UPDATE Language_zh_CN
SET Text = '我们在世界大会上击败了他们的提议。'
WHERE Tag = 'TXT_KEY_DIPLO_FOILED_THEIR_PROPOSAL';

UPDATE Language_en_US
SET Text = 'We helped relocate the World Congress to their lands.'
WHERE Tag = 'TXT_KEY_DIPLO_SUPPORTED_THEIR_HOSTING';

UPDATE Language_zh_CN
SET Text = '我们帮助将世界大会迁至他们的土地。'
WHERE Tag = 'TXT_KEY_DIPLO_SUPPORTED_THEIR_HOSTING';

------------------------------------------------
-- City-State screen/tooltip
------------------------------------------------
UPDATE Language_en_US
SET Text = 'A befriended [COLOR_POSITIVE_TEXT]Militaristic[ENDCOLOR] City-State will provide you occasional gifts of advanced military units.[NEWLINE][NEWLINE]They know the secrets of the [COLOR_POSITIVE_TEXT]{@1_UniqueUnitName}[ENDCOLOR]. If you are their Ally and have researched [COLOR_CYAN]{@2_PrereqTech}[ENDCOLOR], they will provide that unit as their gift.'
WHERE Tag = 'TXT_KEY_CITY_STATE_MILITARISTIC_TT';

UPDATE Language_zh_CN
SET Text = '一个结交的[COLOR_POSITIVE_TEXT]军国主义[ENDCOLOR]城邦偶尔会为您提供先进军事单位的礼物。[NEWLINE][NEWLINE]他们知道的秘密[COLOR_POSITIVE_TEXT]{@1_UniqueUnitName}[ENDCOLOR]。如果你是他们的盟友并且已经研究过[COLOR_CYAN]{@2_PrereqTech}[ENDCOLOR]，他们将提供该单位作为礼物。'
WHERE Tag = 'TXT_KEY_CITY_STATE_MILITARISTIC_TT';

UPDATE Language_en_US
SET Text = '{1_CivName:textkey} {1_CivName: plural 1?is; other?are;} their current Ally. You need another {2_NumInfluence} [ICON_INFLUENCE] Influence to surpass {1_CivName:textkey} and become their Ally.[NEWLINE][NEWLINE]If a player becomes the Ally of a City-State, they receive extra bonuses relating to that City-State''s trait, and they will also receive any luxury and strategic Resources the City-State has connected.'
WHERE Tag = 'TXT_KEY_CITY_STATE_ALLY_TT';

UPDATE Language_zh_CN
SET Text = '{1_CivName:textkey} {1_CivName: plural 1?is; other?are;}他们现在的盟友。你需要另一个{2_NumInfluence} [ICON_INFLUENCE]影响力超越{1_CivName:textkey}并成为他们的盟友。[NEWLINE][NEWLINE]如果玩家成为某个城邦的盟友，他们将获得与该城邦特性相关的额外奖励，并且还将获得该城邦所连接的任何豪华和战略资源。'
WHERE Tag = 'TXT_KEY_CITY_STATE_ALLY_TT';

UPDATE Language_en_US
SET Text = 'Enslave {@1_Unit} - lose {2_NumInfluence} [ICON_INFLUENCE] Influence'
WHERE Tag = 'TXT_KEY_POPUP_MINOR_BULLY_UNIT_AMOUNT';

UPDATE Language_zh_CN
SET Text = '奴役{@1_Unit}- 失去{2_NumInfluence} [ICON_INFLUENCE]影响'
WHERE Tag = 'TXT_KEY_POPUP_MINOR_BULLY_UNIT_AMOUNT';

UPDATE Language_en_US
SET Text = 'If this City-State is more [COLOR_POSITIVE_TEXT]afraid[ENDCOLOR] of you than they are [COLOR_WARNING_TEXT]resilient[ENDCOLOR], you can demand one {@3_Unit} as tribute of at the cost of [ICON_INFLUENCE] Influence. {1_FearLevel}{2_FactorDetails}'
WHERE Tag = 'TXT_KEY_POP_CSTATE_BULLY_UNIT_TT';

UPDATE Language_zh_CN
SET Text = '如果这个城邦更[COLOR_POSITIVE_TEXT]害怕的[ENDCOLOR]你比他们[COLOR_WARNING_TEXT]有弹性的[ENDCOLOR]，你可以要求一个{@3_Unit}作为贡品，以牺牲[ICON_INFLUENCE]影响。{1_FearLevel}{2_FactorDetails}'
WHERE Tag = 'TXT_KEY_POP_CSTATE_BULLY_UNIT_TT';

UPDATE Language_en_US
SET Text = 'They want you to defeat Barbarian units that are invading their territory. You are allowed to enter their territory until the Barbarians are defeated.'
WHERE Tag = 'TXT_KEY_CITY_STATE_QUEST_INVADING_BARBS_FORMAL';

UPDATE Language_zh_CN
SET Text = '他们希望你击败入侵他们领土的野蛮人单位。你可以进入他们的领土，直到野蛮人被击败。'
WHERE Tag = 'TXT_KEY_CITY_STATE_QUEST_INVADING_BARBS_FORMAL';

UPDATE Language_en_US
SET Text = '{TXT_KEY_CITY_STATE_QUEST_CONTEST_TECHS_FORMAL} So far, you have the lead with [COLOR_POSITIVE_TEXT]{1_PlayerScore}[ENDCOLOR] {1_PlayerScore: plural 1?Technology; other?Technologies;}.'
WHERE Tag = 'TXT_KEY_CITY_STATE_QUEST_CONTEST_TECHS_WINNING_FORMAL';

UPDATE Language_zh_CN
SET Text = '{TXT_KEY_CITY_STATE_QUEST_CONTEST_TECHS_FORMAL}到目前为止，您领先于[COLOR_POSITIVE_TEXT]{1_PlayerScore}[ENDCOLOR] {1_PlayerScore: plural 1?Technology; other?Technologies;}.'
WHERE Tag = 'TXT_KEY_CITY_STATE_QUEST_CONTEST_TECHS_WINNING_FORMAL';

UPDATE Language_en_US
SET Text = '{TXT_KEY_CITY_STATE_QUEST_CONTEST_TECHS_FORMAL} So far, the leader has {1_LeaderScore} {1_LeaderScore: plural 1?Technology; other?Technologies;} and you have [COLOR_POSITIVE_TEXT]{2_PlayerScore}[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_CITY_STATE_QUEST_CONTEST_TECHS_LOSING_FORMAL';

UPDATE Language_zh_CN
SET Text = '{TXT_KEY_CITY_STATE_QUEST_CONTEST_TECHS_FORMAL}到目前为止，领导已经{1_LeaderScore} {1_LeaderScore: plural 1?Technology; other?Technologies;}你有[COLOR_POSITIVE_TEXT]{2_PlayerScore}[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_CITY_STATE_QUEST_CONTEST_TECHS_LOSING_FORMAL';

------------------------------------------------
-- Top panel
------------------------------------------------

-- Anarchy (Gold, Science, Culture, Faith)
UPDATE Language_en_US
SET Text = '[COLOR_NEGATIVE_TEXT]The empire is in Anarchy due to a change in Ideology for {1_Turns} more {1_Num: plural 1?turn; other?turns;}. During Anarchy, the empire will not gain any [ICON_RESEARCH] Science, [ICON_GOLD] Gold, [ICON_CULTURE] Culture, or [ICON_PEACE] Faith, and cities have no [ICON_PRODUCTION] Production to build anything[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_TP_ANARCHY';

UPDATE Language_zh_CN
SET Text = '[COLOR_NEGATIVE_TEXT]由于意识形态的变化，帝国将陷入 {1_Turns} {1_Num: plural 1?回合; other?回合;}的无政府状态。在无政府状态期间，帝国不会获得任何[ICON_RESEARCH]科研、[ICON_GOLD]金钱、[ICON_CULTURE]文化或[ICON_PEACE]信仰，且城市没有[ICON_PRODUCTION]产能来建造任何东西。[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_TP_ANARCHY';

-- Culture
UPDATE Language_en_US
SET Text = 'Next Policy: {1_Num} {1_Num: plural 1?Turn; other?Turns;}'
WHERE Tag = 'TXT_KEY_NEXT_POLICY_TURN_LABEL';

UPDATE Language_zh_CN
SET Text = '下一个政策：{1_Num} {1_Num: plural 1?回合; other?回合;}'
WHERE Tag = 'TXT_KEY_NEXT_POLICY_TURN_LABEL';

-- Faith
UPDATE Language_en_US
SET Text = '{1_Num} [ICON_PEACE] Faith is the minimum required to found the next religious Pantheon. If you wish to found a Pantheon, you must do it before there is an Enhanced Religion in the game (though you may always form one if there have not been as many Pantheons as the maximum number of Religions).'
WHERE Tag = 'TXT_KEY_TP_FAITH_NEXT_PANTHEON';

UPDATE Language_zh_CN
SET Text = '{1_Num} [ICON_PEACE]信仰是建立下一个宗教万神殿所需的最低限度。如果你想建立万神殿，你必须在游戏中出现增强宗教之前完成（尽管如果万神殿数量没有达到宗教最大数量，你总是可以建立一个万神殿）。'
WHERE Tag = 'TXT_KEY_TP_FAITH_NEXT_PANTHEON';

UPDATE Language_en_US
SET Text = '{1_Num} [ICON_PEACE] Faith is the minimum required for your next chance at a Great Prophet.'
WHERE Tag = 'TXT_KEY_TP_FAITH_NEXT_PROPHET';

UPDATE Language_zh_CN
SET Text = '{1_Num} [ICON_PEACE]信仰是你下次有机会成为伟大先知所需的最低限度。'
WHERE Tag = 'TXT_KEY_TP_FAITH_NEXT_PROPHET';

-- Gold
UPDATE Language_en_US
SET Text = '[ICON_GOLD][COLOR:255:235:0:255]{1_TotalGold: number "#,###"} {2_GoldPerTurn: number "''(+''#,###'')'';''[COLOR:255:60:60:255](-''#,###'')''"}[/COLOR]'
WHERE Tag = 'TXT_KEY_TOP_PANEL_GOLD';

UPDATE Language_zh_CN
SET Text = '[ICON_GOLD][COLOR:255:235:0:255]{1_TotalGold: number "#,###"} {2_GoldPerTurn: number "''(+''#,###'')'';''[COLOR:255:60:60:255](-''#,###'')''"}[/COLOR]'
WHERE Tag = 'TXT_KEY_TOP_PANEL_GOLD';

-- Golden Age
UPDATE Language_en_US
SET Text = '{1_NumCurrent}/{2_NumNeeded} progress towards the next [ICON_GOLDEN_AGE] Golden Age.'
WHERE Tag = 'TXT_KEY_TP_GOLDEN_AGE_PROGRESS';

UPDATE Language_zh_CN
SET Text = '{1_NumCurrent}/{2_NumNeeded}下一步的进展[ICON_GOLDEN_AGE]黄金时代。'
WHERE Tag = 'TXT_KEY_TP_GOLDEN_AGE_PROGRESS';

-- Tourism
UPDATE Language_en_US
SET Text = '{1_Num} [ICON_GREAT_WORK] {1_Num: plural 1?Great Work Slot; other?Great Work Slots;} Filled'
WHERE Tag = 'TXT_KEY_TOP_PANEL_TOURISM_TOOLTIP_1';

UPDATE Language_zh_CN
SET Text = '{1_Num} [ICON_GREAT_WORK] {1_Num: plural 1?杰作槽位; other?杰作槽位;}已填充'
WHERE Tag = 'TXT_KEY_TOP_PANEL_TOURISM_TOOLTIP_1';

UPDATE Language_en_US
SET Text = '{1_Num} [ICON_GREAT_WORK] {1_Num: plural 1?Great Work Slot; other?Great Work Slots;} Available'
WHERE Tag = 'TXT_KEY_TOP_PANEL_TOURISM_TOOLTIP_2';

UPDATE Language_zh_CN
SET Text = '{1_Num} [ICON_GREAT_WORK] {1_Num: plural 1?杰作槽位; other?杰作槽位;}可用'
WHERE Tag = 'TXT_KEY_TOP_PANEL_TOURISM_TOOLTIP_2';


-- Trade routes
UPDATE Language_en_US
SET Text = 'You have {1_TradeRoutesUsedNum} {1_TradeRoutesUsedNum: plural 1?Trade Unit; other?Trade Units;}.[NEWLINE]You have {2_TradeRoutesAvailableNum} {2_TradeRoutesAvailableNum: plural 1?Trade Route; other?Trade Routes;} available.'
WHERE Tag = 'TXT_KEY_TOP_PANEL_INTERNATIONAL_TRADE_ROUTES_TT';

UPDATE Language_zh_CN
SET Text = '你有 {1_TradeRoutesUsedNum} {1_TradeRoutesUsedNum: plural 1?商路单位; other?商路单位;}。[NEWLINE]你有 {2_TradeRoutesAvailableNum} {2_TradeRoutesAvailableNum: plural 1?商路; other?商路;} 可用。'
WHERE Tag = 'TXT_KEY_TOP_PANEL_INTERNATIONAL_TRADE_ROUTES_TT';

UPDATE Language_en_US
SET Text = 'You have {1_Num} unassigned {2_UnitName}{1_Num: plural 1?; other?s;}.[NEWLINE]'
WHERE Tag = 'TXT_KEY_TOP_PANEL_INTERNATIONAL_TRADE_ROUTES_TT_UNASSIGNED';

UPDATE Language_zh_CN
SET Text = '你有{1_Num}未分配的{2_UnitName}{1_Num: plural 1?; other?s;}.[NEWLINE]'
WHERE Tag = 'TXT_KEY_TOP_PANEL_INTERNATIONAL_TRADE_ROUTES_TT_UNASSIGNED';

------------------------------------------------
-- Demographics
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Deployable Troops'
WHERE Tag = 'TXT_KEY_DEMOGRAPHICS_ARMY_MEASURE';

UPDATE Language_zh_CN
SET Text = '可部署部队'
WHERE Tag = 'TXT_KEY_DEMOGRAPHICS_ARMY_MEASURE';

------------------------------------------------
-- Espionage overview
------------------------------------------------
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Chance to kill enemy spies: {1_Num}%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_EO_SPY_COUNTER_INTEL_SUM_TT';

UPDATE Language_zh_CN
SET Text = '[COLOR_POSITIVE_TEXT]有几率杀死敌方间谍：{1_Num}%[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_EO_SPY_COUNTER_INTEL_SUM_TT';

UPDATE Language_en_US
SET Text = '{1_RankName} {2_SpyName} is attempting to rig the election in {3_CityName} to increase our influence there.[NEWLINE][NEWLINE]Only one civilization may successfuly rig an election. If more than one spy is in a City-State, the highest ranked spy that has been in that City-State the longest has the greatest chance of successfully rigging the election in its favor. Successfully rigging elections also increases the success chance of a coup in the City-State.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]If you successfully rig the next election, your influence will increase by {4_Influence}.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_EO_SPY_RIGGING_ELECTIONS_TT';

UPDATE Language_zh_CN
SET Text = '{1_RankName} {2_SpyName}试图操纵选举{3_CityName}增加我们在那里的影响力。[NEWLINE][NEWLINE]只有一个文明可以成功操纵选举。如果一个城邦中有不止一名间谍，那么在该城邦任职时间最长、级别最高的间谍最有可能成功操纵选举，使其对自己有利。成功操纵选举也增加了城邦政变成功的机会。[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]如果您成功操纵下一次选举，您的影响力将增加{4_Influence}.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_EO_SPY_RIGGING_ELECTIONS_TT';

UPDATE Language_en_US
SET Text = 'All city-states around the world hold elections simultaneously every {1_Num} Turns. The next election will be in {2_Num} {2_Num: plural 1?Turn; other?Turns;}.'
WHERE Tag = 'TXT_KEY_EO_CITY_STATE_ELECTION';

UPDATE Language_zh_CN
SET Text = '世界上所有城邦每年同时举行选举{1_Num}轮流。下次选举将在{2_Num} {2_Num: plural 1?Turn; other?Turns;}.'
WHERE Tag = 'TXT_KEY_EO_CITY_STATE_ELECTION';

------------------------------------------------
-- Religion overview
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Head of {1_ReligionName}'
WHERE Tag = 'TXT_KEY_RO_STATUS_FOUNDER';

UPDATE Language_zh_CN
SET Text = '组长{1_ReligionName}'
WHERE Tag = 'TXT_KEY_RO_STATUS_FOUNDER';

------------------------------------------------
-- Cultural overview
------------------------------------------------

-- CV progress screen
UPDATE Language_en_US
SET Text = '+{1_Num}% Bonus from Trade Route between Empires[NEWLINE]'
WHERE Tag = 'TXT_KEY_CO_PLAYER_TOURISM_TRADE_ROUTE';

UPDATE Language_zh_CN
SET Text = '+{1_Num}帝国之间贸易路线的%奖励[NEWLINE]'
WHERE Tag = 'TXT_KEY_CO_PLAYER_TOURISM_TRADE_ROUTE';

UPDATE Language_en_US
SET Text = 'Influential in {1_Num} {1_Num: plural 1?Turn; other?Turns;} (assuming Tourism output remains unchanged)'
WHERE Tag = 'TXT_KEY_CO_INFLUENTIAL_TURNS_TT';

UPDATE Language_zh_CN
SET Text = '有影响力{1_Num} {1_Num: plural 1?Turn; other?Turns;}（假设旅游产出保持不变）'
WHERE Tag = 'TXT_KEY_CO_INFLUENTIAL_TURNS_TT';

------------------------------------------------
-- Deal overview
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Ends after:[NEWLINE]Turn {1_turn}'
WHERE Tag = 'TXT_KEY_DO_ENDS_ON';

UPDATE Language_zh_CN
SET Text = '结束于：[NEWLINE]转动{1_turn}'
WHERE Tag = 'TXT_KEY_DO_ENDS_ON';

------------------------------------------------
-- Trade Route picker
------------------------------------------------
UPDATE Language_en_US
SET Text = 'You have discovered {1_Num} {1_Num: plural 1?Technology; other?Technologies;} that {2_CivName} {2_CivName: plural 1?does; other?do;} not know.[NEWLINE]They are receiving +{3_Num} [ICON_RESEARCH] Science on this route due to their Cultural Influence over you.'
WHERE Tag = 'TXT_KEY_CHOOSE_INTERNATIONAL_TRADE_ROUTE_ITEM_TT_THEIR_SCIENCE_EXPLAINED';

UPDATE Language_zh_CN
SET Text = '你已经发现了{1_Num} {1_Num: plural 1?Technology; other?Technologies;}那{2_CivName} {2_CivName: plural 1?does; other?do;}不知道。[NEWLINE]他们正在接收+{3_Num} [ICON_RESEARCH]这条路线上的科学是由于它们对你的文化影响。'
WHERE Tag = 'TXT_KEY_CHOOSE_INTERNATIONAL_TRADE_ROUTE_ITEM_TT_THEIR_SCIENCE_EXPLAINED';

UPDATE Language_en_US
SET Text = '{1_CivName} {1_CivName: plural 1?has; other?have;} discovered {2_Num} {2_Num: plural 1?Technology; other?Technologies;} that you do not know.[NEWLINE]You are receiving +{3_Num} [ICON_RESEARCH] Science on this route due to your Cultural Influence over them.'
WHERE Tag = 'TXT_KEY_CHOOSE_INTERNATIONAL_TRADE_ROUTE_ITEM_TT_YOUR_SCIENCE_EXPLAINED';

UPDATE Language_zh_CN
SET Text = '{1_CivName} {1_CivName: plural 1?has; other?have;}发现了{2_Num} {2_Num: plural 1?Technology; other?Technologies;}你不知道。[NEWLINE]您正在接收+{3_Num} [ICON_RESEARCH]由于您对他们的文化影响，这条路线上的科学。'
WHERE Tag = 'TXT_KEY_CHOOSE_INTERNATIONAL_TRADE_ROUTE_ITEM_TT_YOUR_SCIENCE_EXPLAINED';

------------------------------------------------
-- World Congress screen
------------------------------------------------
UPDATE Language_en_US
SET Text = '[NEWLINE][ICON_BULLET]{1_NumVotes} from Wonders'
WHERE Tag = 'TXT_KEY_LEAGUE_OVERVIEW_MEMBER_DETAILS_WONDER_VOTES';

UPDATE Language_zh_CN
SET Text = '[NEWLINE][ICON_BULLET]{1_NumVotes}来自奇迹'
WHERE Tag = 'TXT_KEY_LEAGUE_OVERVIEW_MEMBER_DETAILS_WONDER_VOTES';

UPDATE Language_en_US
SET Text = '[NEWLINE][NEWLINE]Our knowledge of other Civs'' desires:'
WHERE Tag = 'TXT_KEY_LEAGUE_OVERVIEW_VOTE_OPINIONS';

UPDATE Language_zh_CN
SET Text = '[NEWLINE][NEWLINE]我们对其他文明愿望的了解：'
WHERE Tag = 'TXT_KEY_LEAGUE_OVERVIEW_VOTE_OPINIONS';

UPDATE Language_en_US
SET Text = '[NEWLINE][NEWLINE]Civilizations positively affected by this:'
WHERE Tag = 'TXT_KEY_LEAGUE_OVERVIEW_PROPOSAL_OPINIONS_POSITIVE';

UPDATE Language_zh_CN
SET Text = '[NEWLINE][NEWLINE]受此积极影响的文明：'
WHERE Tag = 'TXT_KEY_LEAGUE_OVERVIEW_PROPOSAL_OPINIONS_POSITIVE';

UPDATE Language_en_US
SET Text = '[NEWLINE][NEWLINE]Civilizations negatively affected by this:'
WHERE Tag = 'TXT_KEY_LEAGUE_OVERVIEW_PROPOSAL_OPINIONS_NEGATIVE';

UPDATE Language_zh_CN
SET Text = '[NEWLINE][NEWLINE]受此负面影响的文明：'
WHERE Tag = 'TXT_KEY_LEAGUE_OVERVIEW_PROPOSAL_OPINIONS_NEGATIVE';

------------------------------------------------
-- Leader screen
------------------------------------------------
UPDATE Language_en_US
SET Text = 'You cannot negotiate peace with this player for another {1_Num} {1_Num: plural 1?turn; other?turns;} because of a deal you made with another player.'
WHERE Tag = 'TXT_KEY_DIPLO_NEGOTIATE_PEACE_BLOCKED_TT';

UPDATE Language_zh_CN
SET Text = '您无法与该玩家和平谈判以换取另一玩家{1_Num} {1_Num: plural 1?turn; other?turns;}因为您与其他玩家达成的交易。'
WHERE Tag = 'TXT_KEY_DIPLO_NEGOTIATE_PEACE_BLOCKED_TT';

------------------------------------------------
-- Trade screen
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Unlocks advanced trade options with this Civilization and reveals the location of their Capital.'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_TT';

UPDATE Language_zh_CN
SET Text = '解锁该文明的高级贸易选项并揭示其首都的位置。'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_TT';

UPDATE Language_en_US
SET Text = 'Allows the other player''s military or civilian Units to pass through one''s territory (lasts {1_Num} turns).[NEWLINE][NEWLINE]Note: Military Units belonging to different players may never stack.'
WHERE Tag = 'TXT_KEY_DIPLO_OPEN_BORDERS_TT';

UPDATE Language_zh_CN
SET Text = '允许其他玩家的军事或民事单位通过自己的领土（持续{1_Num}轮）。[NEWLINE][NEWLINE]注意：属于不同玩家的军事单位可能永远不会叠加。'
WHERE Tag = 'TXT_KEY_DIPLO_OPEN_BORDERS_TT';

UPDATE Language_en_US
SET Text = 'If either player is attacked by another major civilization, the other player will immediately and automatically go to war with the aggressor. This agreement lasts {1_Num} turns.[NEWLINE][NEWLINE]You can make Defensive Pacts with a maximum of [COLOR_CYAN]{2_Num}[ENDCOLOR] civs. This is based on the number of living, non-vassal civs in the world.'
WHERE Tag = 'TXT_KEY_DIPLO_DEF_PACT_TT';

UPDATE Language_zh_CN
SET Text = '如果任一玩家受到另一个主要文明的攻击，另一玩家将立即自动与侵略者开战。本协议持续有效{1_Num}轮流。[NEWLINE][NEWLINE]您最多可以签订防御契约[COLOR_CYAN]{2_Num}[ENDCOLOR]公民。这是基于世界上存活的非附庸文明的数量。'
WHERE Tag = 'TXT_KEY_DIPLO_DEF_PACT_TT';

UPDATE Language_en_US
SET Text = 'We already have an Embassy in their Capital!'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_HAVE';

UPDATE Language_zh_CN
SET Text = '我们已经在他们的首都设立了大使馆！'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_HAVE';

UPDATE Language_en_US
SET Text = 'They already have an Embassy in our Capital!'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_THEY_HAVE';

UPDATE Language_zh_CN
SET Text = '他们已经在我们首都设有大使馆了！'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_THEY_HAVE';

UPDATE Language_en_US
SET Text = 'You do not have the Technology to establish an Embassy (Writing).'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_NO_TECH_PLAYER';

UPDATE Language_zh_CN
SET Text = '您没有建立大使馆的技术（书面）。'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_NO_TECH_PLAYER';

UPDATE Language_en_US
SET Text = 'They do not have the Technology to establish an Embassy (Writing).'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_NO_TECH_OTHER_PLAYER';

UPDATE Language_zh_CN
SET Text = '他们没有建立大使馆的技术（文字）。'
WHERE Tag = 'TXT_KEY_DIPLO_ALLOW_EMBASSY_NO_TECH_OTHER_PLAYER';

UPDATE Language_en_US
SET Text = 'We are already allowing Open Borders!'
WHERE Tag = 'TXT_KEY_DIPLO_OPEN_BORDERS_HAVE';

UPDATE Language_zh_CN
SET Text = '我们已经允许开放边界！'
WHERE Tag = 'TXT_KEY_DIPLO_OPEN_BORDERS_HAVE';

UPDATE Language_en_US
SET Text = 'They are already allowing Open Borders!'
WHERE Tag = 'TXT_KEY_DIPLO_OPEN_BORDERS_THEY_HAVE';

UPDATE Language_zh_CN
SET Text = '他们已经允许开放边界了！'
WHERE Tag = 'TXT_KEY_DIPLO_OPEN_BORDERS_THEY_HAVE';

UPDATE Language_en_US
SET Text = 'Neither player yet has the Technology to trade this item (Civil Service).'
WHERE Tag = 'TXT_KEY_DIPLO_OPEN_BORDERS_NO_TECH';

UPDATE Language_zh_CN
SET Text = '两个玩家都还没有交易该物品的技术（公务员）。'
WHERE Tag = 'TXT_KEY_DIPLO_OPEN_BORDERS_NO_TECH';

UPDATE Language_en_US
SET Text = 'You need an Embassy with their Civilization to trade this item.'
WHERE Tag = 'TXT_KEY_DIPLO_YOU_NEED_EMBASSY_TT';

UPDATE Language_zh_CN
SET Text = '您需要一个拥有其文明的大使馆才能交易该物品。'
WHERE Tag = 'TXT_KEY_DIPLO_YOU_NEED_EMBASSY_TT';

UPDATE Language_en_US
SET Text = 'They need an Embassy with your Civilization to trade this item.'
WHERE Tag = 'TXT_KEY_DIPLO_THEY_NEED_EMBASSY_TT';

UPDATE Language_zh_CN
SET Text = '他们需要一个与你们文明有联系的大使馆来交易这个物品。'
WHERE Tag = 'TXT_KEY_DIPLO_THEY_NEED_EMBASSY_TT';

UPDATE Language_en_US
SET Text = 'Both parties need an Embassy to trade this item.'
WHERE Tag = 'TXT_KEY_DIPLO_BOTH_NEED_EMBASSY_TT';

UPDATE Language_zh_CN
SET Text = '双方都需要一个大使馆来交易该物品。'
WHERE Tag = 'TXT_KEY_DIPLO_BOTH_NEED_EMBASSY_TT';

UPDATE Language_en_US
SET Text = 'We already have a Defensive Pact!'
WHERE Tag = 'TXT_KEY_DIPLO_DEF_PACT_EXISTS';

UPDATE Language_zh_CN
SET Text = '我们已经有防御协议了！'
WHERE Tag = 'TXT_KEY_DIPLO_DEF_PACT_EXISTS';

UPDATE Language_en_US
SET Text = 'Neither player yet has the Technology to trade this item (Chivalry).'
WHERE Tag = 'TXT_KEY_DIPLO_DEF_PACT_NO_TECH';

UPDATE Language_zh_CN
SET Text = '两名玩家都还没有交易该物品（骑士精神）的技术。'
WHERE Tag = 'TXT_KEY_DIPLO_DEF_PACT_NO_TECH';

UPDATE Language_en_US
SET Text = 'We already have a Research Agreement!'
WHERE Tag = 'TXT_KEY_DIPLO_RESCH_AGREEMENT_EXISTS';

UPDATE Language_zh_CN
SET Text = '我们已经签订了研究协议！'
WHERE Tag = 'TXT_KEY_DIPLO_RESCH_AGREEMENT_EXISTS';

UPDATE Language_en_US
SET Text = 'One or both of us have already researched all Technologies.'
WHERE Tag = 'TXT_KEY_DIPLO_RESCH_AGREEMENT_ALL_TECHS_RESEARCHED';

UPDATE Language_zh_CN
SET Text = '我们一个或两个人已经研究了所有技术。'
WHERE Tag = 'TXT_KEY_DIPLO_RESCH_AGREEMENT_ALL_TECHS_RESEARCHED';

UPDATE Language_en_US
SET Text = 'Neither player yet has the Technology to trade this item (Philosophy).'
WHERE Tag = 'TXT_KEY_DIPLO_RESCH_AGREEMENT_NO_TECH';

UPDATE Language_zh_CN
SET Text = '两个玩家都还没有交易该物品的技术（哲学）。'
WHERE Tag = 'TXT_KEY_DIPLO_RESCH_AGREEMENT_NO_TECH';

UPDATE Language_en_US
SET Text = 'A Declaration of Friendship is needed to trade this item.'
WHERE Tag = 'TXT_KEY_DIPLO_NEED_DOF_TT';

UPDATE Language_zh_CN
SET Text = '交易该物品需要友谊宣言。'
WHERE Tag = 'TXT_KEY_DIPLO_NEED_DOF_TT';

UPDATE Language_en_US
SET Text = 'A City-State Alliance prevents this action.'
WHERE Tag = 'TXT_KEY_DIPLO_MINOR_ALLY_AT_WAR';

UPDATE Language_zh_CN
SET Text = '城邦联盟阻止了这一行动。'
WHERE Tag = 'TXT_KEY_DIPLO_MINOR_ALLY_AT_WAR';

UPDATE Language_en_US
SET Text = 'A City-State Alliance prevents this action.'
WHERE Tag = 'TXT_KEY_DIPLO_NO_WAR_ALLIES';

UPDATE Language_zh_CN
SET Text = '城邦联盟阻止了这一行动。'
WHERE Tag = 'TXT_KEY_DIPLO_NO_WAR_ALLIES';

UPDATE Language_en_US
SET Text = 'A recent Peace Treaty prevents this action.'
WHERE Tag = 'TXT_KEY_DIPLO_FORCE_PEACE';

UPDATE Language_zh_CN
SET Text = '最近的和平条约阻止了这一行动。'
WHERE Tag = 'TXT_KEY_DIPLO_FORCE_PEACE';

UPDATE Language_en_US
SET Text = 'We have no tradeable cities and/or we do not have an Embassy with them.'
WHERE Tag = 'TXT_KEY_DIPLO_TO_TRADE_CITY_NO_TT';

UPDATE Language_zh_CN
SET Text = '我们没有可交易的城市和/或我们在这些城​​市没有大使馆。'
WHERE Tag = 'TXT_KEY_DIPLO_TO_TRADE_CITY_NO_TT';

UPDATE Language_en_US
SET Text = 'They have no tradeable cities and/or they do not have an Embassy with us.'
WHERE Tag = 'TXT_KEY_DIPLO_TO_TRADE_CITY_NO_THEM';

UPDATE Language_zh_CN
SET Text = '他们没有可交易的城市和/或他们在我们这里没有大使馆。'
WHERE Tag = 'TXT_KEY_DIPLO_TO_TRADE_CITY_NO_THEM';

------------------------------------------------
-- Discussion/Dialogue options
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Our Declaration of Friendship must end.'
WHERE Tag = 'TXT_KEY_DIPLO_DISCUSS_MESSAGE_END_WORK_WITH_US';

UPDATE Language_zh_CN
SET Text = '我们的友谊宣言必须结束。'
WHERE Tag = 'TXT_KEY_DIPLO_DISCUSS_MESSAGE_END_WORK_WITH_US';

UPDATE Language_en_US
SET Text = 'Impossible. You go too far.'
WHERE Tag = 'TXT_KEY_DIPLO_DISCUSS_HOW_DARE_YOU';

UPDATE Language_zh_CN
SET Text = '不可能的。你走得太远了。'
WHERE Tag = 'TXT_KEY_DIPLO_DISCUSS_HOW_DARE_YOU';

------------------------------------------------
-- Banner message
------------------------------------------------
UPDATE Language_en_US
SET Text = 'Your Merchant of Venice bought a City-State!'
WHERE Tag = 'TXT_KEY_VENETIAN_MERCHANT_BOUGHT_CITY_STATE';

UPDATE Language_zh_CN
SET Text = '你的威尼斯商人买了一个城邦！'
WHERE Tag = 'TXT_KEY_VENETIAN_MERCHANT_BOUGHT_CITY_STATE';
