-- Change Kiev to Kyiv to reflect the Ukrainian-derived spelling, in keeping with the game's emphasis on City-States as distinct cultural entities
UPDATE Language_en_US
SET Text = 'Kyiv'
WHERE Tag = 'TXT_KEY_CITYSTATE_KIEV';

UPDATE Language_zh_CN
SET Text = '基辅'
WHERE Tag = 'TXT_KEY_CITYSTATE_KIEV';

UPDATE Language_en_US
SET Text = 'Kyivan'
WHERE Tag = 'TXT_KEY_CITYSTATE_KIEV_ADJ';

UPDATE Language_zh_CN
SET Text = '基辅'
WHERE Tag = 'TXT_KEY_CITYSTATE_KIEV_ADJ';

UPDATE Language_en_US
SET Text = 'According to legend, Kyiv was founded by three Slavic brothers - Kyi, Schek, and Khoryv - around the beginning of the 6th Century AD. Since then, Kyiv, one of the oldest cities in Eastern Europe, has passed through times of great prominence and periods of relative obscurity. Throughout the centuries, however, it has remained the most important Slavic cultural center, playing a pivotal role in the development of the medieval East Slavic civilization.[NEWLINE][NEWLINE]Located on the Dnieper trade route between Constantinople and Scandinavia, Kyiv came under the control of local Varangian (Viking) nobility and became the nucleus of the state of Rus. During the 1000s, it reached its ascendancy, a cultural hub with over 400 churches, eight markets, docks and a caravansary, and magnificent homes. With the founding of the Kyiv-Mogilyanskaya Academy in 1632, the city became the center of Ukrainian learning and scholarship. But as the capital of Kyivan Rus, the city was repeatedly sacked and occupied.[NEWLINE][NEWLINE]In 1667 the city became part of the Russian Empire; Kyiv remained an ecclesiastical and cultural center, but its political and economic influence was marginalized. Kyiv experienced growing "Russification" in the 1800s, as a result of Russian migration, educational policies, and industrialization. However, enthusiasts among ethnic Ukrainian nobles, military officers and merchants kept the native culture alive in Kyiv, often through clandestine activities such as book-printing, amateur theater, private soirees, folk festivals and the like.[NEWLINE][NEWLINE]Forcefully incorporated into the Soviet Union, the city weathered all manner of troubles: the famine of 1932-1933 devastated the lower classes, Stalin''s 1937-1938 purges almost obliterated the city''s intelligensia, and the 1941-1943 Nazi invasion brought death and destruction. But Kyiv survived, and in the wake of the collapse of the Soviet Union an independent Ukraine was proclaimed in 1991, with resurgent Kyiv as its capital and cultural heart.'
WHERE Tag = 'TXT_KEY_CIV5_KIEV_TEXT';

UPDATE Language_zh_CN
SET Text = '据传说，基辅是由斯拉夫三兄弟——基伊、谢克和霍里夫——大约于公元六世纪初建立的。从那时起，基辅这个东欧最古老的城市之一经历了鼎盛时期和相对默默无闻的时期。然而几个世纪以来，它仍然是最重要的斯拉夫文化中心，在中世纪东斯拉夫文明的发展中发挥着举足轻重的作用。[NEWLINE][NEWLINE]基辅位于君士坦丁堡和斯堪的纳维亚半岛之间的第聂伯河贸易路线上，受到当地瓦兰吉（维京）贵族的控制，成为罗斯国家的核心。在 1000 年代，它达到了鼎盛时期，成为一个文化中心，拥有 400 多座教堂、八个市场、码头和一个商队，以及宏伟的住宅。随着 1632 年基辅莫吉良斯卡亚学院的成立，这座城市成为乌克兰的学习和学术中心。但作为基辅罗斯的首都，这座城市多次被洗劫和占领。[NEWLINE][NEWLINE]1667年，这座城市成为俄罗斯帝国的一部分；基辅仍然是一个教会和文化中心，但其政治和经济影响力被边缘化。由于俄罗斯移民、教育政策和工业化，基辅在 1800 年代经历了日益增长的“俄罗斯化”。然而，乌克兰族贵族、军官和商人的热衷者常常通过书籍印刷、业余戏剧、私人晚会、民间节日等秘密活动，使基辅的本土文化保持活力。[NEWLINE][NEWLINE]这座城市被强行并入苏联，经历了各种各样的麻烦：1932-1933年的饥荒摧毁了下层阶级，斯大林1937-1938年的清洗几乎消灭了这座城市的知识分子，1941-1943年纳粹的入侵带来了死亡和破坏。但基辅幸存下来，苏联解体后，乌克兰于 1991 年宣布独立，并以复兴的基辅为首都和文化中心。'
WHERE Tag = 'TXT_KEY_CIV5_KIEV_TEXT';

-- Update Hong Kong's Civilopedia entry to reflect increased Chinese control in 2020 onwards
UPDATE Language_en_US
SET Text = 'A city-state in its truest form, Hong Kong is a massive city residing along the southern coast of China. Home to more than seven million residents in the present-day, the island of Hong Kong and its surrounding territories were once home to numerous small settlements, including those constructed by foreign explorers. During the reign of the Chinese Qing Dynasty in the 19th century, trade relations with England dissolved amidst growing concern over the importation of Indian Opium into China. Britain had hoped to offset its increasing expensive tea imports from China by exporting greater amounts of Opium from its Indian colonies to China. However, the Qing rulers objected, and attempted to seize incoming opium shipments, inciting the First Opium War in 1839.[NEWLINE][NEWLINE]As one of the premier naval powers of the era, Britain had little trouble defeating the Chinese forces and occupying the island of Hong Kong. After nearly 3 years of conflict, the signing of the Treaty of Nanking in 1842 provided Britain with various spoils, including control of Hong Kong. After growing as a British colony for more than 150 years, Hong Kong was finally returned to China in 1997, after a peaceful transfer of power led to the creation of the Hong Kong Special Administrative Region. For years, Hong Kong maintained a high degree of autonomy under the "one country, two systems" framework, supporting a separate legal and economic system rooted in free trade. However, in the early 21st century, Beijing asserted greater control over the region, prompting political changes and widespread international concern over the erosion of Hong Kong''s autonomy. Despite these shifts, Hong Kong remains a global financial center, distinguished by its highly dense urban landscape, distinctive skyline, and vibrant cultural identity.'
WHERE Tag = 'TXT_KEY_CIV5_HONG_KONG_TEXT';

UPDATE Language_zh_CN
SET Text = '香港是一个最真实的城邦国家，是一座位于中国南部沿海的大城市。香港岛及其周边地区如今拥有超过 700 万居民，曾经是众多小型定居点的所在地，其中包括由外国探险家建造的定居点。十九世纪中国清朝统治期间，由于对印度鸦片输入中国的担忧日益增加，与英国的贸易关系破裂。英国曾希望通过从印度殖民地向中国出口更多鸦片来抵消从中国进口的日益昂贵的茶叶。然而，清朝统治者表示反对，并试图扣押进口的鸦片，从而引发了 1839 年的第一次鸦片战争。[NEWLINE][NEWLINE]作为那个时代最主要的海军强国之一，英国毫不费力地击败了中国军队并占领了香港岛。经过近三年的冲突，1842年《南京条约》的签署为英国提供了各种战利品，其中包括对香港的控制权。在作为英国殖民地发展了 150 多年后，香港终于在 1997 年回归中国，并通过和平移交权力建立了香港特别行政区。多年来，香港在“一国两制”框架下保持高度自治，支持以自由贸易为基础的独立法律和经济体系。然而，在21世纪初，北京声称对该地区拥有更大的控制权，引发了政治变革，并引起国际社会对香港自治权受到侵蚀的广泛担忧。尽管发生了这些变化，香港仍然是一个全球金融中心，以其高度密集的城市景观、独特的天际线和充满活力的文化特征而著称。'
WHERE Tag = 'TXT_KEY_CIV5_HONG_KONG_TEXT';

-- Update Singapore's Civilopedia entry to note that it's now the fourth wealthiest country by GDP per capita, not the fifth
UPDATE Language_en_US
SET Text = 'Records and archeological excavations show that the island of modern-day Singapore has been occupied from about the second century AD - the small island was originally part of the Sumatran Empire and went by the name of Temasek, or "sea town." For unknown reasons the area slid into a decline in the 14th century, and for the next few centuries the island''s population consisted mostly of small villages of fishermen.[NEWLINE][NEWLINE]This all changed on January 29, 1819, when the British statesman Sir Thomas Stamford Raffles landed on the island and signed a treaty to develop the southern portion into a British trading post. Singapore officially became a British colony in 1824 when the British East India Company gained control of the entire island. The island city grew steadily as it became an important hub for trade and commerce in the Pacific.[NEWLINE][NEWLINE]In 1941, the Japanese invaded Singapore and in six short days gained control of the city and its military base. The Battle of Singapore, as it came to be known, was the worst recorded military disaster in British history and the city became an important base for the Japanese for the rest of World War II. The British regained control of the island a month after Japan''s surrender in 1945.[NEWLINE][NEWLINE]After the war, Singapore started on the road to independence. In 1955 the city was allowed to hold its first general election, but delegations sent to England demanding self-rule were met with resistance until 1959. Four years later the small city-state nation declared formal independence from the British Empire and quickly joined the Federation of Malaysia. However, major ideological conflicts between Singapore and the Federation soured the relationship and two years later Singapore officially declared complete sovereignty.[NEWLINE][NEWLINE]Since its independence, fortunes for the city-state have increased, with massive improvements in standards of living, the economy, and education. Singapore is now the fourth wealthiest country in the world (in terms of GDP per capita) with booming tourism and medical industries.'
WHERE Tag = 'TXT_KEY_CIV5_SINGAPORE_TEXT';

UPDATE Language_zh_CN
SET Text = '记录和考古发掘表明，现代新加坡岛大约从公元二世纪起就被占领了——这个小岛最初是苏门答腊帝国的一部分，被称为淡马锡，或“海上城镇”。由于未知的原因，该地区在 14 世纪陷入衰退，在接下来的几个世纪里，岛上的人口主要由渔民组成的小村庄组成。[NEWLINE][NEWLINE]1819 年 1 月 29 日，这一切都发生了变化，当时英国政治家托马斯·斯坦福·莱佛士爵士登陆该岛，并签署了一项条约，将南部地区开发为英国贸易站。 1824 年，英国东印度公司控制了整个岛屿，新加坡正式成为英国殖民地。这座岛城稳步发展，成为太平洋地区重要的贸易和商业中心。[NEWLINE][NEWLINE]1941 年，日本入侵新加坡，并在短短六天内控制了这座城市及其军事基地。新加坡之战是英国历史上最严重的军事灾难，这座城市成为日本在第二次世界大战余下时间里的重要基地。 1945 年日本投降一个月后，英国重新控制了该岛。[NEWLINE][NEWLINE]战后，新加坡开始走上独立之路。 1955年，这座城市被允许举行第一次大选，但派往英国要求自治的代表团一直遭到抵制，直到1959年。四年后，这个小城邦国家宣布正式脱离大英帝国独立，并迅速加入马来西亚联邦。然而，新加坡与联邦之间的重大意识形态冲突恶化了两国关系，两年后新加坡正式宣布拥有完全主权。[NEWLINE][NEWLINE]自独立以来，这个城邦的财富不断增加，生活水平、经济和教育水平大幅提高。新加坡现在是世界第四富有的国家（以人均国内生产总值计算），旅游业和医疗业蓬勃发展。'
WHERE Tag = 'TXT_KEY_CIV5_SINGAPORE_TEXT';
